### ISSUE TITLE
Segmentation fault in fiducial agn model: only occurs with certain gcc versions 

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#100]
@smangham has found a rather annoying little bug in which a fiducial model with 200,000 photons (less than usual) crashes with a segmentation fault just after init_freebound. 

Reproducing the error is hard, to say the least. So far I've been able to reproduce it in two specific circumstances:
- Ubuntu 14.04.1 (Sam's machine), using gcc 4.8.2 with the -O3 flag on
- Iridis, using gcc 4.8.1 with the -O3 flag on

Early versions of gcc, e.g. 4.2 and 4.4 don't produce this error, and using -g -pg flags instead of -O3 means it runs fine. It would appear this is something to do with optimization changes in gcc. From the gcc release notes for gcc 4.8.1: 

"A new option -ftree-partial-pre was added to control the partial redundancy elimination (PRE) optimization. This option is enabled by default at the -O3 optimization level, and it makes PRE more aggressive."

Working on it- It's good that we are now running tests on multiple architectures. @Higginbottom have you seen anything similar before?

**Comment by kslong** [comment]
James will try to reproduce with that flag turned off.  If it not longer occurs, he will close.  (He will remove the check in the Makefile that turns off the aggressive compiler obption)>

**Comment by jhmatthews** [comment]
This error still occurs with new versions of gcc when I turn off the -fno-aggressive-loop-optimizations flag. Unsure how to proceed, really we want to understand what causes the segfault but don't have a good means to do so. Looking into xcode and other ways of diagnosing.

**Comment by kslong** [comment]
This sounds for all the world like we are overwriting memory for an array out of bounds, which overwriting memory.  It might not be harmful without aggressive changes.  I wonder if we can run this with some memory tracking tool.  I remember using Electric Fence in the past, but it was a long time ago.

**Comment by Higginbottom** [comment]
So this only happens if we use gcc rather than mpicc right? One way of diagnosing it might just be to check out older versions of the code and see the change that makes it happen??
Does the error happen quickly when running the code, or does it takes ages?

**Comment by kslong** [comment]
I was able to reproduce the error on my Mac, after compiling with -g, which meant I was able to find the location of the error.  Here it is:

![screenshot_418](https://cloud.githubusercontent.com/assets/2530901/16546068/541b2bba-4104-11e6-9b2a-1be8e00854ac.png)

Assuming ddd/gdb is working correctly, it looks likely that the variable gaunt_n_qsgrd is very large.

Initially after getting the atomic data, the value of this is 41.  Setting a watch point on the variable gives the following result:

![screenshot_419](https://cloud.githubusercontent.com/assets/2530901/16546221/ed372da4-4108-11e6-8306-53bf4685a20d.png)

The problem is that nput=10, and if one looks in python.h, NFB which sets the size of the freebound array is also 10.  So this is a clear case of overrunning an array.  

Historical note: Originally, ksl wrote routines that wrote the freebound arrays out to disk in order to speed the program up. The idea was that once you had these arrays written out, you would not have to calculate them again in the next run.  Today, there really is no justification for this, in part because we change frequency bands many times now and in part because this calculation is not a major component of the calculations we do.  So in solving this problem, we should probably remove the portions of the code that write the results to a file and read them back.

**Comment by kslong** [comment]
The segmentation problem should now be solved.  It is quite surprising to me that this problem had now shown up sooner, and with other compilers,  as we were clearly writing outside of the allocated memory space for recombination cooling.  Possibly, the agn fiducial model simply was the one that required the most different band passes.    

I would appreciate @jhmatthews or @smangham  running all of the regression tests with version of gcc-4.8 to make sure there are no other issues.
