### ISSUE TITLE
Implement microclumping 

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#108]
We would like to implement micro clumping into Python.  

In micro-clumping one assumes clumps are optically thin at all wavelengths, which means that one does not need to resolve the clumps in your grid, since the radiation field is not altered by clumping.  It is used in O-star winds, despite the fact that the physical assumptions associated with microclumping are not met in these winds, any more than they would be in the cases we want to use.

To implement, micro clumping, I am:
1.  Adding a new parameter for clumping.  geo.fill.  Thus for now, we assume there is a uniform filling factor for the wind.  
2.  Changing the meaning of the values in the Plasma structure to be the values in the filled portion of the wind.  Basically what this means is that once the smooth wind density is established, we simply increase this by 1/filling_factor.  At the same time, we multiply the volume that is in the Plasma array to be 
3. In resonate.c, multiplying the opacities, both for lines and continuum by the factor f.  

As long as all functions like luminosity are calculated with the volume that is in the Plasma structure, the heating and cooling ought to work out.  Note that resonant scattering if it occurs, occurs in the "clumped" gas, so we should not need to modify anything having to do with escape probabilities etc.

**Comment by kslong** [comment]
Micro-clumping does seem to work as anticipated in Python.  It affects both the continuuum and the lines in CV wind models

**Comment by kslong** [comment]
Here is an example of the effect of micro clumping on a CV model.  The clumping factor for these simulations was 10.

Unclumped
![sv spec_tot](https://cloud.githubusercontent.com/assets/2530901/4251102/50a07bac-3a8a-11e4-9e58-56c0a8f78864.png)
Clumped
![sv_clump spec_tot](https://cloud.githubusercontent.com/assets/2530901/4251118/6a3d3636-3a8a-11e4-968b-fe09fc26379e.png)
Unclumped
![sv_macro](https://cloud.githubusercontent.com/assets/2530901/4251126/80c75b16-3a8a-11e4-8570-6032fff9e8bd.png)
Clumped
![sv_macro_clump](https://cloud.githubusercontent.com/assets/2530901/4251134/8f95986a-3a8a-11e4-883f-ce73ce31eb67.png)

**Comment by jhmatthews** [comment]
Currently we multiply tau_sobolev by the filling factor in calculate_ds (i.e. in the absorption part of the code) but we don't do the same when calculating, for example, p_escape. This should be done along with a review of any place where sobolev optical depths (e.g. line luminosities from the wind, anisotropic scattering) are used to make sure we understand where the filling factor should come in, and why.

**Comment by jhmatthews** [comment]
There are a number of places where we use the sobolev optical depth for various calculations. 
- The routines which increment the estimators for macro-atoms are passed the tau_sobolev which is calculated in calculate_ds, and thus they have the correct tau*fill_factor. 
- P_escape doesn't currently have the fill_factor in it, and I believe the taus should be multiplied by it
- The other thing I am unsure about is what happens within the scattering fraction routines which are used to calculate line heating need any additional factors of geo.fill in there...I _think_ they don't, and it just comes in through P_escape, but we should thing carefully about this. 
- For the anisotropic scattering routine, nothing really needs to be done because one only cares about relative

**Comment by jhmatthews** [comment]
This is now implemented. Understanding the effect on models and physical conditions is the next step, but it's closed as an issue for the moment.
