### ISSUE TITLE
Installation issues for new users

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#109]
At present, make install fails on systems without mpicc; this is an impediment for new users.  
The problem is that we need a configuration stage for the make, which we do not currently have

In addition, make causes many new files to be pulled from git hup which is not normal.  This may be necessary in git but it is not what folks expect.

**Comment by jhmatthews** [comment]
Configuration step is a good idea, or at least a check in the makefile itself.

Regarding the install. Ideally we would have a repository which actually contained the folder structure, i.e. the whole Python directory with subdirectories and including the atomic data and source code.

Example here: https://github.com/agnwinds/python/tree/release_example

I am happy to do my development work like this, as one can just "git checkout" different versions if one wants to do a regression test or similar. The problem is that this is not how development work on python has traditionally been done by e.g. Nick and yourself, and would also make the format difficult when it comes to backwards compatibilit, or testing old versions, but for a public release it is definitely the proper way to do things.

Thoughts welcome.

**Comment by kslong** [comment]
My current concern about simply using git is just the size of the download, since it stores all of the versions internally.   

I think we should develop the .configure steps first and work with that for a while before we adopt a "release" strategy that differs from the way we develop.

**Comment by jhmatthews** [comment]
So I agree that in general that isn't how one would do it, but if we adopted a directory structure which already had everything in then we could just use the github releases page to manage everything, and a user would just download a zipped up release.

**Comment by jhmatthews** [comment]
This issue can be closed once I have 

a) written a configure script which works in terms of mpicc and gcc, at a bare minimum. Making it cleverer would be desirable.
b) changed git to track the entire folder structure.

**Comment by jhmatthews** [comment]
I've created a configure script. All it does is:
- takes Makefile.in as input, copies to Makefile
- check for mpicc and gcc
- replaces the command in the Makefile using sed. 

Probably not completely robust so something better should be done, but it's ok for a short term solution.
