### ISSUE TITLE
wavelengths in source spectrum

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#116]
ksl changed the structure of the output spectra to explicitly include one spectrum which was just the spectrum of a source (unreprocessed by radiative transfer).  This was done by adding a variable to the photon pointer that contained the original photon weight.  James points out that with a macro attom the wavelength can also be changed, so one needs to add another variable, the original wavelength.  

This is a simple change but it needs to be coded and tested.

**Comment by jhmatthews** [comment]
@kslong - I'm just implementing this and testing. Currently you have this Created spectrum being incremented inside this if statement

```
      if ((i = p[nphot].istat) == P_ESCAPE)
    {
```

which means it ignores weight attenuation but doesn't record created photons which didn't escape. I presume we want this outside that if statement, so that even if the photons hit a surface or scattered too many times we want them recorded in the Created column?

Another thing to note is that there will be a fundamental difference in this column depending on whether macro-atoms are used. In the macro-atom mdoe packets are indivisible, so if the spectrum has a disk and star then the created column really will be just disk + star, whereas in non-macro atom some 'reprocessing' has already been calculated by doing the wind emission and thus could feature some lines.

**Comment by jhmatthews** [comment]
I've decided to do this as I've described above. I've added a freq_orig variable to the photon structure which is used to increment the Created spectrum. I've also moved the created spectrum out of the P_ESCAPE if statement.
