### ISSUE TITLE
KSL130405:  Structure of Data files  

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#13]
**Current Status:**   Unsolved
**Priority:**   Medium  Enhancement
**Version discovered in:**  N/A
**Brief statement of problem** Knox and Nick now are using different forms of the data directories and we need to decide what is best
**How to reproduce:**  See the agn standard model data file run110e.pf
**Discussion:**   At present, Nick appears to have adopted a data structure that has atomic73 as a subdirectory of atomic.   Thus one specifies the atomic masterfile  as atomic73/standard73,  and the masterfile has  include atomic/atomic73 as part of the name of each file .  This is extremely confusing, .  Instead, atomic73 should be at the same level as atomic.

**Comment by jhmatthews** [comment]
### @kslong - here is mine and  @Higginbottom proposal for this fix.
- We would merge data and data66. Inside data it would look like this:

![screen shot 2013-07-10 at 15 50 45](https://f.cloud.github.com/assets/3007249/775375/73a102aa-e970-11e2-93dc-45c28febc8ab.png)
- Inside atomic it would look like this:

![screen shot 2013-07-10 at 15 52 58](https://f.cloud.github.com/assets/3007249/775377/757e4c72-e970-11e2-96d4-8b5aee561db4.png)

Then the standard73 files would point to those subdirectories. i.e. they would look like

```
#This is the standard set of data files created for python73
atomic/atomic73/elem_ions_ver.py
atomic/atomic73/topbase_levels_hhe.py
atomic/atomic73/topbase_levels_cno.py
atomic/atomic73/levels_ver.py
atomic/atomic73/lines_linked_ver.py
```

This would lead to the files being more organised, but preserve the atomic/standard73 in the pf and windsave files, which we think is more improtant. 

Open to suggestions though- just let me know the format and I will implement!

**Comment by kslong** [comment]
James, Nick,
I think this is reasonable, but wonder whether one should  do away with the level of atomic altogether and just have a data directory, and put things like
standard39, and the various atomic directories there.  I guess the argument for atomic is that one would isolate atomic process from other things, but atomic may not be needed.

Whatever is done, what I would like to have is a script like the one I use to set up an new directory.  The current version of the script I have is

# This is a simple routine to set up links so that python can be run in

# a directory

# 05aug   ksl   Coded

# 0603  ksl     Modified so others could use this as well

  top=$PYTHON

# top=~/Python/

xdata=data66

ln -s -f $top/$xdata/atomic
ln -s -f $top/$xdata/kurucz91
ln -s -f $top/$xdata/hutdisk93
ln -s -f $top/$xdata/disk06
ln -s -f $top/$xdata/atomic73

but perhaps we want something simpler that links the data directory to the local directory, and then has the standerd input files there.

We could just have a simple ln to the place where the data is stored and make minor mods in python itself to locate all the data, e.g kurucz91 files.

Cheers,
Knox

**Comment by sirocco-rt** [comment]
Yep, my script looks like that (with a few differences), and we may have to dit that slightly if we do change.

The only problem with that structure you propose is old wind save files will not work as they won't be able to open atomic/standard73, and I think I also favour having atomic separated from disk models etc.

**Comment by kslong** [comment]
The problem with the old wind save files is straightforward

"ln –s  whatetever/data atomic"  for old runs

A single directory to link data will be more robust for future changes I think.  and shorter filenames in the master input file.

The setup command would not need to be revised if we add a new set of disk or star models.

But … it is your decisions.

Knox

P. S.   git on reply does not give the name of the author

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
Ah yes, silly me. Ok, that sounds reasonable then, I will create a tarball of the new structure.

And I think git does but I accidentally left myself logged in as 'agnwinds' which is the account which I use to host the site.

**Comment by jhmatthews** [comment]
@kslong @Higginbottom 

https://github.com/agnwinds/python/tree/data 

is a branch containing the new data structure- you can either zip it up there or go to tags to download a tarball.

At the moment, this does not include atomic50, atomic49, And someone who is more familiar with the old atomic data should check that what I've included is complete. The folder includes the new format for the Setup_Py_Dir script.

Issue now closed, with caveat that this may continue to be improved.

**Comment by jhmatthews** [comment]
Just a quick note on this- you could now keep your atomic data folder under control by having it as a git repository

e.g.

$ mkdir $PYTHON/data
$ cd $PYTHON/data
$ git clone https://github.com/agnwinds/python.git -b data .
