### ISSUE TITLE
Style - Enums

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#148]
The code makes a lot of use of integers and lists of integer aliases for states (e.g. wind.inwind and the W_ALL_INWIND etc. list) that are functionally equivalent to enums, but doesn't actually include any enums. 

Is there a policy against using enums, or is this just a case of personal preference? Would anyone be opposed to the use of enums in new code?

**Comment by Higginbottom** [comment]
what's an enum?

**Comment by smangham** [comment]
An enumerated list, they're declared and used like below (where the 0 = default):
<i>enum {VR_NONE=0, VR_IONISATION, VR_SPECTRUM, VR_BOTH_CYCLES} vr_type;</i>
<i>if(vr_type != VR_NONE) [...]
vr_type = VR_BOTH_CYCLES;</i>
On compile they're converted to the sort of int & series of #define ints that we use extensively. They're just neater (currently our #defines can be dozens of lines away from the variable they're associated with) and allow for compiler checks for invalid sets.
You _can_, if wanted, set values for the other enum values (e.g. VR_IONISATION=1) and compare between enums, read ints into them etc. so there's no loss of functionality compared to ints, you'll just get warnings about anything that the compiler can't properly check.

**Comment by Higginbottom** [comment]
Thanks! I guess I have no particular problem with using them, how much of the code needs to be changed? Are the comparisons that crop up everywhere like if(geo.wind_type = proga){ 
still valid, or is there a different syntax? If so, it might be a bit of a drag to go through and change everything.....

**Comment by smangham** [comment]
Well, I wasn't proposing refactoring into enums, just adding new enums instead of new ints/defines in my code. Though all the syntax should be the same so a refactoring would be easy AFAIK- the only bit where the syntax might be an issue is using rdint to fill enums in the get_params section, and even then you'd just get a warning.

**Comment by kslong** [comment]
My question was the same as NIck’s, so I looked it up.

The reason enums are not in PYTHON is that they do not exist in KR c which is what I learned.  Indeed, when PYTHON was initially written we used integers for choices.  I replaced that with the #define statements to make it easer to keep track of what we were actually doing as the code got more and more complex.

Enums may be reasonable now; they are part of ANSI C so it should not matter as a matter of portability.

However, if we should take this course, then I think we would need to have a commitment make it the standard, rather than #define. I think before making any decision one should explore the ramifications a  bit.  We currently use choices like if geo.whatever=XXX.  I’m not really sure how this works.  I guess you define whatever as an enum.    Anyway, Sam, since you suggested this I think you need to tell us what it would mean if we went this route.

As an aside,  I also  think we ought to keep them all CAPS

Knox

**Comment by smangham** [comment]
The implementation would involve replacing constructs like

``` c
#define PTYPE_STAR      0
#define PTYPE_BL        1
[...]
typedef struct photon 
{
    [...]
    int origin;
}
```

With constructs like

``` c
typedef struct photon
{
    [...]
    enum {PTYPE_STAR, PTYPE_BL, [...]} origin;
}
```

Otherwise, all the syntax should be unchanged. I've found a detailed post on StackOverflow explaining the advantages of enums over #defines: http://stackoverflow.com/a/1944061

The advantages of enums for python will mostly be readability and ease of maintenance. It's instantly clear to the user which ints are actual integers, and which refer to a list. If merging a commit that adds a new wind type, for example, into a branch that has also added a new wind type the two additions of <i>#define WIND_NEW1 = 12</i> and <i>#define WIND_NEW2 = 12</i> won't show up as a conflict, whereas modifications to an enum would (but would then be solved immediately by just adding the extra WIND_NEW2 key to the enum). There are already some clarity issues with #define lists as there are two (currently identical) PTYPE lists in python.h, one 300 lines away from the photon struct definition. 

The other main advantage is enum key names will appear in some debuggers, making it easier to track down if the code is trying to refer to a nonexistent (or unexpected) wind type, for example. 

The main disadvantage would be either having a number of warning statements appear in compile when rdint is used to fill an enum or having to rewrite them to read to a temporary variable then set the enum based on that. That would be a minor change and would put into the code a very clear link between the enums and file values that's easy to find if you're wondering how the read-in process works. As mentioned though you can assign numbers on enum options as WIND_NEW1=12, WIND_NEW2=13 and use rdint without modification.

**Comment by kslong** [comment]
I agree our #define statements have proliferated.  I can see how this might make our header files more readable.

So, I can still write in your example below

If (photon.origin==PTYPE_STAR) {
Do magnificent things
}

I guess one could write a new routine

rdenum

Or something that would be distinguishable from rdint, and it could check if a variable was an allowed .  Would that be advantageous since we do still need some pure integers.

I would definitely like to avoid having warnings in the compile stage.

**Comment by jhmatthews** [comment]
This gets a big thumbs up from me. Agree re CAPS, and agree that we should just tweak the readin stage to avoid compilation warnings. We might want to test this on a few different compilers and just need to be careful when converting from define to enum. We'll still want define statements generally in the code for some constants and values, but perhaps enums should be the defaults for "switches" or modes.

**Comment by kslong** [comment]
So the only question that remains is who is responsible for doing this.  Sam, since you brought this up, you probably ought to start.  I’d suggest beginning on the “internal variables” that don’t involve kpar.  And maybe, we ought to create a small toy program just to look at how to handle inputs from a .pf file.  Or at a minimum let’s write down exactly how we want to handle this.

**Comment by smangham** [comment]
I had actually just finished a quick first pass of the code with enums as a demonstration at: https://github.com/smangham/python/tree/enum
It only changes the header file and a single line in python.c- everything else works unchanged. It has no extra warnings as the only read in from a parameter file is first read to int then explicitly cast as an enum type as <i>geo.system_type = (enum system_type_options) temp_int;</i>. A few extra warnings _are_ raised, but they appear to be for actual concerns like comparisons with photon origins that will never evaluate as false given the range of available origins.

I didn't change the IONMODE/NEBULARMODE defines as the links between their values would require a (slightly) more involved look, or alter wind types. There are also several variables that _could_ be enums but don't have #define lists e.g. line_mode, scatter_mode, disk_type and converting them would require a little more effort. Equally, it would increase code clarity if we had <i>if(geo.scatter_mode == SCATTER_ISOTROPIC)</i> rather than 0/1/2 etc. 

If we're changing how wind types are read in, for example, one question would be whether to still use a numbered list in the input file or whether to use strings (e.g. <i>Wind_type SV</i>). The other possible option would be:

``` c
rdint(question,answer_int);
if(answer_int == 0)
  answer_enum = ANSWER_ONE;
else if(answer_int == 1)
  answer_enum = ANSWER_TWO;
[...]
```

Which is clunkier than just using a cast (even if switch/case is used instead) but is a bit clearer.

**Comment by kslong** [comment]
I think if we are going to go this route, then we have to deal with the rdint issue in a less clunky fashion.

While this approach does have the advantage that we can see explicitly what is being assigned in the coed, I think what we want is something that hides all of the … if else stuff, and also checks for valid answers.

Note that a worry I have is that if someone adds a new value for an enum and if that someone is not careful, we may lose the connection between the input integer and the value of the enum.   How to we avoid, and/or check that this is not happening?

**Comment by smangham** [comment]
The neater option than an if list is a switch/case e.g.

``` c
switch( rdpar_return_int("System_type") ){
  case 0: geo.system_type=SYSTEM_TYPE_STAR; break;
  case 1: geo.system_type=SYSTEM_TYPE_BINARY; break;
  case 2: geo.system_type=SYSTEM_TYPE_AGN; break;
  default: Error("System_type invalid!\n");
```

As opposed to

``` c
geo.system_type = (enum system_type_enum) rdpar_return_int("System_type");
```

There doesn't seem to be a standard c way to do bounds-checking on enums, and all the 'simple' enum bounds check techniques I've seen assume that enum values are contiguous, which I don't think is universally the case. I think the clarity and error proofing of enums _requires_ that the code is more explicit.

Switch/case can also be used when reading from an enum, and there are standard c flags that can be used to throw up warnings if a switch/case doesn't include an enum option e.g.

``` c
switch(geo.coord_type){
  case SPHERICAL: spherical_make_grid(w); break;
  case CYLIND: cylind_make_grid(w); break;
  case RTHETA: [...]
  default: Error("Coord_type invalid\n");
}
```

Will throw up compiler warnings about the missing CYLVAR enum option. 
I'm not quite sure how we would lose the connection between the input int and enum value- the compiler won't let you add two enums with the same value, so even if this happened during a merge it would throw up errors. The best way to prevent collisions or confusion would, I think, be to use the switch/case statement method of input as it's clear what values are available.

**Comment by kslong** [comment]
I agree that the first option looks pretty clean.

I was worried that we would end up with s statement  like,  geo.coord_type=whatever[I], where I was the integer and whatever was the enumerated list.  That probably reflects my lack of experience using enums.

I see, if we go this route, we have to write a new routine for rdpar, which is fine.  It was written the way it was for historical reasons.  I’d suggest we start a new series, get …, so would propose rather than rdpar_return_int. we simply cal this get_int, etc.

Finally, I believe James had suggested we pull the reading of the rdpar file out of the main python routine, for a variety or reasons.   I believe this is issue #136   I would suggest we handle both of these items at the same time.

**Comment by jhmatthews** [comment]
Much of it has already been moved to setup.c which goes about the setup procedure. I stopped short of making a file which just read the file and basically just moved code to subroutines.

**Comment by kslong** [comment]
Yes, I see, James.  I had not looked at this, and what I looked at it quickly I saw various rdpar statements stil there. .  Looking at it now it still seems to me there is work to be done, but I need to think about what.

There is still a fair bit of logic in main.  I guess what I was thinking we were trying to do was use “setup” to completely populate geo, atomic, etc,.   That of course would still not be hard to do.  Maybe though what you have done is pulled the easy bits out, and what is in main may indicate there are things we should think about more generally.   A first step, would be to revise the inline comments in main so that one could follow the logical flow.

**Comment by jhmatthews** [comment]
yes, agreed. I definitely took the easiest / least dangerous option. It is at least mostly in one place now which should make future work easy. The spectral cycles set up is one thing I'd been meaning to improve with less hardwired memory allocation + structures, and now would appear the perfect time to address this.

**Comment by jhmatthews** [comment]
Discussion continued in #162
