### ISSUE TITLE
Large numbers of Error- trans_phot: Trying to scatter a photon which is not in a cell in the plasma structure

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#154]
In some recent runs I've been getting huge numbers of the following errors:

```
trans_phot: Trying to scatter a photon which is not in a cell in the plasma structure
```

I can't put my finger on exactly what models are most likely to do this at the moment- I do however think I've figured out how it happens, and it's pretty silly. The basic procedure for translating a photon is to either call translate_in_space (if it is outside the plasma) or translate_in_wind. if you call translate_in_wind then that routine will use calculate_ds to decide if you scatter or not. if you scatter, you return istat=P_SCAT to the trans_phot routine which then tells it to call scatter and generate new directions etc. Crucially, you also up[date the istat variable stored in the photon structure for that photon.

Once you've done all the rest of the stuff in trans_phot for this path element, you update the _local_ istat in trans_phot back to P_INWIND, so you stay in the while (istat == P_INWIND) loop. However, you _don't_ reset the one stored in the photon structure.

Now, say you scattered along the edge of the wind, and then you called reposition which moves you DFUDGE in your new direction. This could feasibly take you outside the edge of the wind, but istat will still be set to P_INWIND. Furthermore, your photon istat will not be updated, because for some reason it isn't updated at the end of the while loop in trans_phot. This then means that next time round you are translated through space despite istat being P_INWIND, istat in the photon structure is set to P_SCAT and you enter the error message.

So I think what should probably happen is the photon structure istat should be updated, there should be a few more error conditions to catch weird things and there should be a check that the photon is still in the wind after reposition.

**Comment by jhmatthews** [comment]
I've confirmed that if I choose a single photon which previously caused this error, and remove the reposition statement at the end of the trans_phot while loop, so pretty sure my explanation above must be the problem.

**Comment by jhmatthews** [comment]
I think the correct fix here is actually fairly simple. One should simply call 

```
istat = walls (&pp, p);
```

after the call to reposition() in trans_phot.c. This will tell you if the photon is still in wind, will escape to infinity or will hit disk/star/other side of wind. I'm also adding a counter which counts how often dfudge pushed a photon out of the wind which throws an error once per cycle if this is >0 - so we can track this. 

related note - @smangham did you see large numbers of photons in the edge cells and did you figure out if this was a real effect?

**Comment by jhmatthews** [comment]
This is fixed now. A few changes - go to commit to see diff: https://github.com/agnwinds/python/commit/4a9f78cf5d97a16c65182a7a93faf816853640a7
- comments added to trans_phot.c, to describe routine trans_phot_single and some detail on this issue
- the call istat = P_INWIND at the end of the while loop is changed to istat = pp.istat = P_INWIND - this is so if it has scatter+dfudged outside wind then pp.istat is not still set to P_SCAT
- after this there's a call to walls, just to check that dfudge didn't bounce it back into the disk/star. I don't know if this ever happens but worth a check
- finally, I check if it has scatter+dfudged outside wind, and if it has increment a counter which is reset each cycle. This counter reports an error once per photon flight if it is > 0 - which is probably will be. 

I'm not closing this issue yet because I'm getting quite large numbers in my counter and what to understand why...

**Comment by jhmatthews** [comment]
Right. Finally all good here. I've checked all these events happen on the edge of the wind and behave as expected. I would just suggest that everyone keeps an eye on the numbers of these that happen. I'm getting 246 events / 1e6 photons. Possibly a little higher than I would expect but I think it depends fairly critically on the model you use- this has high grid res and high opacities. ALL the events happen on the edge of the wind closest to the central source. Closing.

**Comment by kslong** [comment]
I am getting a fairly large number of these issue 36000 in 10**6 photons in my attempt to create a disk atmosphere in domain2.   My atmosphere has inner and outer "radii" of 9e6 and 4e8, and height of 1e7.  All of the photons that are doing this have height just above 1e7, and are going out of the atmosphere in this direction.

This looks like either something related to DFUDGE, or alternatively it is possible that we have cells that we are not getting the right volume for.  However, I checked that the edge boundary is exactly at 1e7, so this makes it appear that it really is a DFUDGE problem.

However, how is that a photon can scatter in a region outside the wind.  The reason is that in translate in wind we add dfudge to the smax calculated from the cell boundary, before calling calling calculate_ds. This leads to the possibility of ending up with a scatter that on the outside of the cell.  Then, if your cell boundary is also a wind boundary, which is the case for a disk atmosphere, then one has scattered in a cell which is outside the wind, which generates a problem.

All of this begs the question of how we are using DFUDGE, and when precisely it should be applied.  The concept of DFUDGE was introduced to make sure a photon would not get caught at a cell or wind boundary.  It also made was intended to make sure there was no ambiguity in calculating something like a velocity.  

I am reopening this as an issue.  @jhmatthews @Higginbottom  Thoughts are welcome

**Comment by kslong** [comment]
Dom2 now implements a variable DFUDGE once a photon is in the wind based on the size of the cell.  This reduces the number of occurrences of this problem very significantly.  It is possible that there are other solutions to this involving changing the point at which DFUDGE gets added to smax.

**Comment by kslong** [comment]
We believe this problem is solved.  None of us has seen it recently and the code has been changed as discussed above.
