### ISSUE TITLE
large number of sane_check errors in pop_kappa_ff_array

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#176]
When running QSO models with Helium macro-atoms turned on, I get large numbers of the following error

```
pop_kappa_ff_array:sane_check sum is -nan this is a problem, possible in gaunt %3
```

This function calculates a prefactor for free-free heating/cooling calculations in advance, as the prefactor depends only on ion densityies temperature and physical constants.

I think there are a few issues here:
- first, something fairly drastic is clearly going wrong in the Helium matom runs, possibly related to having low photon numbers and trying to solve all those level populations. My bet is the reason this particular happens is a knock on effect from something else, rather than a direct problem with the pop_kappa_ff_array() function.
- which makes me think that there is probably somewhere earlier in the code where really a fatal error should have been caught. I will debug at some point to figure out where.
- thirdly, it reminds me that there are many places in the code where Error messages might tell _us_ what is going on, but wouldn't tell a _user_. If we want to public release this code, then this is a pretty major thing to sort in my opinion. Errors should probably be informative enough so a user knows what they have done wrong or need to change/report- I think we are probably all guilty of making our Error messages a little specialised.

**Comment by kslong** [comment]
With regard to error messages,  I agree with James, though I think the standard of having a user understand what is going on may be too high.  I would propose another standard and that is that any of us be able to actually understand the message.  I’d urge everyone, when you are updating a subroutine to look at the Error messages and update them as necessary.

I will also say that in looking at the domain2 code, which forced me to look at a lot of things, there are times when it is obvious that someone wanted to do a quick fix and in some cases put in a “kluge” to solve their problem (sometimes commenting that this is what they had done).  We need to avoid this, because no one is really out there looking over other peoples shoulders, so these “kluges” stay in the code.    I am as guilty of this as anyone.

**Comment by jhmatthews** [comment]
I was hoping this specific problem may be solved by the solution to the Helium problem (https://sites.google.com/site/agnwinds/current-work-in-progress/nextgen-qso-model/changes-w-he-macro-atom) but alas it is not. Working on it!

**Comment by jhmatthews** [comment]
This problem seems to be caused by Helium matom densities being NAN in low density, highly ionized portions of the wind. One obvious thing that should be done is to have sane_checks() in the macro_pops calculation. I am debugging the actual cause of the NANs now.

**Comment by jhmatthews** [comment]
A few more details here. It's kinda difficult to figure out exactly why this is messing up. The cells where it happens all have the following properties:
- partially in wind
- generally seem to be along the leading edge of the wind so well exposed to the X-rays
- really low densities: ne can be as low as 100!

And the models which this occurs seem to be generally lower density: i.e. wider opening angle models with faster accelerating winds.

I've tried a few tests.

First I suspected that numerical problems (noisy estimators etc) were causing this. I tried adding in something where if we get non-sensible level populations then we replace the estimators with dilute BBs and try again. This allowed one to get sensible populations, but gave the following error later in the actual macro-atom machinery during photon propagation:

``` C
Error ("Negative probability (matom, 6). Abort?\n");
```

which happens when the correction for stimulated recombination is greater than the photoionization rate estimator (alpha_st \* ne \* n_u / n_l > gamma). Is this linked to our problem? Problem is numerical and related to the bound-free continuum of He I?

I've also tried truncated the Helium I levels significantly -- hypothesis being that maybe our bound-bound estimators are the ones giving us problems. We still get negative populations with one Helium I level. Again, implies a problem in the b-f.

Finally, I tried setting a minimum density floor of ne = 1e4. This seems to help and allows the model to wrong, but seems like a bit of a fudgy way to solve the problem...

Final question. Why do we seem to get densities of ~100 in partially in wind cells when n eighbouring cells have densities orders of magnitudes higher? just due to the divergence of the wind and not resolving the density structure / streamlines particularly well? [cell of 1.7e+02 below is one of the ones which fails]
![screenshot 2015-11-27 11 34 41](https://cloud.githubusercontent.com/assets/3007249/11440518/e28fb7fa-94fa-11e5-8351-6697e42d873e.png)

For discussion in the telecon, but as you might be able to tell I'm struggling a bit!

**Comment by lazygun37** [comment]
Just two quick points:

1) It seems to me that your final question may be the first one we should sort out, because I just can't see how that's anything other than a bug. Orders of magnitude changes in density across cell boundaries just shouldn't occur if our gridding is resolving the wind reasonably well.The fact that these crazy low densities only occur in "partial" cells -- correct? -- also suggests this is a bug. In particular, it suggests that we are somehow not correctly setting up the conditions in these cells, i.e. our interpolation/extrapolation/weighting is going wrong.

2) Is it possible that the error itself is "physical", in the sense that there are physical processes that we have not implemented, but that would dominate in the (weird) regime that's occurring in these cells?

**Comment by jhmatthews** [comment]
This is closed with a few caveats (namely that we should improve collisions #188 ) by #192
