### ISSUE TITLE
Segfault in 1d_sn in domain branch

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#193]
I'm just doing some testing of the domain2 branch. Getting a segfault in the supernova model which could be indicative of a bigger problem. Either way the pf file ($PYTHON/examples/1d_sn.pf) is a useful test case and used to compare against tardis.

Here's the error:

```
MPI task 0 survived broadcasting plasma update information.
wind_update: note, errors from mean intensity can be high in a working model
wind_update: can be a problem with photon numbers if there are also errors from spectral_estimators and low photon number warnings
wind_update: mean_intensity: 0.0000e+00 occurrences, this cycle, this thread of 'no model exists in a band'
wind_update: mean intensity: 0.0000e+00 occurrences, this cycle, this thread of 'photon freq is outside frequency range of spectral model'
!!wind_update: Absorbed flux    0.00e+00  (photo 0.00e+00 ff 0.00e+00 compton 0.00e+00 auger 0.00e+00 induced_compton 0.00e+00 lines 0.00e+00)
!!wind_update: Wind heating     0.00e+00  (photo 0.00e+00 ff 0.00e+00 compton 0.00e+00 auger 0.00e+00 induced_compton 0.00e+00 lines 0.00e+00 adiabatic 0.00e+00)
!!wind_update: Wind luminosity  0.00e+00 (recomb 0.00e+00 ff 0.00e+00 lines 0.00e+00) after update
!!wind_update: Wind cooling     0.00e+00 (recomb 0.00e+00 ff 0.00e+00 compton 0.00e+00 DR 0.00e+00 DI 0.00e+00 lines 0.00e+00 adiabatic 0.00e+00) after update
[cosmos:08746] *** Process received signal ***
[cosmos:08746] Signal: Segmentation fault: 11 (11)
[cosmos:08746] Signal code:  (0)
[cosmos:08746] Failing at address: 0x0
[cosmos:08746] [ 0] 2   libsystem_c.dylib                   0x00007fff8d8508ea _sigtramp + 26
[cosmos:08746] [ 1] 3   py79d_dom2                          0x000000013c39bc00 qdisk + 0
[cosmos:08746] [ 2] 4   py79d_dom2                          0x00000001084ef89c wind_update + 28700
[cosmos:08746] [ 3] 5   py79d_dom2                          0x00000001085256e7 calculate_ionization + 1319
[cosmos:08746] [ 4] 6   py79d_dom2                          0x00000001084d36ae main + 2558
[cosmos:08746] [ 5] 7   libdyld.dylib                       0x00007fff947567e1 start + 0
[cosmos:08746] *** End of error message ***
Segmentation fault: 11
```

No real debugging done as yet.

**Comment by jhmatthews** [comment]
This is caused by writing to file in qdisk_save(), which is called in line 288 of run.c

``` C
      /* Calculate and store the amount of heating of the disk due to radiation impinging on the disk */
      qdisk_save (files.disk, ztot);
```

It fails here when there is no disk. Something is not being allocated correctly when there is no disk, but this only happens in domain.

**Comment by kslong** [comment]
This is failing for me at a different place
using gcc

Line 833 of wind_updates2d.c

wind_n_to_ij (wmain[nmax_r].ndom, nmax_r, &i, &j);

The number wmain(nmax_r).ndom looks completely wrong ( a large number on my Mac, -1 on linux)
![screenshot_313](https://cloud.githubusercontent.com/assets/2530901/12520142/67f6ee02-c108-11e5-991f-fa499b80c0ab.jpg)

At the point this is failing, it also appears that NPLASMA is 0.

Ultimately this appears to be because the volume of all wind cells are zero and this is because one_dom-> zmax is 0

When comparing the dev version of where_in_wind to the domain2 version it is apparent that the check for zmax is additional.  Presumably it was added for reflection.  

I fixed this problem, but now this is failing in init_freebound.  Why this problem should be associated with domains specifically is unclear.  It could be that something is still not defined correctly, and thus what is being passed to init_freebound is unreasonable.

**Comment by kslong** [comment]
This is a more general comment/musing.  Our way of defining the edges of the "wind" or of a domain has become somewhat complicated.  We use wind, cones, an inner radius an outer radius, a top (zmax) and the boundary of the disk.  I can imagine that in future we would like to define a spherical cloud.  We might want to think about a general way to define volumes that we think will cover everything.  

On the positive side, we have a single routine where_in_wind which is the only place one needs to got to check whether a domain is in the wind, which is good.    

We probably should be issuing an error, perhaps a fatal error if a defined domains ends up with no plasma cells.

**Comment by kslong** [comment]
The segmentation error I see now with init_freebound is a weird error.  

I see it with mpicc and gcc on the domain2 branch
I do not see it with mpicc on dev, but I do see it with gcc with dev branch

@jhmatthews you will probably have to expand the picture but this is what is happening:  fb_xtop->nlev is -1 (as you can see in the printout of fb_xtop at the bottom) and as a result one is accessing array element config[-1] which causes the segmentation fault.  This was, what I got from a run of dev/gcc.  This makes it look like this is really a problem with the setup of the atomic data, and has nothing to do with domains.

![screenshot_316](https://cloud.githubusercontent.com/assets/2530901/12524145/b0223908-c120-11e5-9506-6ba64f582c5c.png)

Notice that this points to ion 11.  One can print out the data for ion[11] and it shows   the data for that ion  is also quite incomplete.  It has no levels (and this information is transferred in to phot_top.  Something is clearly going wrong in get_atomic_data, and we do not have enough checks to spot the error.  (I can see that there were some modifications to get_atomic_data in 1508 in this portion of the code).

**Comment by jhmatthews** [comment]
@kslong -- I can't reproduce this error? Can you verify versions and pf files and when the code actually fails (i.e. which cycle).

**Comment by kslong** [comment]
@jhmatthews 
On linux I see the error on the dev branch compiled with gcc,  using the version of 1d_sn.pf I just pulled dev again and verified the problem.  The error occurs at the end of the first cycle on init_free bound.  (The error does not appear with mpicc, which I also rechecked).  

On my mac, when using clang, I do not see the error on dev branch.  However, the error reappears if one forces the make to use gcc, e.g make CC=/sw/bin/gcc-4 D python

The pf file was just the 1d_sn.pf file copied from  the Examples directory when on the dev branch.

**Comment by jhmatthews** [comment]
Thanks Knox. Still can't reproduce with clang or gcc on my mac or on endjinn which is ubuntu -- can you give me the output of `/sw/bin/gcc-4 --version`?

**Comment by kslong** [comment]
OK,  it is
gcc-4 (GCC) 4.8.2 on my Mac
on linux it is 4.4.7

but I can tell you what the error is, in any event.  If you look back up at the image where I printed out *fb_top, you can see that nlev is -1.  It turns out that ion 11, is Mg I, and if you look at the ion_ptr for this ion, it has phot_info = 0, which means it is a VKFY x-sections and not topbase ones
![screenshot_325](https://cloud.githubusercontent.com/assets/2530901/12799757/43c1b2fa-ca96-11e5-9c65-fde6ccbc1a77.png)

If you look back at get_atomic_data this should have been populated around line 1581 of get_atomic_data, but ion[nion].firstlevel is -1. There are several ions later on that also have this problem, e.g ion 17, which is z=12, istate=7.  

So my story, which I am sticking to for now is that there is some kind of problem in get_atomic data, and that adding lines of checking on the atomic_data files are probably needed.  

That said the problem could also have be caught in xinteg_freebound, where there are some other checks on when to actually integrate.  In this case though, I actually think the problem is that for some reason the level is not being assigned. We did read in the photoinization x-sections.

So @jhmatthews my suggestion is you first check whether you think ion[11] looks correct at the end of get_atomic_data, and in particular whether the firstlevel is -1 or not.  

(Note - I should add that all of this refers to the dev branch)

**Comment by jhmatthews** [comment]
Ah OK, sorry Knox, I got a little confused here. Will look into this tomorrow.

**Comment by jhmatthews** [comment]
The original issue here was solved by Knox above in this commit: https://github.com/agnwinds/python/commit/7ec284445f4a6d6df5fafdcbafb637799fe1a975

The new issue regarding levels and atomic data is now in #195
