### ISSUE TITLE
fb_topbase_partial tries to use level info that does not exist

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#195]
This is an offshoot from #193 -- Knox found an error in which init_freebound would fail because the code tries to access a level which is -1. See printout below.

![image](https://cloud.githubusercontent.com/assets/3007249/12755769/b8952db0-c9c8-11e5-945f-47f99d223bb2.png)

Notice that this points to ion 11. One can print out the data for ion[11] and it shows the data for that ion is also quite incomplete. It has no levels (and this information is transferred in to phot_top. Something is clearly going wrong in get_atomic_data, and we do not have enough checks to spot the error. (I can see that there were some modifications to get_atomic_data in 1508 in this portion of the code).

This causes a segfault for Knox but not for me. He is running 
gcc-4 (GCC) 4.8.2 on my Mac on linux it is 4.4.7

**Comment by jhmatthews** [comment]
I've verified that this doesn't happen for ion 10. So the problem is not so much in the levels but in the fact that we are trying to associate a cross-section - or do a recombination calculation into a bare ion.

**Comment by jhmatthews** [comment]
Ok so I've made some progress here. The reason this particular parameter file messes up is because for Magnesium we are providing Kurucz level information. BUT Kurucz data has no actual levels for Magnesium 1 -- only magnesium 2 and upwards. So, obviously, we never actually populate levels for this ion.

Question 1: Should we ever have a situation where we have ions with no levels? How did we deal with that in the past? 

Question 2: Should VFKY data require level information? As Nick has pointed out before, there should maybe be a different way of choosing multiplicities for VFKY cross-sections than for topbases as they are really cross-sections for ions, not levels. This wouldn't happen to an ion for topbase because we loop over levels to check there's a match for ISLP, level number, ionization state, etc.

**Comment by kslong** [comment]
Excellent news

In the past, there were separate ways of calculating the photoionization x-sections for VFKY, and so that is why this problem did not arise.   Originally, when VFKY was all there was the level information (to the extent it was used) was separated completely from the photo-ionization.   So we should look back and see what was done there. Presumably, we checked our digitization against the predictions.

Undoubtedly this problem was created when we switched from the approximation formula used by VFKY to a digitized, and tried to use the top_base machinery.

**Comment by jhmatthews** [comment]
Ok so I've had a look at what we did in the past, and we adopted the multiplicity of the ION rather than LEVEL. So I've made the following change in commit https://github.com/agnwinds/python/commit/906ddc6a5d855cb4e54ce7870b694e41143401d6:

``` C
  nion = fb_xtop->nion;

  if (ion[nion].phot_info == 0) // it's a topbase record
    gn = config[fb_xtop->nlev].g;
  else if (ion[nion].phot_info == 0)    // it's a VFKY record, so shouldn't really use levels
    gn = ion[nion].g;
```

This should fix the immediate issue and has been fixed in dev and domain2. @kslong  can you verify that it solves your segfault?

Outstanding questions:
1. Checking levels / cross-sections more carefully in get_atomicdata.c
2. Should an ion ever have no levels?

**Comment by Higginbottom** [comment]
I've remembered why the bare ions have a multiplicity of 1, rather than 2 as they were in the distance past. The point is that there is only one way of having an ion with no electrons - the spin of the proton doesn't come into it - if  did then there would be four ways of having one electron! Plus of course, the different nuclei have different spins, helium is spin 0 - so again having 2 for the multiplicity of every bare ion would also be wrong...

**Comment by jhmatthews** [comment]
Thanks Nick.

Also, I made a mistake in the above. I've corrected it so the first if statement is ion[nion].phot_info > 0. Duh!

**Comment by kslong** [comment]
The 1d SN model no longer fails running clang or gcc-4 on my Mac, and it no longer fails using gcc on RedHat linux, so the basic issue seems solved.  (Note that the various compilers do give some warning messages on compilation that at some not too distant point, we/I should try to eliminate. The two Mac compilers seem to be the most picky)

**Comment by jhmatthews** [comment]
Updated this fix to catch the case where the ion doesn't have phot_info by adding an error condition, as Knox suggested. Closing now.
