### ISSUE TITLE
Segfault for thin shell in domain2

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#205]
Getting a segfault at the end of thinshell models in domain2 at the moment

```
wind_update: mean_intensity: 0.0000e+00 occurrences, this cycle, this thread of 'no model exists in a band'
wind_update: mean intensity: 0.0000e+00 occurrences, this cycle, this thread of 'photon freq is outside frequency range of spectral model'
!!wind_update: Absorbed flux    0.00e+00  (photo 0.00e+00 ff 0.00e+00 compton 0.00e+00 auger 0.00e+00 induced_compton 0.00e+00 lines 0.00e+00)
!!wind_update: Wind heating     0.00e+00  (photo 0.00e+00 ff 0.00e+00 compton 0.00e+00 auger 0.00e+00 induced_compton 0.00e+00 lines 0.00e+00 adiabatic 0.00e+00)
!!wind_update: Wind luminosity  0.00e+00 (recomb 0.00e+00 ff 0.00e+00 lines 0.00e+00) after update
!!wind_update: Wind cooling     0.00e+00 (recomb 0.00e+00 ff 0.00e+00 compton 0.00e+00 DR 0.00e+00 DI 0.00e+00 lines 0.00e+00 adiabatic 0.00e+00) after update
[cosmos:46092] *** Process received signal ***
[cosmos:46092] Signal: Segmentation fault: 11 (11)
[cosmos:46092] Signal code:  (0)
[cosmos:46092] Failing at address: 0x0
[cosmos:46092] [ 0] 2   libsystem_c.dylib                   0x00007fff8d8508ea _sigtramp + 26
[cosmos:46092] [ 1] 3   py80_dom2                           0x000000014229dc10 qdisk + 0
[cosmos:46092] [ 2] 4   py80_dom2                           0x000000010e3f1383 wind_update + 28851
[cosmos:46092] [ 3] 5   py80_dom2                           0x000000010e427456 calculate_ionization + 1318
[cosmos:46092] [ 4] 6   py80_dom2                           0x000000010e3d50ee main + 2670
[cosmos:46092] [ 5] 7   libdyld.dylib                       0x00007fff947567e1 start + 0
[cosmos:46092] *** End of 
```

Haven't had a chance to debug, but wanted to flag. It prevents running of thin shell ionization loops for testing purposes.

**Comment by jhmatthews** [comment]
Related to #190 ?

**Comment by kslong** [comment]
This is probably the same error that has affected the other spherical model examples.

**Comment by kslong** [comment]
@jhmatthews  @Higginbottom   This turned out to be an interesting problem.  Ultimately, the error was that setup_dfudge which sets DFUDGE was based on geo.wind_type, but domains allows one to have mulitple wind_types in the same model, and this is stored in zdom[ndom].wind_type.  However, setup_defudge establishes a global DFUDGE.  In reality, we need to relook at how dfudge is setup.  It probably should be done on a cell by cell basis, depending on the size of the cell.  

For now, I have assgned geo.wind_type to be what is read in for the last domain.  Results between domain2 and dev, for template_ion_loop.pf are now similar.  No segfault.  Some photons in right cells, but the number of photons in the cell still differs by 15%, not exact as one would expect.

**Comment by kslong** [comment]
This is now fixed, at least in the narrow sense.  The "problem" was in agn.c, where the dev version retains a line which multiples the radius at which photons are created by a small number r=r*(1+EPSILON) 
to make sure that the photon is created outside of the inner boundary.  Once this line was included in the domain2/agn.c the photons that were created were identical and the results of template_ionloop are identical in domain2 and dev.   

This leaves questions/actions about agn.c for @Higginbottom and @jhmatthews.  Nick has been making changes to agn.c which are now in agn.c, but it looks like some agn.c in domain2 was "cleaned up".  Someone needs to bring this two versions together, so that we can confidently merge domain2 into dev.  As an aside, we also have a somewhat serious formatting issue and that is that changes in indention philosophy, possible introduced by our editors, are making it difficult to compare versions (producing lots of apparent changes in git diffs that do not change the actual code).

**Comment by jhmatthews** [comment]
Hi Knox. I agree with your points. I think having a dfudge as a fixed fraction of cell size would be sensible. I also had noticed the indenting issues and had meant to flag it. It certainly makes doing some of the more complex merges more difficult. I'm pretty sure it's not caused by my editor as I see the same as github.

RE domain2 and dev. I believe I have been careful in periodically bringing domain2 up to date by doing a git pull upstream dev and manually making the changes where necessary. For example, there have been times where someone made a change in python.c in dev, but in domain2 the relevant piece of code has been moved to run.c, so I had to carefully check the change I wanted to make. So switching to domain2 should be fairly easy and I can continue to do this as long as we are still testing domain2 and dev separately.
