### ISSUE TITLE
Indenting

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#218]
Originally, when I coded python, I used "indent" to make sure that the code was easy to read.  We have not done that, and, each of us uses our own editor which may or may not enforce any kind of formatting.  At any, many of the routines are hard to read and the style is inconsistent.  I believe we should adopt a formatting standard and try to enforce it.  

There are two problems:

How do we get the current code to a common standard (and will that obscure the changes in the code that are substantive)

How do we maintain it.

For the first question, I there are git diffs that ignore white space changes.  Some suggestions on the web are to create aliases to ignore white spaces; it is not obvious that one can configure git to make this the default.  There also apparently are ways to turn off "blame" for particular updates.  At any rate, before we made a global indent change we would need to figure out how to do this.  We should do it on all branches, forks, etc.  at the same time.

For the second question, either we have to make sure we run indent in a particular way before making a commit, or apparently there is something called git "hooks", that will run something, in this case indent on all of the files that have changed.  If I have red the documentation correctly, this is something that one actually has to install in each local git repository.  There may also be things that can be done when something is pushed, but I have not figured that out.

Finally, as to format, I would suggest we settle on using gnu indent  (not the indent on a mac which is the Berkeley version), and that we use the -gnu style, perhaps allowing somewhat longer lines than in that standard, so that long equations don't get quite so broken up. 

This is one of the problems I would like us to address when I come to Southampton, so please everyone weigh in on this.

**Comment by jhmatthews** [comment]
I agree that this is a problem. I'm not particularly fussed on the exact style used as long as it's consistent. I think @smangham had some suggestions for specific flags to use to make "indented" code look a little better, along the lines of what Knox has mentioned about line lengths. 

I think the best thing to do would be to simply run it in dev once any changes are merged, make a release just before that as a stake in the ground, and then those indenting changes can be made in one commit and easily pulled to any other branches. That would allow comparison with old code to still be fairly easily facilitated.

**Comment by smangham** [comment]
I had some issues with the default GNU formatting before but it looks like -nut to switch tabs for spacing has fixed most of them. Personally I don't like the

```
if(condition)
  {
    thing
  }
```

notation and prefer the brackets being on the same line as the if conditions, but I can certainly deal with them. It looks like indent interacts a little oddly with doxygen-style comments but they can be reformatted to avoid bugs.

**Comment by kslong** [comment]
So, you prefer the old KR style then I take it.  I'm OK with that.  

I confess I did not know what doxygen was, until I looked it up.  I can see there might be a bad interaction with comment blocks.  Are you suggesting we ought to be thinking of using doxegen.  Have you actually tried it.

**Comment by smangham** [comment]
Ah, I misspoke there- I meant brackets aligned to the if statements, as in -bli0 for 0 indent. I've been using `gnuindent -gnu -l140 -bli0 -nut FILE` as 140 seems to be the most common longest line length. RE: automatic indenting, discussion around git hooks seems to suggest that code-modifying pre-commit code is not recommended, I think James suggestion is a good one.

I am currently using Doxygen in the files I've added- I think we discussed it a little while ago. The issue with indent/Doxygen is that Doxygen requires its comments begin with a `/**`, and so recommends the following structure for boxed comments:

```
/***********//**
 * Things
 * Things
**************/
```

In order to avoid indent being confused about where the comment block begins, you instead have to format boxed comments as:

```
/**************/
/** Things
 * Things
***************/
```

Which is probably better in any case it it requires slightly less modification of our standard comment boxes.

Getting off-topic, Doxygen is particularly useful as whilst being as human-readable as our existing descriptions Doxygen comment blocks can contain hyperlinks to other functions, which makes determining the program flow easier, e.g. this function:

```
/**********************************************************/
/** @name   line_paths_generate_photon
 * @brief   Generates path for a macro-atom line photon
 *
 * @param [in] wind         Wind cell to spawn in
 * @param [in,out] pp       Photon to set path of
 * @patam [in] nres         Matom line to generate for
 * @return                  0
 *
 * If the line is being tracked, pick a random path from its 
 * path histogram. If not, default to the regular path 
 * histogram. 
 *
 * @see r_draw_from_path_histogram()
 * @see simple_paths_gen_phot()
 * @see wind_paths_gen_phot()
 *
 * @notes
 * 26/2/15  -   Written by SWM
 * 24/7/15  -   Removed frequency
***********************************************************/
```

**Comment by kslong** [comment]
We have not dealt with this issue, as discussed in #220
