### ISSUE TITLE
GSL compilation issues on Iridis

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#235]
The 'out of the box' python distribution failed to compile on Iridis for NSH. 
It was failing at the stage of trying to compile our gsl distribution.
Investigation revealed that the environment variable $CC is set to icc, and $CPP to icc -P, i.e using intel compilers. These get used to compile gsl and for some reason they don't work. 

The way to get around this is to force the gsl Makefile to use gcc and cpp by calling the gsl configure script with the additional flags CC=gcc CPP=cpp

This can be added into the python Makefile.in file  

INSTALL_GSL = cd $(GSL); ./configure --disable-shared --prefix=$(GSL) CC=gcc CPP=cpp; make; make check 2>&1; make install; make clean; 

I think that as long as a user has cpp and gcc on their system, this will work.
Comments?

**Comment by Higginbottom** [comment]
OK, so this isn't fixed.
I tried to install a fresh installation on iridis, and it doesn't work for the same reasons - gsl won't compile.
On investigation, it works fine if the module intel/15.0 is not loaded. This is required to load the numpy module for python which is of course required.
There must be an environment setting to fix this - or just remove this module before compiling.
I'm just putting this here for reference...

**Comment by Higginbottom** [comment]
So, I'm not sure why my previous fix worked at all, ./configure doest use CC or CPP as inputs, so that was nonsense.

The way to do it (or at least *a* way) is to put

export CC=gcc
export CPP=cpp

into the Makefile.in so configure puts it into the Makefile for the python distribution. Of course one could also ask the user to to this as environment variables, because we need gcc to compile gsl.

I'm reopening this, because I'd really like the team to comment as to what is the right way of doing it. 

Cheers!

**Comment by kslong** [comment]
I am afraid I have never understood configure scripts, and I don't seem to be able to find any simple tutorials on them.  It surprises me one would have an export command though.  It seems surprising that a .configure script for something like gsl would be needed since it installs on so many machines.  The only thing I can think of is that one of these variables is somehow already defined to something it should not be.  I once had problems for example with something getting in the way of something needed for compiling fortran programs.  We should talk about this at our next telecon.
