### ISSUE TITLE
Segfault in YSO model

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#250]
This is an issue being reported by Kelly Milliner, an undergrad student of Lee Hartmann

**Environment**
Mac, no mpicc available so running serial.

```
gcc (MacPorts gcc49 4.9.3_0) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
Python Version 81b_dev
Built from git commit hash f6111a26e393788db2a9ca4e2224c733a7341f5a
```

**Input file:** yso_a.pf from this repository: https://github.com/jhmatthews/fu_ori
**Output with segfault:** [output.txt](https://github.com/agnwinds/python/files/876463/output.txt)

If anyone is able to run with these exact settings or has any ideas I'd appreciate it - I can't reproduce the error, which I've tested with the below compilers I have available to me, and it's holding up Kelly's undergrad project a lot.

@smangham @Higginbottom @kslong 

Tested with [all using the above commit of python]:
* On mac with Apple LLVM version 7.3.0 (clang-703.0.31)
* On mac with gcc-mp-5 (MacPorts gcc5 5.4.0_1) 5.4.0
* On linux with gcc-5.4.0
* On linux with gcc-4.9.3

**Comment by kslong** [comment]
This does NOT fail for me on my MAC  either using

gcc version 5.4.0 (GCC)

As it exists on Fink

Or

Apple LLVM version 7.3.0 (clang-703.0.31)

Knox

**Comment by Higginbottom** [comment]
I can’t get the fault any more - 
now compiling using my version of GCC on the mac which is 

Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by jhmatthews** [comment]
so you can't reproduce it at all anymore? This is really weird. I haven't been able to reproduce it with any of the compilers I've tried (now over 10). If anyone can help it'd be good because we aren't making the best first impression at the moment. Nick, do you know if you get it when you do the same steps with dev latest?

**Comment by kslong** [comment]
Have we checked Nick’s suggestion, namely that the student pull the current version, do make clean, recompile, and try it again. We definitely need to be able to reproduce the error to fix it, but I’d prefer not to have to figure out how to install a macports version of gcc.  Knox

**Comment by jhmatthews** [comment]
I've asked them to do that yes. Will report back.

**Comment by Higginbottom** [comment]
I’m testing the latest version of dev as we speak. 
Compiled MPI it runs OK
Compiled serial it runs OK.

With my compilers….

N

**Comment by Higginbottom** [comment]
Wait,
Just went back to f6111a26e393788db2a9ca4e2224c733a7341f5a
Now seg fautling…..

No idea what I did really….

Baffling…..

**Comment by Higginbottom** [comment]
OK,
So I get the crash if I don’t run in -f mode

i.e. py81b_dev yso_a

the crash occurs because even in normal mode, the temperatures don’t change at all (is this correct???) and so when wind_updates2d.c executes the check

if ((fabs (t_e_old - plasmamain[n].t_e)) > fabs (dt_e))
    {
      dt_e = plasmamain[n].t_e - t_e_old;
      nmax_e = n;
    }

the if statement is never true and nmax_e remains at its initialised value of -1

This means that when it tries to do 

wind_n_to_ij (wmain[nmax_e].ndom, nmax_e, &i, &j);
    Log ("!!wind_update: Max change in t_e %6.0f at cell %4d (%d,%d)\n", dt_e, nmax_e, i, j);
    Log ("!!wind_update: Ave change in t_e %6.0f from %6.0f to %6.0f\n", (t_e_ave - t_e_ave_old), t_e_ave_old, t_e_ave);


if returns a seg fault because there is no cell -1.


So, a simple test protecting the wind_n_to_ij would suffice here - if nmax_e = -1, this means no cells have changed, so the code can report this.

I have no understanding of the yso run, so perhaps I can leave that with someone else to tell me why the temperatures never change, even in non -f mode…..

I’ll do a few more tests, then push the changes to the dev branch, along with my line changes.

N

**Comment by Higginbottom** [comment]
So, 
My solution to the student is:

a) If they want to carry on using the commit they have, then make sure they use the -f option

b) Otherwise, update to the latest version py81c. If they don’t update the atomic data to atomic80 (which includes the collision strength data) then all should work more or less as before, other than dielectronic recombination cooling and some changes to compton cooling.


In other news - of course the reason t_e isn’t changing is because this is a fixed ion mode - so the code that changes t_e is never called. Is this a desired behaviour???
I’ve 

Cheers!!!

N

**Comment by kslong** [comment]
Good job, Nick

Sent from my iPhone

On Mar 30, 2017, at 3:27 AM, Higginbottom <notifications@github.com<mailto:notifications@github.com>> wrote:

So,
My solution to the student is:

a) If they want to carry on using the commit they have, then make sure they use the -f option

b) Otherwise, update to the latest version py81c. If they don’t update the atomic data to atomic80 (which includes the collision strength data) then all should work more or less as before, other than dielectronic recombination cooling and some changes to compton cooling.


In other news - of course the reason t_e isn’t changing is because this is a fixed ion mode - so the code that changes t_e is never called. Is this a desired behaviour???
I’ve

Cheers!!!

N

**Comment by jhmatthews** [comment]
Great spot. I will get in touch. Thanks for looking into this Nick.
