### ISSUE TITLE
Tweak diagnostic mode

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#253]
I've recently fixed the diagnostic mode ( #252 ) -- but we'd like to test it and also improve it slightly to make it easier to read (e.g. add a special character). This issue is just so we don't forget!

Any discussion and testing of it to go here!

**Comment by Higginbottom** [comment]
Trying to run in diagnostics mode to output wind save files for each run. It seems to require all of the diagnostics options to be in the .pf file? 

Here is the error:

freqs_init: 13078.66 (3.16e+18)    49634.40 (1.20e+19)  
freqs_init: 49634.40 (1.20e+19)    50000.00 (1.21e+19)  
@Extra.diagnostics(0=no,1=yes) 	  1
get_extra_diagnostics: Getting extra diagnostics as requested...
Switching to interactive mode for this variable
@save_cell_statistics (0) :


here is the end of the .pf file

live.or.die(0).or.extract(anything_else)                    1
spec.type(flambda(1),fnu(2),basic(other)                    1
reverb.type 0
Photon.sampling.approach           8
Num.of.frequency.bands(5) 10
Lowest_energy_to_be_considered(eV) 1.03333
Highest_energy_to_be_considered(eV) 50000
@Use.standard.care.factors(1=yes) (1)
@Extra.diagnostics(0=no,1=yes)   1
@keep_ioncycle_windsaves()   1


Is this the expected behaviour? I can stick all the options in, but it seems odd..

Nick

**Comment by jhmatthews** [comment]
That's the expected behaviour, yes.

**Comment by Higginbottom** [comment]
Oh, OK. Why does it loop and count the number of options then - I thought the if, else if loop was constructed in drag.c to allow you to put all or only some options in. OK.

also, its not turning on wind_saves even with all the options in, and set to zero. 

end of .pf file.

Lowest_energy_to_be_considered(eV) 1.03333
Highest_energy_to_be_considered(eV) 50000 
@Use.standard.care.factors(1=yes) (1)
@Extra.diagnostics(0=no,1=yes)             1
@save_cell_statistics                             0
@ispymode                                         0
@keep_ioncycle_windsaves                   1
@save_extract_photons                            0
@print_windrad_summary                            0
@print_dvds_info                                  0
@track_resonant_scatters                          0

Maybe its because I'm restarting, and you can't turn on these things mid-run..... No time to look into this. Will have to be after holiday....

**Comment by jhmatthews** [comment]
sorry - ridiculous mistake in diag.c from me where the modes were set incorrectly. Fixed that. 

There shouldn't be a loop to count the number of options though?

**Comment by jhmatthews** [comment]
I believe this now works as expected. Closing.
