### ISSUE TITLE
Mismatch between _cool, and _lum plasma fields 

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#284]
A bit of an old chestnut this one, but re-surfaced due to the new split in rr_cool and rr_lum. 
There are a few different fields in the plasma structure that deal with cooling and luminosity and these are a little confused. More confusing is when they are updated prior to being written out into the wind_save file. 
This problem specifically crops up with the way in which there are now two radiative recombination fields, lum_rr (the radiative recombination luminosity) and cool_rr (the RR cooling). The former is updated at the start of a cycle, when photons are made (lum_lines, lum_ff and lum_tot are also filled at this time) and ends up containing the band limited luminosity for the last band generated. This is frequently a rather high frequency band and there is no luminosity, so probably all four fields end up containing a zero.
The photons are flown, and then the effect of those photons is computed via one shot. At this point, lum_lines, lum_ff, and *cool*_rr and *cool*_tot are populated during the search for the new temperature. NOTE - these fields end up populated with the rates at the last temperature used in the *search* for t_e, not necessarily the actual new temperature.

After this, the processes all exchange information, and then the _ioniz fields are populated.

Then wind_cooling and wind_luminosity are called to update the cooling and luminosities to the current t_e, and  then the wind is reported and exported.

So, why is this confusing?

1: The _ioniz fields don't contain the same information as the fields they are supposed to be copies of if the temperature has changed

This caused me a lot of headaches, since I was exporting a .complete file from py_wind, then picking a cell to examine more closely using the 'e' option in py_wind. The former uses the 'normal' fields, e.g.. lum_rr, whilst the latter uses the _ioniz fields - e.g. lum_rr_ioniz. The fact that these were different was very confusing!!

Solution?

Call wind_cooling in one_shot *after* the new t_e has been calculated to ensure that right from the outset the _cool fields have the cooling rates that match the actual adopted t_e rather than a random t_e in the search. This would also mean that the convergence criteria is computed for the new t_e...

BUT - we need to be more careful about the _lum fields

we should decide if we want the _lum fields to represent the luminosity of the wind in its new state, or in the state where the photons were generated. I think we probably want it to represent its current state - otherwise it will get very confusing. So this is fine, but we need to move the call to wind_luminosity in wind_update to before the point at which everything gets copied into the _ioniz fields.

its also a little confusing that we use lum_lines for cooling and luminosity - its kinda fine since they will always contain the same value though.

**Comment by kslong** [comment]
This is sufficiently complicated @Higginbottom that my suggestion is that at your convenience you actually write up a more complete explanation of what is going on here, and circulate it.  Then we should have a telecon once we have all digested that.  I agree with your basic premise though. We need to have a very clear understanding of what the heating cooling and luminosity numbers mean precisely.

**Comment by jhmatthews** [comment]
Yeah, this is tricky (but at least only diagnostic) and was raised before here: https://github.com/agnwinds/python/issues/36

It's always a bit debatable what you really want here, because it's impossible to have everything be "self-consistent" (i.e. cooling heating and temperatures are calculated using the same physical conditions) until the code is converged. I generally agree with Nick's points. But I think the main thing is to be as explicit and consistent as possible. 

Things we should definitely change IMO: 
* "Call wind_cooling in one_shot after the new te has been calculated to ensure that right from the outset the cool fields have the cooling rates that match the actual adopted te rather than a random t_e in the search. This would also mean that the convergence criteria is computed for the new te..." -- this should definitely be done. Note this is why the DR cooling is reported weirdly at the moment.  
* "e.g.. lum_rr, whilst the latter uses the _ioniz fields - e.g. lum_rr_ioniz. The fact that these were different was very confusing!!" -- I believe the ioniz quantity should always be used in py_wind because otherwise it can get changed in spectral cycles to be a band limited quantity.

**Comment by jhmatthews** [comment]
I believe this also got fixed by Nick in 2017, so I'm closing. Please reopen if this is not the case.
