### ISSUE TITLE
Fixed Ionization Fractions

### ISSUE THREAD

**Issue by lazygun37** [sirocco-rt/sirocco#291]
In running some YSO models for Lee Hartmann, I realized that the way in which we handle models with fixed ionization fractions isn't very clear. For example, with fixed ionization fractions, we still currently run ionization cycles, which is odd. Also, it's not at all obvious how the thermal state of the wind is determined in this case. Does the temperature just stay constant? A related question is, typically, the file that's read in to fix ion fractions only lists those elements we care about. So what is assumed about the other elements? This wouldn't matter if we didn't do ionization cycles and fixed temperatures, but, as it stands, it's not obvious what is happening.

There is a "real" issue here as well -- if you fix CIV, say, and "don't care" about the H (and other element) ionization, then you obviously can't try to calculate things like H (and other) ionization edges, and not even about electron scattering (since you don't know what the electron density is).

My suggestion would be to change this mode so that it only initializes the wind to a fixed temperature and then only runs spectral cycles that ignore all processes except those associated with the ionic species whose ionization state we've fixed.

**Comment by jhmatthews** [comment]
An additional issue to bear in mind here is that, for unknown reasons, the current number of fixed ions is limited to 10, and probably shouldn't be.

**Comment by kslong** [comment]
I am not surprised about this.  The history of the fixed ionization model was that Christian's PhD model was just concerned with CIV and so we were trying to make comparisons between python and his program.  If a wind is optically thin, and if your are only interested in CIV, this may be OK, but as @lazygun37  points out, then what's the point of all the ionization cycles.  

Christian suggests changing Python for this case so that (in my breakdown of requirements) (a) it runs at fixed temperature, (b) so that only spectral models are run and (c) that process not involving the ion's that are specified are somehow turned off.  Items a and b can be already be accomplished with the right values in the .pf files.  Item (c) effectively means you have to disregard all elements not mentioned as fixed in the file for ions.  A simple way to do this, is to comment all the other elements out in the atomic data files, and in many ways that is the simplest thing to do, because if you do that then all of the data structures that appear for the other elements are not ever created.  In the short term, Christian, if that is the mode in which you wish to operate with Lee, I suggest this is what you do.

Longer term, I'm not personally sure that we want to limit the way python works in this case.  I can easily imagine we would want to fix some "not very abundant" element, "not very abundant" in the sense that it does not govern the heating and cooling of the plasma, and let the abundant elements "evolve".  

My suggestion is that before we do anything, we figure out the use cases for this mode in some detail.  We also ought to document what this mode does so that we will remember the next time this comes up.  

The limit on the number of ions should be trivial to fix.  We should just make sure when we do this that it is in some #define variable so that it can be changed whenever needed.  Hopefully, that's the way it is now, but this mode was in the very early releases of Python and has not been used much since.

**Comment by kslong** [comment]
This has come up in the context of the FU Ori models.  We should decide what we want to do.

**Comment by Higginbottom** [comment]
Adding to this - I would like to be able to read in the ionization state of a previous run for the rad-hydro model. I would then want the code to iterate that ionization state. ISTM that this work should dovetail in with the work discussed here to be a part of an overall framework for reading in/fixing ionization states...

**Comment by Higginbottom** [comment]
This mode would also be of use in Christians idea of setting up a first guess of a model - to speed up convergence.

**Comment by kslong** [comment]
What Sedona does, or can do, is create input files where the abundances are set for each ion in each cell.  Sedona also has a well defined process for turning certain processes on and off.  Sedona also uses and input process that differs from Python in the sense that it reads it has a default file, which inputs from the user file can over ride.  If we really want to provide a better fixed concentrations approach.  We should really consider what we want and why.  For now I am I am going to close this issue, but I have added closed with caveat.
