### ISSUE TITLE
A systematic check of functions that call cdf_gen_from_func is needed

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#302]
The functionality of cdf_gen_from_func (which used to be pdf_gen_from_func) has changed.  Previously, this function generated a fine array of x values, calculated the pdf at each, and in constructing the final cdf  sub-sampled the x-values to produce a cdf that was more or less uniformly spaced in probability.   To get around the fact that one sometimes wanted points at the ends of the distribution, we used jumps, which forced certain values into the final cdf. The new version of the routine does not do this sub-sampling.  We simply use all 10,000 points.

The current version of the cdf_gen_from_function still incorporates jumps (and probably doe this properly.)    cdf_gen_from_func is called in a variety of places, most of the time with jumps set.

However it is unclear that anyone has checked the various routines to see whether the jumps that are there are needed and if they are the right values, given that we are storing 10,000 points now instead of 200.   
 
While it is probably not important to deal with this now, what would be helpful immediately  @Higginbottom is for you to comment on the calls of this routine you did think about when you were working on the general problem of cdfs here and in the code for those calls where you did think about it, e.g bb.c which I recall some discussion of.  That way we won't forget.

Note that cdf_gen_from_func is called from bb.c  anisowind.c brem.c random.c

**Comment by mandyhewitt** [comment]
Plan of action for this issue is to check calls to cdf_gen_from_func - see if it is now called from more (or less) functions than listed above (bb.c, anisowind.c, brem.c, random.c) and establish if all 10,000 points are used (vs 200 points as was previously used). Also look at our latest documentation to see if this is clearly evident from the visual function mapping we have implemented since this issue was raised. Subsequently working through the logic of the function to also understand cdf_gen. NB cdf_gen is interesting to study in regards to current frame work (sampling dipole)

**Comment by kslong** [comment]
It seems unlikely we will do this, unless an identified problem arises.
