### ISSUE TITLE
Setting a inner edge to accretion disk

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#306]
In my rad-hydro work I'm at a point where I want to create photons from a disk that is underneath the wind. At the moment, unless I'm missing something, python assumes that the disk extends to the surface of the central object. In order to have a nice radial distribution of photons from the central source, my 'agn' is very small so the disk extends all the way down to small radii. 
I tried to effectively truncate it by reading in a temperature profile that dropped to 10K inside the radius I was interested in, but this didn't work - perhaps a different bug? 
So, I'm interested in working out how to set an inner edge, seems very simple, just read in a new parameter - disk_radmin, and use this to define the disk rather than just using geo.rstar as this value. Clearly this is n upgrade of general use!
I'd also probably rename the parameter geo.diskrad to geo.disk_radmax to keep things understandable.
I'll try this in a branch and let you know how it goes.

**Comment by Higginbottom** [comment]
OK, this is much harder than I thought - mainly due to the way that ds to disk is written. Basically its always assumed that if a photon doesn't hit the star, but its inside the maximum disk radius, then it will hit the disk. Tricky coding particularly for a thick disk...

**Comment by kslong** [comment]
If this is the only time we plan to use this, then I would like to understand why the right course of action is not to fix the problem with reading in the temperature, rather than creating a new input variable.

If there is a general need for radmin, then we should understand the ramifications, and argue that where is it needed generally.  The one I can think of is that one actually wants photons to go through the inner edge of the disk,  but am doubtful that this matters for the X-ray binary simulation.

I will be upset if 6 months from now we have to do cleanup on this because we did not understand how radmin was going to be used in all situations, e.g in the standard model.

**Comment by kslong** [comment]
I believe we have decided to defer this for now.  Nick has found a work around to his problem, and will will need to work that through.  It might come back when we get serious about CVs.

**Comment by kslong** [comment]
Given that we are not planning on working on this enhancement for the foreseeable future.  I am closing this issue.  @Higginbottom, if you wish to work on it, you should reopen it.
