### ISSUE TITLE
Python reverts to default values when it reads in a misunderstood parameter value

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#315]
When I provide python with values that it doesn't understand (say, answer "20" to System_type or answer "aloadofrubbish" to "mstar", it defaults to the default value initially stored in, say, geo. 

To replicate this, type "py" and enter incorrect values, or say, strings as answers to float questions. Python adopts the default value in this case, but I'm not sure this is the expected, or desired, behaviour. Do we agree?

**Comment by mandyhewitt** [comment]
Hi James,

I’ve limited understanding of python but I would imagine that there are 2 main cases:

Interactive mode - should prompt for correct values and give error message 

Non-interactive - should either chose the default value so it can continue or it should halt based on some initial setting (e.g. debug mode?)

Is there a mixture of these 2 modes available?
Ie partially interactive?

Mandy

**Comment by jhmatthews** [comment]
Right, Mandy. There is a mixture of the two modes available - in that, if you miss out a parameter from the input file python will prompt the user for that variable - and so I believe a similar thing should happen here as you suggest should occur for interactive mode.

**Comment by kslong** [comment]
OK, I have confirmed this happens if this is entered from the command line, or from a file.  Furthermore the non-sensical entries are written to the output file.

It is also obvious what is happening.  The data are all initially read in as strings, and then there are sscanf statements to convert the string to an integer, double or whatever.  But there is no check on the sscanf statement to see that the conversion was successful.  This, as @jhmatthews  noted leaves the default in place.   See e.g line 946 of rdpar.c

It appears what needs to be done is to check the sscanf statement and if we have a nonsensical input set the status to REISSUE

**Comment by kslong** [comment]
I have mostly fixed this problem.  If you give it a non-sensical entry, you will be asked for a sensible one.  Until you provide a sensible answer, the question will reappear.  Note that sensible means something that can be converted to an integer or whatever, not something that the program can actually use. 

The part of the solution that is not ideal is that the output .pf file will contain the original non-sensical entry (as well) as the one that has the correct format.
