### ISSUE TITLE
Running a file with macro atoms in non-macro mode

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#316]
In the past, one was able to run a set atomic data files which contained macro atoms in a non-macro atom run.  Now it causes a segfault.    We want to maintain this capability, in part because we want to be able to compare macro atoms and non-macro atoms.   

This segfault was uncovered while working on the segfault described in #311   But that one is an error that occurs when you run a macro atom model with macro atoms and occurs much later.

The proximate reason for this segfault are these lines in wind_updates2d.c

1106     plasmamain[n].heat_auger = 0.0;     //1108 NSH Zero the auger heating for the cell
1107 
1108     if (nlevels_macro > 1)
1109       macromain[n].kpkt_rates_known = -1;

Since we are not in a macro atom mode, macromain has not been allocated.   This is easy to fix in principle 

geo.macro_simple is the variable that is supposed to control this.

So I added a qualifier 

if (nlevesl_macro >1 and geo.macro_simple == 0 

to this line, but that did not help.  So minimally geo.macro_simple is not being set properly. 

The underlying question though is whether there is more to restoring this capability than just getting geo.macro_simple set.

**Comment by kslong** [comment]
It's pretty simple to generate this problem, but here is a sample anyway.

[macro_off.pf.txt](https://github.com/agnwinds/python/files/1528928/macro_off.pf.txt)

**Comment by jhmatthews** [comment]
Right Knox. I've had a quick look at this and the code and have reminded myself of some things. I believe this is how the code works at the moment, or is at least designed to.

* line mode 3-5, macro-atom data set: not supported (segfaults).
* line modes 6 and 7, macro-atom data set: full macro-atom run, 6 or 7 changes scatter mode
* line modes 6 and 7, normal data set: treat everything as a simple-ion, 6 or 7 changes scatter mode
* line modes 8 and 9, macro-atom data set: treat everything as a simple-ion, 8 or 9 changes scatter mode.

I am not sure if options 3-5 with matom data have ever worked (which is the situation that segfaults), but clearly they should not segfault. I believe the variable geo.macro_simple is supposed to control if you treat **everything** as a simple ion or not. 

Note that there is a distinction between "simple ion" line transfer mode and "standard", because if you treat everything as a simple ion photon weights are still indivisible, and k-packets and so on are still used, and the various approximations about bound-free continua that we make for simple-ions apply.

So I think it really depends how much we want modes 3-5 to work with macro-atoms, and what we actually mean by that. I feel like it might require some tricky coding in get_atomicdata to get this to work, and I'm not sure if it's worth it as it doesn't give any new capabilities. So I would probably favour something that checks for the situation in which the code currently segfaults, and quits cleanly while clearly signalling to the user what they need to do.

As you say, this should be documented, which I am happy to do.

**Comment by jhmatthews** [comment]
I've started adding some documentation in the cookbook, mainly just describing the modes for the moment. Somewhere the general principles of "simple ions", macro-atoms, indivisible packets and so on need to be added.

**Comment by kslong** [comment]
James, modes 3-5 predate macro atoms, and I am quite sure that originally they did work properly with macro atom inputs during @ssim   YSO project.

**Comment by kslong** [comment]
I believe this is the same issue as #206

**Comment by jhmatthews** [comment]
It seems to me that the specific issue above can be solved by changing

```if (nlevels_macro > 1) ```
to
```if (geo.rt_mode == RT_MODE_MACRO)```

k-packet cooling rates should be calculated whenever one is in indivisible packet mode, even if no actual macro-atoms have been allocated. The reason the segfault was occurring was because macromain is only allocated if geo.rt_mode == RT_MODE_MACRO, but if one reads in macro-atom data then nlevels_macro is non-zero.

**Comment by kslong** [comment]
The particular change the James mentioned above was made at some point.  The routine now crashes here.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010002b4c7 py`wind_rad_init at wind_updates2d.c:1133
   1130     {
   1131       for (njump = 0; njump < config[i].n_bbu_jump; njump++)
   1132       {
-> 1133         macromain[n].jbar[config[i].bbu_indx_first + njump] = 0.0;      // mean intensity
   1134       }
   1135       for (njump = 0; njump < config[i].n_bfu_jump; njump++)
   1136       {
```

nlevels_macro is non zero here, but is failing on the first past through this loop.  It's a pretty good bet that macro main is not defined.  

The underlying question here whether we want macromain to be defined.  If our goal is to turn on macro atoms at somepoint it may be desirable to do that.

**Comment by kslong** [comment]
This is a version of the parameter file, updated so it will run in py83

[macro_off.pf.txt](https://github.com/agnwinds/python/files/2975673/macro_off.pf.txt)

**Comment by kslong** [comment]
@jhmatthews   There has been some question as to whether we should be/had been able to run a macro atom set of inputs as if it were a simple model.  I am interested in doing this again, in part because I think it might speed up the code if we spent a certain number of cycles using simple atoms, and a certain number in full macro atom mode.  At any rate, I ran across the following comments in python.h which I think proves my assertion that we used to be able to do this.

Note specifically the last bit

```
  int search_light_radiation;   /* 1605 - ksl - Added to implement 1d testing */
  int matom_radiation;          /* Added by SS Jun 2004: for use in macro atom computations of detailed spectra
                                   - 1 means use emissivities for BOTH macro atom levels and kpkts. 0 means don't
                                   (which is correct for the ionization cycles. */
  int ioniz_mode;               /* describes the type of ionization calculation which will
                                   be carried out.  The various ioniz_modes are defined by #defines IONMODE_MATRIX_BB
                                   etc.  See the documentation in this file for what these mean.*/
  int macro_ioniz_mode;         /* Added by SS Apr04 to control the use of macro atom populations and
                                   ionization fractions. If it is set to 1 then macro atom populations
                                   computed from estimators are used. If set to 0 then the macro atom
                                   populations are computed as for minor ions. By default it is set to
                                   0 initially and then set to 1 the first time that
                                   Monte Carlo estimators are normalised. */
  int ioniz_or_extract;         /* Set to 1 (true) during ionization cycles, set to 0 (false) during calculation of
                                   detailed spectrum.  Originally introduced by SS in July04 as he added
                                   macro atoms.  Name changed by ksl (57h) since this variable can be used more
                                   generally to speed up the extract portion of the calculation.
                                 */
  int macro_simple;             /* Added by SS May04 for diagnostics. As default this is set to 0. A full
                                   Macro Atom calculation is performed in that case. If it is set to 1 it means
                                   that although Macro Atom data has been read in, all lines/continua are treated
                                   using the simplified two-level approximation. Such a calculation should reproduce
                                   the same results as pre-Macro Atom versions of the code. */
```

**Comment by jhmatthews** [comment]
@kslong  - just to clarify here. I do not believe that one could ever run macro-atom data with standard line transfer mode, or at least I don't know how. One can however use macro-atom data and treat all things as simple ions. That is what the above variables are for. They are accessed through the old line transfer modes 8 and 9, but I note that with the new rdchoice commands it's not possible to access these. See lines in setup_line_transfer.c. 

I would suggest:
* we allow these modes to be accessible in some capacity
* we add an error message if you provide matom data to "standard mode" which, note, is not the same as "simple ion mode", since the latter will enforce indivisible packets.

The philosophy being that the user switch controls the treatment of line transfer (indivisible or not?) and the data (LevMacro etc.) controls whether things are macro- or simple-.

**Comment by kslong** [comment]
James, I expect we are in violent agreement.  I am not quite sure what the distinction between running macro atom data with standard line transfer mode and using macro-atom data and treating things as a simple ions.  In any event, what I meant was being able to read in a macro atom data file, and use portions of the data so that one could for one, several, or all cycles use that data and run a model in simple mode.

To me the basic question is how exactly you carry this out.  There are three possibilities:


  *   Rigid.  If you specify a simple radiative transfer mode, you issue an error if you start reading in a macro atom file (your option 2)
  *   Semi-Rigid  - Provide a mode that says I am going to read in a macro atom file but I want to only use the parts of this that I need to do simple radiative transfer.  This requires providing additional radiative transfer modes (to enable 8 and 9).   Pro – It does provide all the options,  Con – It is not very user friendly.
  *   Flexible – If I read in a macro atom file, but specify a simple radiative transfer, I automatically only use the parts of the data that pertains to this.  Pro-provides all the options, user friendly, might permit us to reduce the number of data files

**Comment by kslong** [comment]
Minimally for release we need to warn the user if she has tried to do this.  Ideally we should sort this out.
