### ISSUE TITLE
Parameter naming convention

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#318]
In late 2017, ksl conducted a small survey regarding naming conventions for our input parameters.  There was a general consensus that parameters should have an initial word, e.g disk to describe what general topic was, separated by a period from one or more words separated by _ describing the variable, e. g.

disk.mdot_in_wind

There was a split opinion whether the parameters should have the first word capitalized, e.g

Disk.mdot_in_wind

or everything lower case.

A number of people suggested replacing the case statements where one responds with a number to a system where one responds with a string, but this is a large step and should be deferred until later

Now is a good time to try to deal with standardizing the parameter names as we are also currently trying to provide help.  Note that one thing which may help is to implement a capability to make the inputs case insensitive, so that we do not have to use synonyms to make changes.  In principle, a clever person might deal with standardizing where '.' and '_' should be as well.

**Comment by kslong** [comment]
This is a code fragment that will convert a string to the desired format.  It assumes we want everything to be lower case.  It could be inserted somewhere into rdpar to provide backward compatibility, assuming that all of the rdpar statements themselves were fixed, or more dangerously, applied in some way to the modify the inline statements themselves.

[foo.c.zip](https://github.com/agnwinds/python/files/1628465/foo.c.zip)

**Comment by kslong** [comment]
Note, ultimately I decided that an automatic approach was too dangerous so I made changes for the stellar winds variables by hand, using the synononyms.c to preserve backward compatibility.  For reference the steps that are needed are

- Change the keyword name for the rdpar to the current standard in whatever routine it appears, e.g. stellar_winds.c
- Modify add the old name and the new name to the appropriate arrays in synonyms.c
- Increase the variable that gives the number of synonmyms in synonyms.c
- use git mv to rename the yaml file
- edit the yaml file to reflect the new name

**Comment by kslong** [comment]
I have started making changes.  Note that I have used my "seniority" to choose that our standard will be to capitalize the first letter of a variable and to allow for variables where we want an underscore in the first word,

eg.  Stellar_wind.v_infinity

So the standard is:

- Capitalize the first letter with everything (except possibly a well known abbreviaition, e.g SV) lower case
- Use a period to separate the "subsystem", e.g a disk from the detailed variable. Disk.mdot

**Comment by kslong** [comment]
This is documented on https://github.com/agnwinds/python/wiki/Coding-Standards.  @mandyhewitt  please review this documentation and add comments on the yaml files.  Once you are happy please close this issue.

**Comment by kslong** [comment]
@jhmatthews   On https://github.com/agnwinds/python/wiki/Coding-Standards  we have documentation about coding standards, but what's said there about beautifying is clearly out of date.  I cannot find where we said what our indenting standard was.  I believe it was vanilla gnu indent.  Is that correct?  

@mandyhewitt   what's said about yaml is probably OK.  Once, we've properly documented, what indent to use, I think this can be closed.

**Comment by smangham** [comment]
The [old Makefile ](https://github.com/agnwinds/python/blob/3d02301822606b71fe437623a2fb4c7fa32999d1/source/Makefile)has this as the indent string:
`INDENT_CMD = $(INDENT_PATH) -gnu -l140 -bli0 -nut *.c *.h`

Default gnu indent has a weird half-indent for braces as:
```
if (blah)
  {
    things;
  }
things;
```
`-bli0` is brace line indent 0 so you get:
```
if (blah)
{
    things;
}
```
Instead, which IMO is more readable.

**Comment by saultyevil** [comment]
The Makefile hints at that GNU Indent is used for the indentation (lines 89-111). We use the command,

    indent -gnu -l140 -bli0 -nut *.c *.h

A quick Google shows that as of Indent 1.2 -gnu is no longer needed (but won't break it if still included) and -bli0 corresponds to brace formatting. I'm not too sure what -l140 or -nut are though. My best guess for -l is maximum line length.

**Comment by kslong** [comment]
Thanks.  This is all related to the problem we were discussing Friday, where we seemed to be having trouble merging (producing too many diffs).  Maybe the problem (and I may be the culprit) is that we are not using a make indent command, but indent on the command line.

**Comment by saultyevil** [comment]
Building on Knox's last post and coding standard...  I've been playing around with the indent command in the Makefile. Using indent ends up modifying around 13k lines, so it looks like it'll be messy/difficult to merge into dev. A lot of the modifications being made seem to relate to whitespace been added around comments or brackets and changes to indentation style.

So I guess there are a few questions.

1) Do we care enough about how the code looks right now? How often are we running into issues with difficulty merging because of indentation or style changes? Currently, the code looks fine on GitHub, but, at least on the editors I've tried, the indentation/style is all over the place making some parts difficult to read.

2) Do we want to change the style arguments for indent? Currently the indent command uses mostly GNU style with a few changes. The indent command uses `-gnu -l140 -bli0 -nut` which uses the indentation style (different to the GNU standard),

```
if (things)
{
  things;
}
```

which I think is a bit nicer to look at than the GNU standard. For anyone interested, the GNU standard formatting can be found [here](https://www.gnu.org/prep/standards/standards.html#Formatting).

3) If running this makes a lot of modifications, would we want to run indent per file as we edit each file? I can see this being easier to merge, but would take longer for all of Python to be updated. Or would we want to do something like run indent on dev and then update any branches/forks? I imagine this would be a lot of work to do though.

**Comment by kslong** [comment]
Thanks for doing all this work, Edwin. Clearly, this is something we need to talk about with everyone present.  A huge number of changes makes it almost impossible to got back in time to see when something changed.

One question would be good to resolve.  I know that one of the options locally, is to ignore white spaces in a git diff.  It’s possible this can be done when comparing on github as well.  I see some stuff on google about this, but have not figured out what one has to do.

Knox

**Comment by kslong** [comment]
I have opened a new issue #430 to discuss the indenting problem.   As far as I am concerned, the rest of the issue is closed.
