### ISSUE TITLE
py_wind inputs

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#324]
Python and py_wind both use rdpar for inputs.  It's not obvious which are which.  This would/will be confusing for the documentation if we were to add these to the yaml files.   Currently, Sam seem to have recognized this is a problem, and has prevented his scripts from looking at these files, so this is currently just a potential problem.

However a number of the py_wind input lines are quite non-standard:

rdint ("dvds_ave (0) dvdx (1) dvdy (2) dvdz (3) component LoS (4):", &ichoice);
rdint ("Save ions as densities (0) or fractions? (1)", &frac_choice);

We need a plan to address this.  Suggestions would be appreciated.

**Comment by smangham** [comment]
This is still an open issue even though we've ditched yaml files.
Switching to choices rather than `rdint`s will solve some of the problem. 
Realistically, though, we do still probably need to document all the choices for `py_wind` which will be a bit of a faff. Equally, switching the main options from `rdchar` will solve our problem with using increasingly unrelated characters for options.

**Comment by kslong** [comment]
I am closing this as  "zombie" issue, because we proably never intend to address it.  Improvments to windsave2table have higher priority
