### ISSUE TITLE
.out.pf file does not seem to end up with correct responses

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#325]
I'm trying hard to get all the correct updated keywords into my parameter files, but I'm getting lots of warning messages like:

Matched keyword Central_object.mass(msol) in .pf file to mstar in current python version
Central_object.mass(msol)	  7.000000e+00

when I run with 

[input.pf.txt](https://github.com/agnwinds/python/files/1676691/input.pf.txt)
[hdf000638nsh_dw44.zeu.txt](https://github.com/agnwinds/python/files/1676692/hdf000638nsh_dw44.zeu.txt)

This confused me, because I thought Central_object.mass was the new keyword. But OK, if we have gone back to mstar, then I thought that the file input.out.pf would have the correct keywords. Well this one still has  Central_object.mass in it....

[input.out.pf.txt](https://github.com/agnwinds/python/files/1676701/input.out.pf.txt)

This is annoying, because you end up with a slew of these messages in the output file, with is a mess when you are running with 256 processors.

**Comment by kslong** [comment]
We have not gone back to Mstar. I am not sure what is wrong. What branch etc are you on.

Sent from my iPad

On Jan 30, 2018, at 2:32 AM, Higginbottom <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm trying hard to get all the correct updated keywords into my parameter files, but I'm getting lots of warning messages like:

Matched keyword Central_object.mass(msol) in .pf file to mstar in current python version
Central_object.mass(msol) 7.000000e+00

when I run with

input.pf.txt<https://github.com/agnwinds/python/files/1676691/input.pf.txt>
hdf000638nsh_dw44.zeu.txt<https://github.com/agnwinds/python/files/1676692/hdf000638nsh_dw44.zeu.txt>

This confused me, because I thought Central_object.mass was the new keyword. But OK, if we have gone back to mstar, then I thought that the file input.out.pf would have the correct keywords. Well this one still has Central_object.mass in it....

input.out.pf.txt<https://github.com/agnwinds/python/files/1676701/input.out.pf.txt>

This is annoying, because you end up with a slew of these messages in the output file, with is a mess when you are running with 256 processors.

**Comment by jhmatthews** [comment]
I think all that has happened here is the print statement is slightly wrong and has the variables printed the wrong way around, and also should only print for the 0th thread. 

The original file has mstar, the .out.pf file has Central_object.mass, which I believe is the desired behaviour.

**Comment by jhmatthews** [comment]
Having said that, it does look to me like there is another mistake in check_synonyms() and I'm not sure I understand the description either. I would have thought the loop at line 134 in synonyms.c should loop and compare to "old_names", but it instead compares to "new_names"

```C
  for (n = 0; n < nunber_of_names; n++)
    {
      if (strncmp (new_names[n], firstword, wordlength) == 0)
	{
	  printf
	    ("Matched keyword %s in .pf file to %s in current python version\n",
	     new_question, old_names[n]);
	  strcpy (old_question, old_names[n]);
	  return (1);
	}

    }
```

Changing the printf to log should also help with outputs. @kslong can you clarify?

**Comment by Higginbottom** [comment]
Just back in the office after seminar. I'm using the restart branch, commit bc06fba20b8d64e2e3856d238ff1bec4899396be

**Comment by kslong** [comment]
I have changed the print statement to Log to address the issue with regard to getting lots of print out in mulitprocessor mode.

The logic of the for loop is correct.  firstword is the bare parameter name for parameter as contained in the program.  It has to be matched to something in new_names.  The old name is returned for further processing.    I have added comments to this.

@Higginbottom should be using the dev branch, not the restart branch.  The restart branch was only to address the restart problem.  The changes that were made to address the restart problem have been merged into dev.
