### ISSUE TITLE
excited state populations + metastable levels

### ISSUE THREAD

**Issue by ssim** [sirocco-rt/sirocco#35]
Currently we don't identify metastable levels and so use "dilute" populations for all exciting states. That may underestimate the populations of low lying levels (e.g. cases where the ground configuration is split and the populations are more likely to be close to Boltzmann equilibrium). 

We could instead (as in Tardis) flag levels as meta stable or not (based on whether they have downwards transitions in the line list) and use that flag to determine when to just use Boltzmann populations (LTE) or the "dilute" approach.

**Comment by jhmatthews** [comment]
Reopening this issue as it's worth thinking about. We've discussed modelling density-sensitive lines, which generally involve a ratio of lines involving metastable levels. 

I'd also like to be able to model CIII] 1909A for my quasar stuff. I don't know if the upper level of this line counts as a metastable level (it's an electric dipole transition 2s2p 3P0 -> 2s2 1S0 that violates the spin selection rule, but the radiative lifetime is significantly longer than that of the 2s2p 1P0 state). 

The reason why I'm mentioning it here is the general arguments about how appropriate our treatment of levels are relevant to all of a) density sensitive levels, b) getting level pops right in order to get bound-free opacities right and c) modelling CIII] 1909 and intercombination lines correctly. Nick's work on improving the collision strengths should help a fair bit as one will at least be able to get the collisional rates closer to correct.

**Comment by kslong** [comment]
I would also like us to give this some priority, as CIII 1909 is strong in CVs.

**Comment by jhmatthews** [comment]
CIII 1909 addition with two-level treatment now described here: https://sites.google.com/site/agnwinds/bugfixes-and-tests/ciii-and-updated-collision-strengths-impact-on-16-model

Note that the general question about level populations remains.

**Comment by kslong** [comment]
This is a issue with the atomic data files and should be revisited as part a general effort, but no short term activity is planned and so I am labeling it a zombie issue and closing it.
