### ISSUE TITLE
Nasty disk spectrum and failures when making XRB scale disk

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#393]
I've been trying to understand how to make SEDs similar to those described in Chris Dones recent paper on XRBs - with an aim to making disk winds for different 'stages' of a cycle. Trying to make disk radiation with a disk has thrown up some fairly horrible disk spectra, and indeed hang ups in photon generation. 
This .pf file
[input.pf.txt](https://github.com/agnwinds/python/files/2175027/input.pf.txt)

makes this rather nasty 'input' spectrum

![input_created_vs_emitted](https://user-images.githubusercontent.com/3329213/42437693-c3a9fae8-8355-11e8-9f64-55b450f67c77.png)

if you set the disk outer edge to 1e11 cm then the code just hangs at the photon gen stage - not  sure what its doing...

ill most likely end up using a pl + brem to do this work, not sure if that combo is possible tho, but I thought I'd log this issue. Im assuming it is happening because the disk is so huge in terms of radial range, I'll keep looking for an hour or two.

**Comment by Higginbottom** [comment]
Ok, so the reason it was 'hanging' when I cropped the disk was excessive time in qromb trying to integrate the BB spectrum over the very wide frequency range I had set up originally. Don't quite know why, but not the reason for the horrible spikes in the disk spectrum.

**Comment by Higginbottom** [comment]
![input_band_created_vs_emitted](https://user-images.githubusercontent.com/3329213/42449270-e5858750-8377-11e8-8ead-c671da136dd9.png)
I've cropped down the emitted photons, here is a generated spectrum in one band

and here it is banded...

![input_band_created_vs_emitted](https://user-images.githubusercontent.com/3329213/42449370-4d7b23b0-8378-11e8-8cc3-87205f364bb4.png)

Horrible....

**Comment by Higginbottom** [comment]
Here is a plot that illustrates what is going on!

![test](https://user-images.githubusercontent.com/3329213/42453681-6595cbc8-8385-11e8-836c-fef11cea5404.png)
![test](https://user-images.githubusercontent.com/3329213/42453718-8110c61e-8385-11e8-9716-a9dae3ecf352.png)

**Comment by Higginbottom** [comment]
OK, I think it is because the disk is so large. When one gets up to the high frequency bands, the 10 000 radial bins in the code that computes the equal luminosity annuli isn't enough, thousands of then return zero emissivity. If I increase the number of radial bins, the problem goes away. I rather think some kind of intelligent fix is called for, rather than just chucking more calculations at the problem. I'm going to do a little fiddle which, if it finds zeros in the radial bins it locally changes rmin and rmax, so all the radial bins are in bits of the disk that actually emit in the band in question...

**Comment by Higginbottom** [comment]
OK, so a more sensible approach is to use a log grid over the disk when computing the initial Lum vs r distribution. This gives more resolution where the temperature (and hence luminosity) is changing fastest.

Here is new version of the above simple version with this log scheme.

![input_band_created_vs_emitted](https://user-images.githubusercontent.com/3329213/42498686-baf144cc-8424-11e8-939a-0b38eb0a955f.png)

better - although there is an odd hump at low frequencies. While I've got my sleeves rolled up I;ll see why this is. I suspect it is because one ends up with a huge outer annulus at a low temperature. If one increases the number of annuli to 3001, it goes away. But there once more should be a clever way of dealing with this...

**Comment by Higginbottom** [comment]
OK, its not a huge outer annulus, but it is an oddly cold outer annulus.

You can see it here, where I have plotted the temprature vs radius of annuli in the lower frequency band. 

Orange is the standard 300 rings, blue is 3000 rings

I think this arises because when assigning a temperature to an annulus, we just choose the temperature at the geometric middle of the annulus. But T is not linear in R. A log interpolation would be better...

![picture1](https://user-images.githubusercontent.com/3329213/42499749-7e0be94c-8427-11e8-8e2a-e42504183eaf.png)

**Comment by Higginbottom** [comment]
OK, so a quick think about this reveals to me that there is basically no way of choosing a 'best' temperature for an annulus without computing the luminosity vs radius on a finer grid, and then interpolating. Which is utterly pointless, because we woulds just do the same number of calculations as simply having more annuli. So, we should discuss this, but ISTM that just upping NRINGS to 3001 from 301 will have very little impact on anything, probably, but will fix these problems. One could do better I'm sure...

**Comment by kslong** [comment]
So, I am trying to catch up on this.  If I understand correctly, the original problem arose because for different bands, Python calculated used different radial grids for different wavelength regions, and as a result of coarse gridding had different temperatures when it did so in the disk, and this was enough to produce the wacky output spectra with edges at the band boundaries.   And the problem may be worse tat the outer edge of the disk.   

I am a bit surprised we have not seen this before although maybe it is some how associated with the very large range in radii of this model.  In any event,the proposed solution ... more annulae in seems a perfectly reasonable way to address the problem.

**Comment by kslong** [comment]
...hmm.  I compared what happens if you just increase NRINGS by 10 to 3001.  It's different, but does not appear to fix the problem.  See the pdf file below,

[disk.pdf](https://github.com/agnwinds/python/files/2181497/disk.pdf)

**Comment by kslong** [comment]
Thinking about this a bit more.  As @Higginbottom  original plot shows, the problem is at high energies, so this means the problem is at the inner and not the outer edge of the disk.  What's going on I believe is that with such a large range in radius there is not enough resolution at the inner part of the disk.   Look at the first few rings, in the standard diagnostic file for the disk:

![screenshot_808](https://user-images.githubusercontent.com/2530901/42528381-e7455fc4-8440-11e8-8718-fc481b7780d9.png)

The temperature is already falling after element 1.    Now, note that what's printed out in disk diag is not what is used to calculate the annulae for each band pass, but it does suggest there is a problem there.    The integration that is used to create the annulae is actually very simply.  It's a fixed step integration, which is carried out in disk_init, and the number of steps is controlled by a variable NSTEP which is set to 1e7.   So I reasoned that setting it to 1e8 might help.   It changes things a bit:

![screenshot_809](https://user-images.githubusercontent.com/2530901/42528543-6a402116-8441-11e8-87fd-ebf19017b5a3.png)

We are getting better definition of the peak ... but we still get a spectrum that looks more or less what NIck got at the beginning.

I am finding this all fairly bizarre.  I have tried some of the other options for banding and several of them seem not to be working properly.

**Comment by Higginbottom** [comment]
Hi Knox,
So the fix is not just to change the number of annuli, but I also changed the way the annuli are made from a 'linear' scheme where all the annuli are the same radius, to a log scheme. This is mentioned above but there are a lot of messages, so easy to miss. 

The making the grid logarithmic captures the high temperature part of the disk much better, but it caused a problem at the other end - the extra hump in the low frequency part - this was caused because the low temperature part of the disk was more important, and not properly sampled. So increasing the number of rings fixed that. There is still a slightly unpleasant problem at the very high frequency band, where we are in the exponential part of all the rings...

![input_created_vs_emitted](https://user-images.githubusercontent.com/3329213/42551947-d7eedeb0-84d1-11e8-828a-64ee073af6f7.png)

**Comment by Higginbottom** [comment]
OK, so I'm a bit baffled as to this last thing. I *think* it is probably because the disk contributing to the spectrum at this frequency is just a tiny stub - with all annuli at very similar temperatures. So you get a very weak, high temperature blackbody rather than the exponential (ish) decline wed like.

There is another small issue. When we count out along the disk, filling annuli with emission we stop at the NRINGS-1 point, where there is still 1/NRINGS of the flux left to account for (at least for high frequency band where much of the disk doesn't emit). The code then just sets the outer radius of this last ring to rmax. Since this is pretty huge in this model, one ends up with a last ring that emits at a very low temperature (essentially the temperature of the midpoint of a very large ring). If there are 3000 rings, then 1/3000 of the flux comes from this ring - so not massively important.

**Comment by kslong** [comment]
I'm a bit confused still (especially by the comments concerning logarithmic grid).  I thought the way this worked was that an integration was done so that the annulae were set up so that an equal band limited luminosity was in each annulus, and that this is why the annulae change for different frequency bands.   

I also wonder why we are just seeing this problem now, since the disk spectrum generation software is very old.  Are the disk parameters very different from what we have calculated previously, or is it possible that an error has crept into the code.  

Finally, I would note now that we are investigating this, we need to check carefully that the total luminosity of the disk is what we think it ought to be.  I did check this many years ago, but given what we are seeing here, I think we need to recheck.

**Comment by Higginbottom** [comment]
There seems to be an odd bit of logic. I think that when one is calculating the annuli, one always triggers the "if (nrings >= NRINGS)" error condition, because one always needs nrings=NRINGS to get all the flux. Thus, at this point the r that has just been assigned to the NRINGS-1 array element is the radius that encompasses all the emission. 
Then, one drops out, and resets the radius for NRINGS-1 to rmax. This is regardless of what the r that encompasses the whole disk actually is. Surely, this last r element should be that which contains all the disk emission. Usually, this will indeed by rmax, but if the frequencies are high, then it is not correct, and the last annulus ends up very cold. 
not a big problem, but a little irritating...

**Comment by kslong** [comment]
Note that my statement that some of the stratified sampling options seemed to be failing was incorrect.  I was confused by the log outputs referring to init_freqs (used for setting up the coarse spectra) and those used for stratified sampling.  I have  updated the comments in bands.c to try to clarify the difference and silenced some of the  logging to the screen to reduce the confusion (for me) in future.

**Comment by Higginbottom** [comment]
so, the new scheme generates a lot more errors of the type

disk_init: Got to ftot 1.705330e+34 at r 2.399977e+10 < rmax 2.400000e+10. OK if freqs are high

now, I think this is because the grinding scheme is actually *better* and we get to ftot very slightly inside the maximum disk radius, rather more often that we used to. I've checked and in the old scheme, when we didn't get to the total disk flux, we normally fell short by something like 10^18 parts in 10^36. So it is really a rounding issue. 
I think this error needs to be removed - it isn't really an error anyway....

**Comment by Higginbottom** [comment]
OK, final comments.
The error   if (nrings < NRINGS - 1)
actually deals with the problem of not having enough rings.
Run regression tests, and everything seems fine - one or two more photons lost errors, most likely from making photons really close in because the disk is better sampled.
Closing this out with commit #399
