### ISSUE TITLE
hydro model import does not understand domains completely

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#397]
There are multiple questions in hydro_import of XXX form  and particularly hydro_restart about what is happening and it is evident that the routine would fail if the one, for whatever reason, wanted to use multiple domains.  While we may not think that this is a likely use mode for python, it would good to fix them, and it looks fairly straightforward.  I suspect most of the other comments, some by ksl and James are just worries, it would be good for Nick to look at them and make sure nothing is amiss (and provide a little clearer explanation).

Note:  There were other XXX like questions earlier on in the file, but it looked like they had been fixed/explained so before submitting this issue, I removed them.

**Comment by Higginbottom** [comment]
I have now run an SV model overlaid on a hydro model. 
It runs OK, but when the heatcool file is output, it outputs both domains. 
So this problem is still live.

Unsure of how to proceed - I think there there needs to be some kind of note as to which domain is the hydro domain - so that when outputting the heat cool file only this domain is output.

Investigating....

I do believe that the basic function of the hydro code when there isn't another domain present is OK, so the commit as it stands is fine.

**Comment by Higginbottom** [comment]
I have now modified wind_update2d.c so it only writes out the hydro domain.
Pulled in #419 
There is still a rather minor issue about how the maximum radius in the wind is set. Nonetheless, since the hydro mode now 'understands' domains, I'm closing this.
