### ISSUE TITLE
Spurious features in fairly standard cv model

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#400]
Keara and Stuart reported odd features in the spectra of a cv model they were running on dev branch.  The problems can be produced with 
[cv_standard.pf.txt](https://github.com/agnwinds/python/files/2229468/cv_standard.pf.txt)  This is a small variant of the standard cv model with 1e7photons, 10 ionization and 10  spectral cycles.

The features are appear in the the wind generated photons in cv.spec  and look like this

![screenshot_814](https://user-images.githubusercontent.com/2530901/43226210-c969dc50-9020-11e8-8e30-106d93b9dbae.png)

I have duplicated the problem, running on my mac with 4 processors   The problem is something to do with the spectral cycles.  As far as I can tell these features do not appear in the wind_tot spectra.  More significantly, if one plots the spectra after each spectral cycle, then the problem does not appear until Cylce 2 or 10 (actually cycle 3 since we start with 0).    For cycle 0, the same plot as above looks like this:

![screenshot_813](https://user-images.githubusercontent.com/2530901/43226342-38500d56-9021-11e8-9ad0-4f4ba342fdbb.png)

(Note that there is a page on Evernote, where Keara documented the problem first)

All of this is quite weird, @ssim @jhmatthews @Higginbottom   ( I actually am running this on the fuori branch, which does not have Nick's updates to disk model in it, so despite the fact that several of the features look double peaked this probably has nothing to do with the work which Nick did.  Rather the double peaks are probably due to the fact that the wind is rotating.)

**Comment by kslong** [comment]
Furthermore, the number of these peaks increases as the number of cycles increases.
![screenshot_815](https://user-images.githubusercontent.com/2530901/43227316-fca2db3c-9023-11e8-9987-4307fccb5854.png)

**Comment by kslong** [comment]
I reran this model with 1 processor.  There are not as many "features" but they are there so, it's not some kind of mpi problem.

Reducing the number of photons per cycle by a factor of 10 does not alleviate the problem.

The problem is also apparent in the cv.pf model that is part of our standard regression tests, so this is an indictment of our regression testing, since no one had noticed this.  (Note though one needed to have been looking for the problem because the statistics of our cv model in regression are not that good.)

**Comment by kslong** [comment]
We have discovered that this problem is arising in one_line which generates a frequency for a line.  The problem is the the frequency line luminosity exceeds the sum of the powers in lin_ptr, which is what is used to select which frequency is returned.  When this happens, the frequency is the last frequency in the frequency limited line list.  Because in the example we looked the line luminosity is a lot greater than the sum of the various individual intensities, we get a feature.  What appears to be happening is that the lin_ptr[n]->pow array is not updated before tying to create a photon in each cell.  

We have evidence that this error is new, and appeared some time after Nov 2017.

**Comment by mandyhewitt** [comment]
This bug was introduced on Dec 04 2017 by commit 2e5297e4f99088a962598001cdd108cd1ffb05e7

See output wind spectral file from this python run (Dec 4) using a modified cv_standard.pf as used on original discovery of the issue (by Keara).

 In particular, notice that the carbon 4 line around 1550 Angstroms was clean and distinct (further down below on Dec 03) in both the wind spectrum (red) and wind log spectrum (blue) but on Dec 04 the linear wind spectra and log spectra are no longer in sync and there are many spurious lines:

![image](https://user-images.githubusercontent.com/32335653/43593516-def6bb2e-966f-11e8-8f91-30963efc02ee.png)

and one day earlier run from Dec 03 2017 by commit c6dff8cae54e671750781acfa387218b2a59ddeb


![image](https://user-images.githubusercontent.com/32335653/43593992-071bd354-9671-11e8-99ef-c3b23ebfd8b0.png)


Parameter file is:

[dec042017.pf.txt](https://github.com/agnwinds/python/files/2254142/dec042017.pf.txt)

**Comment by kslong** [comment]
This what one_line like when we did not have this problem:

![screenshot_818](https://user-images.githubusercontent.com/2530901/43654627-bfe53c4a-9743-11e8-81ee-1f840bea8bfb.png)

Notice that is pretty clear that we calculated the ->pow for this element at that point, when we also checked whether the luminosity was sufficient.

**Comment by kslong** [comment]
This problem should now be fixed with commit 3be24edb  All of the changes were emission.c
