### ISSUE TITLE
Time-dependent radiative transfer

### ISSUE THREAD

**Issue by lazygun37** [sirocco-rt/sirocco#409]
At the moment, the ionization state calculated by python is only strictly correct for situations in which the input radiation field is constant in time.

In the context of reverneration mapping -- which explicitly deals with time-dependent continuum luminosity variations -- we fudge this by effectively treating the limit of "small" changes. This is somewhat unsatisfactory because the actual -- observed -- luminosity changes in AGN reverberation mapping campaigns are not usually small -- they can be easily tens of percent, up to factors of several.

Ideally, we would deal with this by making python explicitly time-dependent. The specific situation I am envisaging here is that we still (for now, anyway) treat the physical parameters of the flow (geometry, density, kinematics) as constant in time, but we want to have the correct ionization state and observed spectra at any given time. We would also be OK with the assumption (I think -- again, this would ideally need checking) that the ionization/recombination time-scale is short compared to the light crossing time (and, really, also the flow time-scale -- see the "frozen ionization fractions" issue).

SS thinks this is not actually that difficult to implement (albeit tedious in terms of the additional book-keeping required). 

SS: Could you please summarize again roughly the scheme you outlined?

**Comment by ssim** [comment]
My broad suggestion would be (initially) to consider a scheme like we use for the SNe:
 

- Put an outer loop over timesteps around the algorithm

- Give all the photons a private "clock" variable: i.e. a scalar that is used to record their progression in time (analogous to their position that we already record and follow in space). This is time as measured in the observer frame, and it's followed separately for each photon packet.

- Whenever packets move their "clock" is updated by distance / c

- Packets are initialised in some manner throughout the simulation volume at the start of the full simulation. E.g. inject a BB distribution into each cell at its initial guess temperatures. Reliable results will likely depend on running for enough timesteps that this initial guess radiation field has been forgotten (i.e. many light crossing times)...or that it was a good guess!

- Further packets are injected to the simulation during each timestep to represent the ongoing radiation coming in from each of the boundary sources. The total energy injected during a timestep is the luminosity of the relevant source times timestep duration. The packets are injected at randomly drawn times during the timestep to simulate a constant luminosity during the timestep (or you might want to bias their injection times if you want to capture a luminosity gradient -- I'm not really sure if that helps or not ...probably not: i.e. the way to capture rapid time variation in boundary luminosity is really just to have short timesteps). Injected packets have their clock initialised to the time they are injected, and then it "ticks" as normal from then on.

- Whenever a packet's clock reaches the end time of the current timestep it stops and is "parked" until the simulation progresses to the next timestep. Packets otherwise interact as normal inside the simulation domain and can leave through the domain boundaries, just as normal. (Outgoing packets record the time they leave the domain for use in binning them up to make time-dependent spectra: note: when making spectra, relative differences in light travel time outside the computational domain to the observer need to be taken into account - this can be a significant effect.)

- If it is assumed that matter reaches equilibrium with its local radiation field very fast (i.e. ionization is NOT frozen in etc.) then the estimators are recorded in just the usual way during each timestep to get values for everything during that timestep (radiation field model, ionization rates etc.). From these the plasma conditions can be calculated for each timestep.

- Photon packet states are stored at the point when their clock time runs out for the current time step and are then restarted from that state / position etc. in the next time step. If it's necessary to iterate on plasma conditions for each timestep, then you can store the packet properties at the end of timestep n then run timestep n+1 multiple times (each time restarting the packets from their stored end-of-n state) until you are happy that the conditions for timestep n+1 are converged. Then you move on to timestep n+2 etc.

The story above is assuming that things like the density / velocity are in a steady state (i.e. there is not an important net change in e.g. density or velocity during a timestep). It also assumes that the ionization / heating are always determined by the instantaneous local radiation field (i.e. that recombination and cooling are still fast ...i.e. the approach accounts for the time variation of the radiation field but not for freezing in of excitation or ionization). The basic idea can likely be developed to approximate other conditions too (e.g. a completely frozen in ionization state, which would be pretty simple to implement too).

**Comment by kslong** [comment]
This is desirable, but a pure enahancement that would need a specific project to undertake. We do have the person power for this.
