### ISSUE TITLE
Macro atom transition probabilities via Matrix solution

### ISSUE THREAD

**Issue by ssim** [sirocco-rt/sirocco#423]
As outlines in Belfast, could implement methods developed by others to avoid explicitly following internal macro atom state transitions. Based on matrix inversion method. Before attempting this would first need to scope out what's feasible:

- need for new routines to gather data into appropriate matrix (probably not expensive but need to consider how to implement)
- main question is probably about storage: matrix could get large (quantify)
- speed of inversion - need to scope out how long a call to this process would take at runtime.

**Comment by jhmatthews** [comment]
This was partly implemented during the Soton 2019 code week. There is some discussion on evernote. The current code is in the hyper_macro branch and can be turned off and on via the ```#define ACCELERATE_MACRO 1``` flag in photo_gen_matom.c.

**Comment by jhmatthews** [comment]
I've been testing this implementation a bit -- in which the accelerated scheme is only used in the matom emissivities part of the code -- and documenting / streamlining the code. The latter part is mostly done. The tests currently seem to produce differences with dev when using the cv_macro_benchmark pf file, beyond the statistical effect I would expect. The emissivities seem systematically lower in the new version. Possibly the new code doesn't work so well when extra ion species are included. Investigating.

**Comment by jhmatthews** [comment]
This has now been "fully" implemented in the ```matom_matrix``` branch. This note is just a todo item for me to describe the code changes here.

**Comment by jhmatthews** [comment]
The main changes to the code, currently in the matom_matrix branch, are as follows. This branch can be compared to dev by going to this link: https://github.com/agnwinds/python/compare/dev...matom_matrix.

**Usage:** To use the matrix scheme, select ```matrix``` as the response to the question ```Matom_transition_mode(mc_jumps,matrix)``` in the parameter file. ```mc_jumps``` uses the old method, but still uses the accelerated scheme for the emissivity calculation. This needs to documented on ReadTheDocs, and the parameter files need updating where necessary before merging into dev. 

### Main Code Changes
**Modes / infrastructure**
* new variables in the macromain structure for storing the matrix, as well as various flags.
* a new variable in the modes structure which determines whether we are storing the matrix (possibility to include a partial or adaptive option here in future). At the moment the ```macromain[n].store_matom_matrix``` directly inherits the ```modes.store_matom_matrix``` value which is set by the command line flag.
* new variable ```geo.matom_transition_mode``` which is either ```MATOM_MC_JUMPS``` or ```MATOM_MATRIX``` (again possibility to include a partial or adaptive option here in future). At the moment the ```macromain[n].matom_transition_mode``` directly inherits the ```geo.matom_transition_mode``` value which is set by the keyword in the parameter file. 
* new kpkt modes, with the possibility to ignore cooling pathways that excite macro-atoms.
```C
#define KPKT_MODE_CONTINUUM  0          /* only account for k->r processes */
#define KPKT_MODE_ALL        1          /* account for all cooling processes */
#define KPKT_MODE_CONT_PLUS_ADIABATIC 2 /* account for k->r and adiabatic destruction */
```

**in macro_accelerate.c:**
* A new function ```matom_deactivation_from_matrix()``` which chooses the deactivating state ```j```  for a given activating state ```uplvl``` by randomly by sampling the B matrix. The function checks whether the matrix is stored -- if it is, it uses the stored matrix, but otherwise it calculates it on the fly. 
* A new function ```calc_all_matom_matrices ()``` which does a parallelised loop to calculate every matom matrix and store it in macromain, before calling ```communicate_matom_matrices ()``` to communicate the matrices between threads. 
* modifications to ```fill_kpkt_rates``` to also record the simple ion only bound-bound cooling, stored in ```mplasma->cooling_bb_simple_tot```

**In macro_gov.c:**
* various modifications to the macro_gov routine.  
* if we are using the old mc_jumps method, the old functionality is preserved, although the order in which checks for simple ions
* if we are using matrix method, we first check if we have excited a simple ion. If so, we choose a k or r packet. If we have an r-packet, we exit immediately. If we have a k-packet, we choose the deactivation pathway from the matrix accordingly. If we started with a macro-atom interaction, we go straight to the matrix bit and choose the deactivation pathway from the matrix accordingly.
* Once we know our deactivation, we choose our new photon frequency and so on by calling either emit_matom, or kpkt. 

**In para_update.c:**
* a new function  ```communicate_matom_matrices ()``` which communicates the matrices between threads after they have been calculated
* a new function ```get_parallel_nrange```, a helper routine for splitting up tasks in MPI and avoiding code duplication

**In gridwind.c:**
* a new function ```calloc_matom_matrix()``` which allocates space for each stored matrix. 

**In matom.c:**
* changes to kpkt to allow for modes that only allow k->r transitions (no macro-atom excitations). Note that simple ions are basically direct k->r pathways in our approach. 

The changes specifically for parallelisation can be viewed in this PR: https://github.com/agnwinds/python/pull/895

### Caveats/Concerns
* **I have only done limited testing! BETA! Use at your own risk!** (although tests so far look pretty good)
* Doesn't always seem to give a speedup yet
* Really limited testing of new parallel version

**Given the major changes, it would probably be good if someone independently checked the following things:** 
* changes to matom.c and  macro_accelerate.c to get the basic scheme working
* the parallelisation routines
* the extra code infrastructure and that things are reset /initialised in the right places.

**Comment by jhmatthews** [comment]
Since this has been implemented and the results are good, I believe this can now be closed. Issues to do with estimators that were uncovered are described in #910. The performance of the routine is being investigated in #669
