### ISSUE TITLE
spherical coordinate type is misinterpreted as spherical_polar

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#444]
Trying to run a shell model in py82i, I try to use the 'correct' word base coordinate system:

Wind_type(SV,star,hydro,corona,kwd,homologous,yso,shell,imported)                    shell

Wind.coord_system(spherical,cylindrical,spherical_polar,cyl_var                    spherical

but I get in stdout:

Wind_type(SV,star,hydro,corona,kwd,homologous,yso,shell,imported)   shell
XX shell
XXX the answer was shell
Wind.coord_system(spherical,cylindrical,spherical_polar,cyl_var)   spherical
XX spherical_polar
XXX the answer was spherical_polar

Will try and fix...

**Comment by Higginbottom** [comment]
Ok, as far as I can make out the routine string2int is *totally* broken. If it works, it only works by accident. 
It checks for either a list of numbers or words, but the test for numbers is bonkers.
It makes a list of numbers using:

for (i = 0; i < strlen (string_values); i++)
  {
    values[i] = tolower (string_values[i]);
  }

but this counts commas as well as numbers, so you end up with a long array including commas.

Later on, this line

nchoices =
    sscanf (values, "%d %d %d %d %d %d %d %d %d %d", &xv[0], &xv[1], &xv[2], &xv[3], &xv[4], &xv[5], &xv[6], &xv[7], &xv[8], &xv[9]);

runs though this array, and if the case of the wind coord system (and other presumably) there are more than 9 numbers and commas, so even though there should only be 5 choices, it ends up with 9.
This is probably a separate problem to the erroneous matching of spherical to spherical polar - but clearly this routine needs some work...

Assigning to KSL...

**Comment by Higginbottom** [comment]
OK, here is a problem, this loop

  for (i = 0; i < strlen (values); i++)
  {
    if (values[i] == ',')
    {
      values[i] = ' ';
      vcommas++;
    }

does a loop over the length of the originally declared array values, which has length LINELEN rather than the actual length of the input arrays, which should have been copied char by char to the values array. So, this is a problem because the values/choices arrays are not zeroed - so contain lots of junk that then gets parsed. 
A couple of fixes -

1: zero the contents of values and choices arrays.
2:when removing commas, only loop over the initial arrays.

Then, to fix the problem where spherical is erroneously matched to spherical_polar, compare the strings using the length of the option, rather than the answer, so

instead of

if (strncmp (word, xs[i], strlen (word)) == 0)

which compares only the first 9 characters of spherical_polar to the input, and so can match either spherical or spherical polar

do

    if (strncmp (word, xs[i], strlen (xs[i])) == 0)

so all of the characters in the spherical_polar will match.

Think this is fixing this...

**Comment by Higginbottom** [comment]
Ack - the is of course a problem - travis failed because the questions where y/n were the answers to questions that needed yes or no screwed up. 
I've simply modified the questions to require y/n rather than yes or no. There should be some kind of clever fix here, realising that yes no questions  can accept y/n. Or changing the travis files (and examples) to use yes or no instead of y/n.

**Comment by Higginbottom** [comment]
Ok, I'm going to leave this - but leave it open for comments - one last thing - there are a lot of printf statements in the code and it is not well commented. 
Might need a tidy up....

**Comment by kslong** [comment]
I am baffled by this discussion.  The way rdchoice worked when I left was to do a minimum match.  So either y or n or yes or no should have worked.    A further cause for my bafflement was that the regression tests were all working, and one of these was a shell model.   It would have been very helpful to provide a .pf file that illustrated the problem.

 @Higginbottom   We should not have modified the questions to expect y/n instead of yes no.   Instead we need to make sure that we have the right code solution, which should take an answer of y from the command line and write out to the .out.pf file the full word yes.

It looks like to me that the actual problem was assoicated with the fact than when one responds "spherical"  there may have been two "answers" that could be minimum matched.

**Comment by Higginbottom** [comment]
Its possible it was working on some machines but not on all. I agree that the minimum match was what was intended, but this is clearly not ideal with spherical vs spherical_polar. 
It was very hard to debug due to lack of commenting.....
I didn't think it was worth uploading a .pf file since I wasn't expecting you to work on it while on holiday - sorry, but I needed to get it working so I could progress. Feel free to implement a fix of your liking - I didn't want to do a load of coding when I couldn't properly understand the code - so I did what was necessary....

**Comment by Higginbottom** [comment]
I suspect that the reason it was working with the regression, is that the regression tests all use numbers, not text....
With numbers it is fine. Thats certainly the reason the travis tests were working - the only shell model is the 1dsn.pf file - that uses numbers.

**Comment by kslong** [comment]
What it is,  is not complete.  We should check if the minimum match produces an ambiguous result.  I knew this was a problem. In this case the simplest workaround would have been to replace spherical_polar by polar. Please put any set of .pf files you would like checked on the page, and I will look at this some time in the future.

**Comment by kslong** [comment]
@Higginbottom   I have made updates to rdchoice which I believe reflect your concerns about the way it was working.  In particular, I have restored the minimal match capability that was intended, but provided checks when what is input is ambiguous.  In the process, I have updated the string definitions for coordinate systems so that "spherical_polar" is replaced by "polar" to reduce the possibility of ambiguous inputs.

I encourage you (and others) to carry out additional checks of the new rdchoice capability.   If something arises, I would like this to reported under issue #362, and I will attempt to fix the problem.  Please describe the problem and provide a .pf file which illustrates it.  At least for now, I prefer you not try to fix a problem yourself, because, as you noted, the documentation my not be sufficient to understand the ramifications of a simple fix to a problem.

Aside: Currently the regression directory does not include a shell model.  I think it would be a good idea to add one, because the shell model is fairly central to some of the diagnostics routines for ionization balance that have been set up, but is coded in a way that goes around a lot of the normal inputs, which means others may not always understand the implications of changes elsewhere in the code to the shell model.  Nick, you are the ideal person to decide what parameters should be included in this, so I leave this to you to do, if you agree it would be useful.
