### ISSUE TITLE
py_wind failing on macro atoms

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#473]
In trying to verify that #290 could be closed, I find py_wind is failing on this input file in py82k (dev)

[original.pf.txt](https://github.com/agnwinds/python/files/2869565/original.pf.txt)

Here are the commands I used to cause the failure, as well as the indication of where it is failing:

![screenshot_920](https://user-images.githubusercontent.com/2530901/52862453-f14fb200-30fa-11e9-8db8-03c3bfee5d14.png)

**Comment by jhmatthews** [comment]
I think this is due to the levden array note being calloc-ed. It's a bit confusing to me since I'm sure it used to work, but perhaps no-one has used it since the xplasma arrays started being dynamically allocated. Fix is just to add dynamic allocation of arrays to copy_plasma. 

Travis could test py_wind as well if we want, by running it on a simple very fast model and querying with all the commands possible. 

I will submit a specific fix for this today.
