### ISSUE TITLE
clock_gettime requires differnt libraries depending on compiler and machine

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#474]
@saultyevil  added better time tracking using clock_gettime to py83, but unfortunately this requires different LDFLAGS in certain situations

- mpicc works fine both on linux and osx with no change to the existing Makefile
- gcc works fine on osx
- gcc fails on linux, or at least it does on the version of linux we are running at STScI.  Instead you need to add -lrt to the LDFLAGS

But on osx, lrt does not exist and this causes the compilation to fail.  We need gcc for diagnostic purposes so this is not really an acceptable situation.

**Comment by saultyevil** [comment]
Oh dear, I only tested the code using a fairly recent version of gcc. Specifically, I used gcc 7.3 on Ubuntu 18 and clang 10 on MacOS 10.14 to test the code whilst developing. It's also compiling using gcc 5.4 on Ubuntu 16. What are you using at STSci?

Unfortunately, I didn't notice that `clock_gettime` isn't defined in the C standard, but is actually defined in one of the POSIX standards. I think -lrt needs to be linked for versions of libc prior to 2.17. Weirdly though, it seems Apple chose to implement the librt (-lrt) function in their standard of Clang a bit differently... 

If we can't figure a solution, I'll write something more portable this time :-).

**Comment by kslong** [comment]
Gcc4.4.7, on the machine I was working on.  I found another machine at STSCI, where they had gcc 4.8.5 and there I did not have compilation errors.   So this does seem to have to do with the exact version of gcc.

One wonders if one were sufficiently clever, whether a Makefile could check for a library.

For me, ./configure is not even a really good option, although it would be livable.  This is because we have a disk area that is common to a number of machines.

Note that I expect good programming practice would be to either use clock_gettime or gettimeofday but not both as we do now, so an informed decision should be made on this.

**Comment by saultyevil** [comment]
I think a simple fix here would just be to check the version of gcc/glibc in the Makefile. We already check to see if gcc is 4.8 or above and add the extra flag `-fno-aggressive-loop-optimizations` if it is. So I think it would fit in neatly if we check for older versions of gcc and then add the extra flag -lrt.

But actually, I think this is becomes a little more complicated when you worry about macOS, since gcc is aliased to clang by default and `gcc -dumpversion` returns 4.2.1 for me on masOS 10.14 (note that you don't need to use `-lrt` for clang and that it doesn't understand the flag anyway). An extra bit of logic to check the operating system would probably help, but then the Makefile is becoming more complicated than it needs to be I guess.

**Comment by saultyevil** [comment]
Building on what was said in the telecon, I think there are a few ways which we could address this issue.

1. We could check the compiler version in the Makefile and adjust the library flags accordingly. This would likely mean we're applying the `-lrt` flag for old versions such as gcc 4.4. If we're doing this, we should also be checking the current OS, which is something we did in the past for the old indentation method. This would be done to avoid any headaches with macOS and clang. I think excluding mpicc from these checks would be fine, since mpicc, for OpenMPI at least, uses a pretty modern version of gcc.
2. Switch to using `gettimeofday` instead of `clock_gettime` as we already know this is more portable. This would only require a minor change to the new timing routines. But, I'm of the opinion that `clock_gettime` is probably the better routine for us due to being able to set which reference clock we are using, i.e. `CLOCK_MONOTONIC` will generally use Unix time and `CLOCK_THREAD_CPUTIME_ID` will use a thread specific timer.
3. We could check the compiler version and just exit out for an old or imcompatible compiler (this is probably bad, but the Linux kernel development team did something similar).

The quick fix now is for Knox to set the `-lrt` flag for just his machine at STScI. But, for the long term fix, I would be interested in what other people think. I think it's worth thinking about if we ever consider going down the MPI/OpenMP hybrid parallelsation route, since right now clang doesn't support OpenMP and we would likely have to deal with that problem in a similar way.

**Comment by saultyevil** [comment]
This issue has been resolved with PR #480, so I'm closing the issue. If there are any other issues, then I propose we should go back to using gettimeofday exclusively instead.

**Comment by Higginbottom** [comment]
Just tried to compile on my old mac - tried commit 85537ae971e1c6f12e153d4d4b90e016c7b19888

Make fails with 

time.c:123:3: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
  clock_gettime (CLOCK_TYPE, &timer_t0);
  ^
time.c:123:18: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
  clock_gettime (CLOCK_TYPE, &timer_t0);
                 ^
time.c:116:20: note: expanded from macro 'CLOCK_TYPE'
#define CLOCK_TYPE CLOCK_PROCESS_CPUTIME_ID
                   ^
time.c:153:18: error: use of undeclared identifier 'CLOCK_PROCESS_CPUTIME_ID'
  clock_gettime (CLOCK_TYPE, &timer_t1);
                 ^
time.c:116:20: note: expanded from macro 'CLOCK_TYPE'
#define CLOCK_TYPE CLOCK_PROCESS_CPUTIME_ID
                   ^
1 warning and 2 errors generated.


This is for mpicc 4.2.1

I guess I need to update?

**Comment by kslong** [comment]
Try finding out what .h file you need first, and add it to the top of the file.  Note that is is probably not mpicc that is a problem as this is a wrapper around cc I believe

On my mac

mpicc --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by Higginbottom** [comment]
I get

SOTONMAC /Users/nsh2m14/python/source =>mpicc --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin17.7.0
Thread model: posix

Seems quite old. I'm updating Xcode which is so out of date that macports won't update mpicc...

I don't really know how to find what .h file I need - seems like a fiddle to have to edit the source to get it to compile, but do you have any hints?

**Comment by kslong** [comment]
The man page will tell you what include files you need assuming man works.  I believe (but would have to check) that it should not matter if different compilers use different include files.

K

**Comment by Higginbottom** [comment]
Which man file? 
man time says resource.h but I don't think thats correct?
I'm re-installing Xcode - that will take a while but might fix it. 
Ed thinks this may fix it.....

**Comment by saultyevil** [comment]
Yeah, I'm guessing Clang 7 could be one of those older versions of Clang which doesn't implement/support clock_gettime because of reasons. `man clock_gettime` shows that it's included in time.h, so I don't think the correct header is missing. I think trying to catch all of the different compilers, especially for Macs, may become tricky. If Nick updating Clang doesn't fix his issue, then I think switching back to gettimeofday would be the easiest solution to this.

**Comment by kslong** [comment]
I favor switching back also, even though I expect using up to date versions of compilers would solve the problem..  I’m not convinced the new method is “much” more accurate, and we are not always in charge of the version of a compiler that is on the machines we run on.

**Comment by kslong** [comment]
Just try  in a terminal window

man clock_gettime

… but I suspect as you say upgrading will solve the immediate problem

**Comment by Higginbottom** [comment]
I wouldn’t worry on my account. Its an old machine what I don’t really use for heavy lifting. I just mentioned it coz I thought it would be useful for debugging - if we want to get the code into thee wild - others may have similar old compilers…

N

**Comment by saultyevil** [comment]
I've switched clock_gettime to gettimeofdaynow and reverted the Makefile to not include the rt library, so hopfully there should be no errors. I'll keep this issue open for now and will close later if there are no issues.

**Comment by saultyevil** [comment]
I haven't heard any issues since updating the timing routines, so I feel like this can be closed now.
