### ISSUE TITLE
Exit(0) is misleading when thread other than 0 fails.

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#488]
Exit(0) is intended to safely close out all of the MPI processes when a serious error occurs.  It also prints out the error summary from thread 0 as part of the process.  But if the program has failed because of, for example, thread 5, the reason for the failure is not particularly apparent.  It would be better in this case, if the routine printed out the summary errors for the thread that was actually causing the problem to fail, in this example, thread 5.

@saultyevil  if you have time to fix this, I would also appreciate it if we could avoid sending the standard MPI error close out, if there was only one thread.

**Comment by kslong** [comment]
I take it back @saultyevil   That's what it does already.

**Comment by saultyevil** [comment]
Knox, I have noticed that when we do exit from MPI that the error summary is printed only to the master processes. This sometimes means that whilst the error summary is printed to the correct diag file, it isn't always printed to the screen. If this was behaviour which you would like, I think it would mostly be a case of having a parallel version which uses Log_parallel instead of Log or using compiler directives to switch between Log and Log_parallel depending on how Python is compiled.

Anyway - if Python is only being run using one MPI process I can add an extra line or two of logic to catch that and exit with the standard exit instead of MPIs. That would be a really quick and simple thing to do.

**Comment by kslong** [comment]
OK … I misread the code.  I thought it was doing the “right” thing.   Yes, I think when an mpi process kills the code, it’s that thread whose errors we want printed to the screen.
