### ISSUE TITLE
New restart mode

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#51]
It is somewhat irritating from time to time that if one runs a model with spectral cycles, that one cannot then use the windsave file to produce a new spectrum even in -r mode.
I propose a new restart mode -s which simply resets the number of spectral cycles, and doesn't read in the specsave file. This lets you use a completed run to produce new spectra without needing to rerun all the ioinization cycles.
This is a minor niggle (and perhaps there is another way round it that I've not been able to find) but it is trivial to implement and would certainly save me a lot of irritating fiddling around keeping windsave files that have not had spectral cycles run...

Nick

**Comment by kslong** [comment]
This is so terse that I cannot understand the problem.    You need to describe these problems more completely.

From your description, I don't see why reading in the old model and using a .pf file with 0 ionization cycles and some number of spectral cycles does not work

We need to define all of the use cases for restarts and try to understand a generalized approach for what we want to do.  Maybe you can tack a crack at this.  If we do not,   we are going to simply end up with lots of unused or hard to document switches and no general concept.

I'm concerned in a number of areas that when we find a "difficulty", our approach to put in a band-aide without thinking about the long term.  It's understandable that there is tension between what we want to do today and the long term, but if we intend to make this program public, or even maintain it ourselves for a long time, we need work a bit more systematically, particularly (but not exclusively) in the area of reading inputs and restarting the program.

Knox

Knox S. Long
Space Telescope Science Institute

**Comment by jhmatthews** [comment]
So with the current restart mode, the windsave file contains the information on number of wind cycles executed (w), number of spectral cycles (s) and max number of wind cycles (wmax) and max number of spectral cycles (smax)

if w < wmax, it carries on with wind cycles.

if w=wmax and 0<s<smax then you carry on with spectral cycles by reading the specsave file. 

If however, you want to change what the spectral cycles do (e.g. no. of photons) have the problem case, because the specsave file contains information on the spectral cycles already computed. I came across a similar problem, for example if I wanted to look in the Balmer continuum in the YSO model. If s>0 then the model will only run if there is a specsave file present, and if there is then it will use the information from that and not your new pf file with different wavelength ranges (I think...). To me this new mode makes sense in terms of getting around that problem at least, and I can't really think of any other potential restart cases.

**Comment by kslong** [comment]
I agree James' last example is an issue. It is not so much related though to restart per se, as it is to what variables are read in from the parameter file on restart, and which are inherited from the old wind save file.  Nick already ran across one example of this problem when he tried to add a new source of radiation in the spectral cycles.   He made a quick fix to address his specific problem, but we did not follow up and decide what to do more generally.

One possibility for the general case is to say that on restart, all values are reread from the .pf file, and rely on the user to make sure that this makes sense.

A thing that would not make sense for example is to change the dimension of the wind, or anything that could affect the wind, including switching atomic data file.

The current philosophy, not exceptionally well-implemented, attempts to protect the user in some cases.

Knox

**Comment by Higginbottom** [comment]
I think it would be overkill to re-read the whole .pf file. My philosophy would be that one gets one chance to set up the wind - and the windsave file should reflect those choices. To my mind there is no reason why one would want to restart the ionization cycles a run with modified model midway through.
However, making changes to the spectral cycles after completing the ionization cycles seems reasonable.
This extra restart mode that I'm proposing simply resets the number of spectral cycles to zero which forces the code to recompute spectra.

**Comment by kslong** [comment]
```
NIck,
  I do not think this makes sense, and the sorts of models you are
  currently running are part of the reason.  
  You have use cases that say you want to change the radiation
  sources for the spectral cycles compared to the ionization cycles,
  and you just put in a change to python to make this possible.  
  Indeed your solution was to use read a portion of the the .pf file
  that in the extant version of the code was not reread.  
  That is exactly why I would like us to have a generic solution for
  this, one that one can explain in a users manual and not create a
  lot of one-off solutions.
  Furthermore, it is unclear to me that you cannot solve your
  problem currently by reading the old windsave file, setting the
  ionization cycles to 0, and setting the spectral cycles to
  whatever you want.
  Knox
  On 9/12/13 1:44 AM, Higginbottom wrote:

  I think it would be overkill to re-read the whole .pf file. My
    philosophy would be that one gets one chance to set up the wind
    - and the windsave file should reflect those choices. To my mind
    there is no reason why one would want to restart the ionization
    cycles a run with modified model midway through.
    However, making changes to the spectral cycles after completing
    the ionization cycles seems reasonable.
    This extra restart mode that I'm proposing simply resets the
    number of spectral cycles to zero which forces the code to
    recompute spectra.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by Higginbottom** [comment]
Ok, so I had no idea that setting the ionization cycles to zero would force it to redo a spectral cycle. This doesnt seem very intuitive to me, however since that is how to do it, I'll close the thread.
I'm also incredibly confused since it seems to me that James's 'use case' is identical to mine.
This is a different issue to adding radiation sources to the spectral cycles that were not in the ionization cycles, hence my starting a new thread.

**Comment by kslong** [comment]
I think some of these threads are creating confusion that is unnecessary, largely because we don't describe the problem adequately at the beginning.  Instead, we jump to an implementation for a problem, that to others is poorly described.  When we were detailing problems on the google site, we had a kind of format for describing a problem.  We need to a try to do this, separating the mentally separating the roll of user from the roll of developer, when a problem is described.

I am probably going to start harping on this from now on.

I also  have to disagree with your idea of what is intuitive or not, but I think the confusion is connected to the fact that we do not have the philosophy written down anywhere, e.g in a manual, and the fact that heretofore one has mainly been only concerned with extending an existing calculation.

Knox

Knox S. Long
Space Telescope Science Institute
