### ISSUE TITLE
Problem using -p and -t as options together

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#518]
I have been running a large grid of models, some of which were getting very bogged down, and so I have been trying to run the models using both the -t and -p options to fill in as much of the grid as a could.  However, whhat I have found is that with these models the -t option was not having any effect.  

One can easily duplicate the problem using the standard cv.pf file which is part of the regression tests, with a command like:

py -p -t 30 cv.pf  

Both the -t 30 and the -p options work when applied independently, but together, while the -p option continues to work, the program does not exit at the appropriate time.

(Aside, I may have run into a separate problem when running mpi that the program does not clean up all the mpi processes properly. However this only happened one time, and so needs to be verified.)

**Comment by kslong** [comment]
OK, so this problem is associated with the way the command line is being interpreted in parse.c

py -t 30 -p cv.pf

produces the correct result.  Undoubtedly the issue here is that -p is sufficient on its own, but -p 2 is also a possible command line option.

py -p 1 -t 30 cv.pf 

produces the correct result.

**Comment by kslong** [comment]
OK this was, as indicated, and issue in the parsing of the command line, and has now been fixed on branch  bug518_cut.

@saultyevil  I have fixed the issue where 

py -p -t 30 cv.pf 

does not stop after 30 s properly, because of a parsing issue in parse.c,  but there is a related issue associated with how python exists when it has exceeded the desired time. 

For me, what is happening on the dev branch with for example

mpirun -np 2 py -t 30 cv.pf

is that the program tries to exit, but does not do so completely.  This is because of the Exit command in the check_time function (which is in signal.c).  

Changing Exit to exit (the way the bug518_cut branch has it currently) does cause the proposal to exit completely but produces warnings. 

There should be a clean way to exit python when one wants to stop the program for excessive run time that does not produce errors like this. Can you look into it please. (It may be that this should be a new issue.)

**Comment by saultyevil** [comment]
I don't think using the wrapper Exit or the stdlib exit will allow Python to exit cleanly in MPI, as I believe MPI_Abort is always be loud and mpirun will complain when it detects that an MPI processes exits with a non-zero exit status or abnormally.

I think the way here to exit cleanly would be to use MPI_Finalize and then exit using the stdlib exit, rather than making a call to the wrapper Exit. But we may have to be careful here to make sure all MPI processes reach MPI_Finalize before we exit, otherwise I'm sure mpirun will complain.

**Comment by kslong** [comment]
I will look to you, Ed,  to work this out.  As long as the program actually exits and returns control to the command line, then I will be happy.  I just don't want to end up in the current situation, where one has to enter control-C to get out of the routine.  Among other things this means one cannot run a grid of models from a macro file (or a python script).

**Comment by saultyevil** [comment]
The issue with the deadlocks here was, I believe, caused due to synchronisation between the MPI processes. Essentially, each process will have a different total run time when they enter `check_time`, which could cause the situation where only a few processes have  exceeded the maximum run time. This means some would exit, whilst others would carry on and be unable to communicate with killed processes causing a deadlock. 

To get around this, I have added a reduction operation to find the maximum execution time and to communicate this to all processes. So if one process has exceed the maximum time, then all processes will exit. This does add some extra overhead to the function, but it should be small enough that it will be unnoticeable - at least for the number of processors we commonly use. 

I should also mention that mpirun will only exit "cleanly" without an error if Python exits with 0. Knox, if I remember correctly, you check the return code in your script to run Python, so I have set the exit code to 1 to indicate non-proper exit. Unfortunately, this makes mpirun return an error saying it detected a non-zero exit.

**Comment by kslong** [comment]
@saultyevil  I am going to close this.  The original problem has been dealt with, and you have convinced me that the best we can do is comment why the program is being ended with a non-zero value.  I can imagine that we should identify an exit code that indicates that we have had to terminate the code for "expected" reasons, and other error codes which really are failures of one sort or another.
