### ISSUE TITLE
mc estimators - stimulated emission

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#583]
The following .pf file does not run even after I but a limit on the number of times a sobolev density error was found.

[flat_rwtri.pf.txt](https://github.com/agnwinds/python/files/3483954/flat_rwtri.pf.txt)

```
Para:        20 -- model: %s %8.2f %8.2f
Para:        20 -- model: Rescaling spectra because parameter %f outside bound %f of spectra in grid
Para:        14 -- photon_checks:   nphot  origin  nres  freq     freqmin    freqmax
Para:        42 -- photon_checks: %id %5d %5d %10.4e %10.4e %10.4e freq out of range
Para:       398 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
Para:        99 -- sobolev: VERY BAD den_ion has negative density %g %g %g %g %g %g
Para:         2 -- walls: distance %g<0. Position %g %g %g 
Para:    100001 -- mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Para:    100000 -- stimfac %g, i %d, line[config[i].bbu_jump[j]].nconfigu %d
Para:         1 -- sobolev: suppressing negative density errors
```

This needs your attention @jhmatthews  Presumably it is the same problem that @saultyevil  has been finding with his TDE models, but this is a CV with a very flat wind profile.

**Comment by saultyevil** [comment]
I think this is a very similar problem to what I'm having. For completeness, I'll add the parameter file I'm having trouble with to this issue.

[tde_spherical_cno.pf.txt](https://github.com/agnwinds/python/files/3485732/tde_spherical_cno.pf.txt)

Here is the error summary from a run.

```
Para:     71817 -- walls: s %g < 0. Cur pos %g %g %g Old pos %g %g %g Cur lmn %g %g %g Old lmn %g %g %g
Para:      1035 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
Para:    100001 -- sobolev: VERY BAD xden_ion < 0: d1 %g d2 %g gl %g gu %g freq %g f %g
Para:    100000 -- sobolev: continuing by setting tau to zero
Para:      3161 -- mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Para:      3161 -- stimfac %g, i %d, line[config[i].bbu_jump[j]].nconfigu %d
Para:         3 -- photon_checks:   nphot  origin  nres  freq     freqmin    freqmax
Para:         4 -- photon_checks: %id %5d %5d %10.4e %10.4e %10.4e freq out of range
Para:         2 -- wind_update: Huge w %8.2e in cell %d trad %10.2e j %8.2e
Para:      8528 -- macro_pops: level %i has calculated pop. %8.4e in cell %i
Para:       328 -- macro_pops: found unreasonable populations in cell %i, so adopting dilute BBody excitation
```

I'm pretty sure I know what is causing the errors in walls and that they are very likely unrelated to the sobolev and estimator errors.

**Comment by jhmatthews** [comment]
I'm running Knox's file although haven't run into any errors yet. Could you both give some typical values for the actual errors? - i.e. the values the code spits out for the lines ```stimfac %g, i %d, line[config[i].bbu_jump[j]].nconfigu %d``` and ```sobolev: VERY BAD xden_ion < 0: d1 %g d2 %g gl %g gu %g freq %g f %g```

**Comment by saultyevil** [comment]
Sure, this is what I typically get in the spherical models.

```
Error: sobolev: VERY BAD xden_ion < 0: d1 5.24767e-08 d2 1.75285e-08 gl 3 gu 1 freq 1.37331e+13 f 0.32067
Error: sobolev: continuing by setting tau to zero
Error: sobolev: VERY BAD xden_ion < 0: d1 5.24767e-08 d2 1.75285e-08 gl 3 gu 1 freq 2.50453e+13 f 0.05867
Error: sobolev: continuing by setting tau to zero
Error: sobolev: VERY BAD xden_ion < 0: d1 4.17609e-08 d2 1.75285e-08 gl 3 gu 1 freq 9.392e+12 f 0.37667
Error: sobolev: continuing by setting tau to zero
Error: sobolev: VERY BAD xden_ion < 0: d1 5.24767e-08 d2 1.75285e-08 gl 3 gu 1 freq 3.3097e+13 f 0.02267
Error: sobolev: continuing by setting tau to zero
Error: sobolev: VERY BAD xden_ion < 0: d1 4.17609e-08 d2 1.75285e-08 gl 3 gu 1 freq 1.74399e+13 f 0.06867
```
```
Error: mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Error: stimfac 3, i 28, line[config[i].bbu_jump[j]].nconfigu 32
estimators: den_config (xplasma, i) 1.75285e-08  den_config (xplasma, line[config[i].bbu_jump[j]].nconfigu) 1.75285e-08 
Error: mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Error: stimfac 3, i 28, line[config[i].bbu_jump[j]].nconfigu 38
estimators: den_config (xplasma, i) 1.75285e-08  den_config (xplasma, line[config[i].bbu_jump[j]].nconfigu) 1.75285e-08 
Error: mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Error: stimfac 3, i 28, line[config[i].bbu_jump[j]].nconfigu 44
estimators: den_config (xplasma, i) 1.75285e-08  den_config (xplasma, line[config[i].bbu_jump[j]].nconfigu) 1.75285e-08 
Error: mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Error: stimfac 3, i 28, line[config[i].bbu_jump[j]].nconfigu 50
estimators: den_config (xplasma, i) 1.75285e-08  den_config (xplasma, line[config[i].bbu_jump[j]].nconfigu) 1.75285e-08 
Error: mc_estimator_normalise: bb stimulated correction factor is out of bound. Abort.
Error: stimfac 3, i 28, line[config[i].bbu_jump[j]].nconfigu 56
estimators: den_config (xplasma, i) 1.75285e-08  den_config (xplasma, line[config[i].bbu_jump[j]].nconfigu) 1.75285e-08 
```

[tde_spherical_cno_0.diag.txt](https://github.com/agnwinds/python/files/3486016/tde_spherical_cno_0.diag.txt)

**Comment by jhmatthews** [comment]
Ok, so at least in some cases for this example we are actually getting genuine population inversions in the upper levels of Helium I. It looks some of the lines (e.g. the 35-43 line in the He model atom, 119700A) are close to the critical value of 3, but one of them (e.g. 41-43) is quite far out. 

This shouldn't be allowed to happen, because we clean for inversions in macro_pops for any radiative transitions, so suggests to me that either something is being overwritten or that cleaning scheme isn't working properly. A quick inspection of the cleaning code looks sensible, so I'm not really sure what the issue is. Fundamentally we need to figure out how a population is being allowed through with n_u > (n_l * g_u/g_l) when there is an explicit check of that condition.

**Comment by jhmatthews** [comment]
So I think this error is somewhat artifical, in that it is happening for levels that have extremely low densities - in some cases equal to DENSITY_MIN = 1e-20. Normally these ions don't get noticed, because we only check this things when the level density is greater than 1e-10, but obviously if the ion density itself is high - say 1e12 - then we check it and run into "problems", especially if it's cold and dense and He I is the dominant He ion. 

So there is definitely one "artificial error" which is that if two levels in the line have hit the density floor, then they both get set to 1e-20 which can trip the population inversions warning. This could either be solved by setting them to some other floor (i.e. cleaning for inversions after setting the floor) or also explicitly checking if any of the densities = 1e-20. 

But that's not the full story, because in Knox's model, I printed out some densities and while this general behaviour is happening, one gets values like this for the levels:
```upper levden 1.8049e-20, lower levden 1.0000e-20, ion density 7.9156e+11```. This surprises me, because the lower_levden only gets set to 1e-20 if it is less than 1e-20, so if the upper level is 1.81e-20, then this implies a population inversion was present anyway. A little weird.

**Comment by jhmatthews** [comment]
Hmm. Can't really see how that could happen unless something is going wrong elsewhere. When does the segfault occur i.e. cycle no, portion of code? I will try and reproduce as well.

**Comment by jhmatthews** [comment]
It does seem that one issue is nden can be -1, so levden should only be used if nden >= 0. But even if I add something like this in, I am still getting a segfault. It's not clear to me that it's actually anything to do with this specific fix.

**Comment by kslong** [comment]
It is not obvious to me either … but I have not seen it before which suggests it is either directly related or we have some activated some path that was not there previously.

**Comment by jhmatthews** [comment]
Knox, can you try running with the latest version of dev, commit: https://github.com/agnwinds/python/commit/9560a876305912226bdfc2ebd2421c439c7d89a8 and let me know if you still get the segfault.

**Comment by kslong** [comment]
I see the same problem with today’s dev version.

**Comment by jhmatthews** [comment]
when does it happen?

**Comment by kslong** [comment]
It happens at the same place in the code … though not quite at the same time.

**Comment by jhmatthews** [comment]
This is totally bizarre. The segfault seems to happen at different places or not at all for me, in an apparently random way.

**Comment by kslong** [comment]
That’s not good.  Do you really mean it happens elsewhere in the code, or just at different times at the same place, which could be just due to different random numbers being generated.  I do notice that it occurred at a different time, and I did not wait to see it happen in a single processor run

**Comment by jhmatthews** [comment]
Ok. In at least one case I think it's happening due to this line interaction, which doesn't have a sensible nconfigu, which would presumably cause the issue. I've only had a brief look, but I can't actually find this line transition in the database. The lower level does exist in the levels database. 


```
result = {LinePtr | 0x17e19fbb0} 0x000000017e19fbb0
 nion = {int} 81
 z = {int} 14
 istate = {int} 3
 gl = {double} 5
 gu = {double} 3
 nconfigl = {int} 1435
 nconfigu = {int} -9999
 levl = {int} 3
 levu = {int} 12
 macro_info = {int} 0
 freq = {double} 3005782156638402.5
 f = {double} 0.047426999999999997
 el = {double} 0.000000000010552469103839999
 eu = {double} 0.000000000030471740370144004
 pow = {double} 0
 where_in_list = {int} 1245
 down_index = {int} 0
 up_index = {int} 0
 coll_index = {int} -999
```

**Comment by jhmatthews** [comment]
Hmm. I've found something suspicious. There's a line entry in the "excited.py" file which matches the above. I don't what the excited.py file actually is, but it seems to be able to create line transitions to levels that don't exist. This suggests a problem in get_atomicdata - bad checking of levels and so on -- as well as a need to understand what that file is and whether it should be there.

**Comment by kslong** [comment]
First, of all, good catch, but secondly, that file has been in Python for ages, and in particular it is in the directory atomic39 without any differences.   it's in both many of the macro atom datafiles and many of the non macro atom ones.  

Possibly, the fact we have a problem now has to do with the changes we made in Belfast to make simple atoms behave more like macro-atoms.  

I agree though we need to check in Python more clearly, or alternatively write a python script that checks all of this.  At one point, I wanted us to create a python script because I wanted to have something to help us build macro atom files.

**Comment by jhmatthews** [comment]
I'm opening a separate issue for this. I think it's purely a get_atomicdata problem.
