### ISSUE TITLE
Unknown spectype error for restarted model

### ISSUE THREAD

**Issue by jhmatthews** [sirocco-rt/sirocco#585]
I'm trying to restart Knox's flat_rwtri.pf model from issue #583. It doesn't work and I get the following error:
```
get_spectype: Programming error.  Unknown spectype 0
```
This happens when one tries to figure out what the default spectype is before it's actually read from the file. the possible spectypes are -1,-2,-3,-4,-5,-6,-99, but the value in geo.star_ion_spectype is 0 because it's a model (I think) and the spectype gets set to the number of models minus one, or something (???). 

Anyway, besides the obvious general code issues with modifying global variables and saving them and so on, one can presumably perhaps get around this by asking if the spectype is greater than zero? But it's not really clear to me what the desired behaviour here is for restarts and previous runs. I also tried just adding an if clause to get_spectype in setup.c:

```
if (*spectype >= 0)
      *spectype = SPECTYPE_BB;
```

to default the spectype to something recognisable, but in this case it doesn't seem to read in the models properly and fails with emittance_continuum errors.

**Comment by kslong** [comment]
Yes, I have duplicated the problem.

When one reads in models one assigns a positive number to the spectype so that one can have different sets of models for different radiative sources.  

But when one restarts these numbers are assigned to something that is not normally allowed.  Probably we need to avoid the rdpar statement and the checks the second time around.  We just have to worry about differences between this and system_type Previous

The problem also occurs if you try to restart the run, via system_type Previous

**Comment by kslong** [comment]
I think we just have to avoid the check for run_type previous or restart, and set the *spectype back to that for models if it is 0 or greater.

**Comment by kslong** [comment]
This should now be fixed.
