### ISSUE TITLE
Better initial conditions to shorten run times

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#617]
Currently, we define and initial temperature for each domain in the .pf file, and for each ionization cycle we allow the electron temperature to evolve toward a better value. We restrict how much the electron temperature in various ways, through a gain criterion which evolves with cycle depending on whether temperatures are headed in a particular direction, and also by a maximum change with is about 30% of the value in the last cycle.  We do this in order to prevent drastic changes in temperatures as a function of the cycle.

The downside of this, is that in the intial cycles we may be very far away from the "correct" result.  We address this at least partially using the -p option which for the earlier cycles uses less phtons than in later cycles (when we think we are closer to the "correct" solution).  

An alternative however would be to assume that a better estimate of the something close to the final solution would be to set the electron temperature to some faction of the radiation temperature.  This might reduce the number of ionization cycles that need to be run, and shorten the overall run time, which would be highly desirable.

This issue is raised to explore this problem/idea.

**Comment by lazygun37** [comment]
Improving our initial conditions could be a valuable enhancement. I am not completely convinced that setting Te to some fraction of Tr is necessary a good solution, at least for cases where we have significant X-ray power law contributions. It has the advantage of being simple to implement though.

What I think would be very useful would be to have a way of feeding in outputs from *similar* runs as initial conditions for new runs. This could speed up calculations for *grids* tremendously. Implementing this is harder though, because it requires more checks -- i.e. what do we mean by "similar", do you try to deal with different grid sizes/geometries, do you try to match on a cell basis or on a physical basis, etc etc.

I'm going to rate this as moderate priority for now.

**Comment by kslong** [comment]
@lazygun37  Feeding a previous model is possible in two ways, already.  If the wind geometries are identical you can use the "Previous" option on start up.  If they are similar, then you can always use the routines that generate the inputs for an imported model and deal with it that way.  

Using t_r of after the first cycle  to set t_e is something that I have tried.  It does help in the models I have tried.  Obviously for a pure power law model this will be worse than for a model with BB, but I suspect still is an improvement.

The real issue here though is whether you can do anything that is more efficient that ramping up the photon numbers through the ionization cycles.  That is the metric one needs to be judging against.  I was never convinced I could do much better (and the advantage of ramping up the photon numbers is that it is a method that is agnostic about your thermal vs power law models).

**Comment by kslong** [comment]
Obviously this is desirable, but we do have several approaches, including the -p swithc and using a previous file, and no one has time to work on this generically, so I am labelling this a zombie issue and closing it.
