### ISSUE TITLE
Package Reverb Python Scripts

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#627]
The Reverb python scripts need beating into shape as a proper python module that can be pip installed, with full documentation on how to use them.

I was aiming to have them be a subsection in a larger `py4py` module (i.e. `py4py.reverb`) as that's currently a free bit of namespace. We could fold some of the `py_progs` scripts in eventually (the ones that're routinely reused).

I'll create `agnwinds/py4py` which hopefully we can begin migrating across some of the contents of `py_progs` to.

**Comment by smangham** [comment]
I don't have the rights to create `agnwinds/py4py` it seems. @kslong would you be able to create it, or a repo with whatever name you think appropriate.

**Comment by kslong** [comment]
@smangham  I can do this, but why really do we want to create a separate repository and break what has so far been a fairly successful approach, that will require more things to be installed  by users..  I can imagine that we want to create modules under py_progs, which already is part of ones PYTHONPATH, and PATH in the current installation.    I can even imagine py_progs might not be the best name though again I think one would need a compelling reason to change.

As an aside, for those us using conda/astroconda  using pip install actually requires installing in every conda enviroment that one is likely to use, so for me this is a negative.

**Comment by kslong** [comment]
One more comment related to this.  I have wondered whether we should be combining the atomic data repository with the python repository, because it means it makes it harder to go back to old versions of the code which have different data files (in the examples directory).  Indeed, I think this is something we should consider for the release. Creating a 3rd repository would make this issue worse over time.

**Comment by smangham** [comment]
This was settled with #668
