### ISSUE TITLE
Create Source Script

### ISSUE THREAD

**Issue by smangham** [sirocco-rt/sirocco#628]
We want to create a bash file that can be sourced to streamline the process of setting up python.

It should add `bin/` and `py_progs/` to the path.

**Comment by kslong** [comment]
I don't actually see how this would work, unless it were generated on the fly at the time Python was installed, because we don't require Python to be installed in a particular place.  Our current installation procedures are actually quite simple.  If someone want to work on this, that would be fine, but I am going to close it for now, as very low priroity
