### ISSUE TITLE
Does it matter than only a very small number of X-sections (and no inner shell) is used in compute ds

### ISSUE THREAD

**Issue by Higginbottom** [sirocco-rt/sirocco#649]
In calculate ds, in the macro atom mode, the bound free opacity is calculated. TO speed up the code, a little script kbf_need is used to select which continuum cross sections will be used to calculate the total opacity and hence the ds.
While investigating how to speed up python, I played around with using the list that kbf_need draws up in order to limit the bound free opacities used later, in radiation.c. However, using that list meant that the results changed a lot, and in order to get the results to agree I had to dramatically widen the criteria for including cross sections, i.e. changing the threshold frequency range and also the peak opacity. 
In addition, inner shell bound free opacities are not included at all.
I don't really understand what is going on here - so this is a question to decide if we need to do more work. If it is important that we get ds correct - then this might be important Ibn cases where bf opacity is the most important.
Thoughts /advice from the macro atom experts?

**Comment by ssim** [comment]
This is / was an attempt to speed up the code. The underlying issue was (is?) that calculating the bound-free opacity as a sum over all cross-sections was very expensive so it was restricted to a subset to try to speed it up. Basically if we exclude negligible processes consistently (i.e. include them neither as a contribution to the opacity - which is what limits ds - and also don't include them as a k-packet / macro-atom channel following absorption) then they shouldn't cause an issue and can speed us up. However, it will be situational as to what is negligible what and when - when I was doing it for the YSOs I expect the regimes might be rather different. How this does (or doesn't) interact with e.g. inner shell cross sections would depend on the machinery we use to deal with such processes - in terms of the existing macro atom infrastructure, I don't think we do / can properly handle inner-shell ionization so it is probably always going to be an approximation what we do in that case. At the moment, do those processes attenuate the photon weight as well / instead? or if they don't contribute to kbf do they simply not appear at all?

**Comment by kslong** [comment]
This is a question, but not one we are going to work on in the near term. So I am labelling it a zombie issue and closing it.
