### ISSUE TITLE
Fiducial agn model labels scattering 1000 per inclination angle in spec file

### ISSUE THREAD

**Issue by mandyhewitt** [sirocco-rt/sirocco#658]
Latest version of fiducial agn model, modelled using the standard fiducial_agn.pf parameter file (from dev branch examples repository), shows scattering 1000 as the label of each flux column per observer angle in the .spec file. 

MAXSCAT recently changed from 1000 to 2000 in python.h, however, treatment of selected scattering within spectra.c and extract.c are inconsistently using a mixture of -1 or 999 to show that all scattering events should be shown in the spectrum (as opposed to e.g. only showing single scattering via the diagnostic file). 

This results in _sc:1000 appended to the angle flux columns i.e. A20P0.50 is printed on the spec file as A20P0.50_sc:1000:

Freq.        Lambda    Created  Emitted   CenSrc     Disk     Wind  HitSurf Scattered A20P0.50_sc:1000 A40P0.50_sc:1000 A60P0.50_sc:1000 A70P0.50_sc:1000 A75P0.50_sc:1000 A80P0.50_sc:1000 A85P0.50_sc:1000 A89P0.50_sc:1000
1.154432e+15 2596.884      1.3943     1.3472   0.001194     1.3267   0.019341   0.055875    0.11127     3.0242     2.3466     1.2562    0.73604    0.36146    0.07285   0.027854   0.027151
1.155815e+15 2593.775      1.4067     1.3548 0.00071819     1.3354   0.018669   0.055051    0.10484     3.0622     2.2619     1.2674    0.78891    0.35084   0.066942   0.026124    0.02354
1.157199e+15 2590.673      1.4012     1.3592          0     1.3364   0.022792   0.056623    0.11613      3.178     2.3171     1.2332    0.75076    0.33789   0.069529   0.026003   0.023375
1.158583e+15 2587.580      1.4392     1.3899   0.000481     1.3697   0.019721   0.056518    0.10149     3.1815     2.3627      1.281    0.77007    0.34606   0.072024   0.030554   0.028294

**Comment by kslong** [comment]
I guess this is not totally surprising as we don't use the scattering option that often and it is not in our regression tests.  You probably just need to set some of the defaults differently.

**Comment by mandyhewitt** [comment]
The main issue here is that scattering is not set on. This is with the default parameter file.

**Comment by saultyevil** [comment]
I think this is because of a hardcoded value of `geo.scat_select`. In `init_observers()` in setup.c, we hardcode `geo.scat_select = 1000`. I think this should actually be set as MAXSCAT, as going by this,

```Log ("OK n>MAXSCAT->all; 0<=n<MAXSCAT -> n scatters; n<0 -> >= |n| scatters\n");```

Then in spectrum_init(), we append the labels to the table headers [here](https://github.com/agnwinds/python/blob/cfb7a832a9e113c3f23a925946a1743f60a3e63e/source/spectra.c#L212). I don't think this affects the actual photons which are extracted, since that mode isn't turned on, I think it just changes the name of the headers. 

Either way, it looks like a small bug which shouldn't be hideous to fix. I don't think it's a big problem unless you have a plotting script which is expecting a certain style of header in the .spec file.

**Comment by kslong** [comment]
Implemented the fix suggested by @saultyevil
