### ISSUE TITLE
Improving the Disk Temperature Distribution and SED for Black Holes (and Neutron Stars)

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#660]
An improvement to our modelling of AGN and XRBs would be to use a Novikov-Thorne disk,
which does not have a hard inner boundary.

**Comment by jhmatthews** [comment]
What is the NT boundary condition? It's not a zero-torque one, i.e. dOmega/dr = 0?

**Comment by lazygun37** [comment]
Even though this issue is labelled with "Novikov-Thorne", I think it's clear from context that it's really about the appropriate treatment of thin disks around black holes (and perhaps NSs) more generally. 

With this in mind, there are actually (at least) 3 distinct issues here:

1. The Novikov-Thorne model is essentially "just" the relativistic version of Shakura-Sunyaev, in the Kerr metric. It still assumes the same zero-torque boundary condition (ZTBC), just now at the ISCO.

2. There have also been discussions in the literature whether the ZTBC is actually correct. I think this is what Knox refers to above when he talks about models not having a "hard inner boundary".

3. Incomplete thermalization means that the escaping radiation isn't really BB, which is often "corrected" via a "spectral hardening" factor f, which is applied to the specific intensity in a way that keeps the integrated flux constant.

(There is a fourth potential issue associated with the direction-dependence of the radiation field in the relativistic limit, but I think that's tied much more closely to  what we might want to do about GR more generally than to this particular issue.)

I have written a little python code to check how important (1) is. It looks to me like it can modify the peak temperature by perhaps a factor two or 2. So, not completely irrelevant, but at the same time not hugely important, given all the other uncertainties in our modelling. It may be worth including though, simply because it's not hard to do...

The ZTBC question is more thorny. I think at some level, it is possible to treat a limiting case here by effectively removing the "turnover" from the T(R) law.  One could do this in an ad-hoc way. A discussion of the physics is here https://ui.adsabs.harvard.edu/abs/2002ApJ...573..754K/abstract and https://ui.adsabs.harvard.edu/abs/2003ApJ...592..354A/abstract and https://ui.adsabs.harvard.edu/abs/2001ApJ...561L..81R/abstract (and many others). My feeling is that this isn't worth doing really, and certainly not beyond just considering limiting cases, as per above.

I think by far the most important issue is actually spectral hardening. I think this can have quite important consequences for the SED. And, actually, I don't think we have much of an excuse not to incorporate this, because the correction factor can be approximated pretty easily, based on https://arxiv.org/pdf/1809.05134.pdf

So, my suggestion is that we implement at least (1) and (3) with fairly high-priority. We could implement the limiting case of no-turnover for (2) as well at the same time,  if we felt that was worth it. 

I'm giving this high priority.









https://ui.adsabs.harvard.edu/abs/2007A%26ARv..15....1D/abstract

**Comment by kslong** [comment]
This is one of many enhancements that would be useful to include in Python, but is not a bug, so I am labelling a zombie issue for now.   It may become important if we have a bigger concentration on XRBS.  For now, I am removing the high lable, adding a zombie label and closing it.
