### ISSUE TITLE
imported models - only T_e is set

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#667]
For imported models, we have the option of setting the a temperature.  But this temperature is only appled to T_e, and not T_r.  Both should be initialize, possibly using Leon's old approximation that T_e was 0.9 T_r.

**Comment by saultyevil** [comment]
In one of my test runs of Jane Dai's model, I have in the model grid, dai.grid.txt, a run of gas temperatures provided to us. The function which reads in an r-theta grid has no trouble reading in the grid, but the temperature I have provided does not seem to be set.

In the provided parameter file (which doesn't all make sense, as I was just testing what the grid looks like), I do not run any ionization cycles but go straight to the spectral cycles so I can get some optical depth diagnostics - but I quit the program before I run any spectral cycles anyway.

When I run windsave2table after doing this and plot the snapshot, I get something looking like this, where the electron and radiation temperatures is set to a single temperature throughout the grid.

![image](https://user-images.githubusercontent.com/19627279/75260568-b8541e00-57e1-11ea-9b8b-715f526b9ab5.png)

As far as I can tell, whilst we read in the temperature for each cell and store it in `xx_rtheta.t[icell]`, this variable is never used again and only has scope in the file `import_rtheta.c`. I think this is the case for cylindrical models as well, but for the struct `xx_cyl.t`.

Incidentally, the temperature in the above plots is ~10^4.6 ~ 40,000 K which is the value of Wind.t.init. It looks like the colour bar has a slightly different scale for the radiation temperature, so I assume we are actually initialising T_e ~ 0.9 T_r in this case.

My guess is that this is to do with this if in define_wind() in wind2d.c line 339.

```c
if (zdom[ndom].wind_type == HYDRO)
{
    plasmamain[n].t_r = hydro_temp (x);       
}
else
{
    plasmamain[n].t_r = zdom[ndom].twind;
}
```

It looks like t_r is initialised to zdom[ndom].twind (or Wind.t.init) unless we're using a hydro model, where it is then set to whatever hydro_temp returns for the given position x.

**Comment by jhmatthews** [comment]
Just a thought Ed, but we should probably avoid sharing the model grid on github yet - maybe put it in a privately accessible place for the moment.

**Comment by saultyevil** [comment]
For the sake of completeness, I checked if the same problem I have is happening with cylindrical imported models. For this test, I ran cv_standard.pf and then used py_progs.py/import_cyl.py to create a model which I can import. At this stage, I think it's also worth noting that I believe when we supply a temperature, it is actually T_r which we are setting and not T_e. I think this is the case for two reasons. 1) import_cyl.py outputs T_r and not T_e and 2) we set T_r using Wind.t.init, so we initialise the radiation temperature first and then use Leon's approximation.

[cv_import.pf.txt](https://github.com/agnwinds/python/files/4262950/cv_import.pf.txt)
[cv.import.txt](https://github.com/agnwinds/python/files/4262957/cv.import.txt)

Anyway, when you look at cv.import.txt, you can see that there is a range of radiation temperatures. With the above .pf, I import the wind and run no ionisation cycles but 1 spectrum cycle but quit before the spectrum cycles start - this way I have a wind_save with too much work. Each cell in the grid has the same temperature, as can be seen below.

![image](https://user-images.githubusercontent.com/19627279/75468730-95fb0580-5985-11ea-9c24-87ae325a4a15.png)

I've added a sort of hacky, less than ideal, fix where I store the input temperature in the wind structure and transfer the temperature over in define_wind(). The temperature is now initialised properly. A related issue was that, due to a typo, we would never read in the temperature for some coordinate systems.

![image](https://user-images.githubusercontent.com/19627279/75469670-4fa6a600-5987-11ea-9eb4-6805d4f2a3b0.png)

I'll merge in a proper fix very soon - probably with some kind of global imported models struct or clever trick so I don't break backwards compatibility by adding to the wind structure.

**Comment by kslong** [comment]
I am afraid am not surprised at what you have found, Ed.  We were focused on the cylindrical models and really only checked the others to see if they allowed photons to go through the grid.  That is the danger of "hacky" programming, which I am glad to hear you will not merge into Python.

Here is what I think should happen.  

- If a grid has no temperature, then both the initial Te and Tr should be set to the value in the .pf file
- If the input grid, has one temperature.  Both Te and Tr should take that initial temperature
- If the input grid has two temperatures for each grid cell, then the first should be Te and the second Tr.

It should be easy to distinguish these cases by the number of input variables in each line.

Please make sure this is documented, both in the code, and somewhere in the Sphinx documentation.

**Comment by saultyevil** [comment]
Pull request #670 fixes this issue.
