### ISSUE TITLE
Using Python for simulating circumstellar interaction spectra

### ISSUE THREAD

**Issue by manolis07gr** [sirocco-rt/sirocco#681]
Hi all,

I am interested in using Python to simulate the spectra of Supernova ejecta - circumstellar/wind interaction. In such a situation one has strong velocity gradients between the forward and the reverse shock that forms following the interaction of supernova ejecta with a dense, massive circumstellar shell. The expansion of the material (SN ejecta + shell) is on-going however it is not homologous as is the case for a typical supernova. As such, a combination of nLTE effects and non-homologous treatment is essential to get this right. As an example, Type IIn supernovae show features of circumstellar interaction in their spectra (narrow emission lines of hydrogen formed due to hydrogen recombination). A first test, would be to reproduce Type IIn SN spectra.

Does Python have the capacity to treat such a problem?

Kind regards,

Manos

**Comment by kslong** [comment]
HI  Manos,

This is not something we have tried with Python, and undoubtedly the answer is going to depend on the details, but it might be worth a try.  We have made comparisons of Python to SN model spectra generated with Tardis and they are not "crazy".  

It is possible to import a structure (1-d in this case), in which you have defined the the velocities and densities and and initial temperature and to calculate the ionization structure and emission.  And it is possible in the macro-atom mode of python to calculate the recombination spectrum, as long as the radiation field of whatever you are calling the photosphere is defined.

@ssin who knows much more about SN spectra than I may also want to comment.  

Best,
Knox

**Comment by manolis07gr** [comment]
Dear Knox,

I appreciate you for the response back, sounds like that, at least to get the ionization structure and emission, as well as a recombination spectrum for my problem, non-homology (i.e. my 1D supernova ejecta profile including sharp gradients at the interface with the circumstellar medium), would be possible. A first such test would be a typical, H-rich Type IIn supernova spectrum. I have tried using TARDIS to get to that but the capabilities are still not there (i.e. H-recombination and H-opacities are incomplete for Type II-type SN spectra). Any more advice would, of course, be welcome as I venture into using Python for this application.

Kind regards,

Manos

**Comment by ssim** [comment]
Dear Manos and Knox,

What you say, I think, is correct - namely that Python should be able to do a better job of the NLTE hydrogen physics than the publicly available TARDIS version can at the moment. 

However, there will still be things you'll need to think about that may make this quite a challenging problem. First, although Python does not require an homologous velocity law, it does (by default) still assume the velocity law is smooth - so if you want to handle models with sharp velocity gradients you will need to consider this - i.e. whether those are physical shocks (and therefore better treated as discontinuities) or just steep gradients. Python is, after all, a Sobolev code.

Also, you'll need to decide what to do for radiation / energy sources. Python, like TARDIS, has its roots in radiative equilibrium problems, where the radiation field is imposed as a boundary condition at surfaces and then the matter in the computational domain is assumed to be in radiative equilibrium with those boundary surfaces (and otherwise open boundaries). Depending on exactly what you are aiming to do, you will therefore need to think about placing a photosphere and/or potentially imposing temperatures if you want to handle a shocked region that is above (or crosses) the photosphere. 

The spherical symmetry of the problem may also mean that optical depths from a thermalisation photosphere are very high, which we know can lead to problems sometimes in these sort of Monte Carlo codes.

I should note that the comparison that @kslong refers to that we've made before were all for moderate optical depth SN models for either Ia or IIP type conditions - and @kslong is correct that those work sort of ok. However, IIn's are a different challenge - it will depend on exactly what you want to get out from the models how well Python can cope, I think.

Stuart

**Comment by manolis07gr** [comment]
Dear Stuart,

I appreciate you for the thorough response and feedback. I guess at this level, I can attempt to post-process some interaction profiles I have and see how good/bad the first iteration of results is. I am sure there will be a (rather steep) learning curve as I familiarize myself with Python, so it is likely I will bother the community again with questions asking for help. Thanks to both for taking the time to look at my issue and for all the feedback!

Manos

**Comment by jhmatthews** [comment]
Since we are trying to better keep track of issues with the code, I'm closing this issue for the moment - Manos, if you have questions, you can email or comment on the closed issue.
