### ISSUE TITLE
Option to specify NWAVE to tailor spectral wavelength binning for plotting

### ISSUE THREAD

**Issue by mandyhewitt** [sirocco-rt/sirocco#747]
In order to increase the resolution of spectra, we need the ability to change the NWAVE parameter for spectral wavelength binning. It is currently defined as 10,000 in python.h. It would be good to be able to run models and change the value of NWAVE either via the command line or parameter file. For polarisation, I currently require  NWAVE of 1000 and hard code the change in my branch. We also need to change this value for Fe K-alpha work. In Tardis code this option can be tailored.

I'm not sure if this option is available already in python via running the code in a diagnostic mode nor if there is a reason it should not be adjusted but if this is a good enhancement to implement then Rahul and Mandy will try and implement it during virtual-belfast.

**Comment by kslong** [comment]
I agree that for many purposes, 10,000 seems excessive.    

I would prefer that you NOT do this on the command line, but do it as a parameter and insert the fix somewhere near where this line line is set

Spectrum.type(flambda,fnu,basic)              flambda

You will want to name the variable something like

Spectrum.nwave

Note that there is an issue with this.  Currently NWAVE is a global variable and it used to allocated structures with a certain dimension. This allocation preceeds anything you read in.  So either you will need to dynamically allocate all of the spectrum arrays, or you will leave NWAVE as it is, but fill only nwave values of the array.  To do this, you will need to 

* define a new variable, nwave,  in the geo structure (probably near the other spectra related variables).  You will, I think need it in the geo structure so that you can restart models.
* replace NWAVE with geo.nwave in many places in the code.


These changes are not hard, but they will require some robust testing to make sure for example, you can re-import and continue a model.

Good luck!

**Comment by kslong** [comment]
@Higginbottom   @mandyhewitt   if @kslong  were to implement this, would you wand

* to apply this just to the detailed spectra or to both.  If just to the detailed spectrum, then probably this nunber would need to be smaller than the maximum value we store.
* Assuming the answer to the above question is just the detailed spectra, then would you prefer to specify nwaves directly or delta lambda.  
* Do you have any other thoughts on what would make this feature most useful?

**Comment by mandyhewitt** [comment]
@kslong I would like to be able to apply the NWAVE setting to both detailed spectra and have the possibility to set it also in the ionization cycle. 
I would prefer the value to be specified directly (as this is simple), however, I do not understand the use of  delta lambda - could you give your thoughts on this? 
The feature would be most beneficial if it had some intelligence built in. My understanding is that we use NWAVE for binning purposes to produce better spectral results/plots - if there was a way to, for example, learn which binning gives the best spectra that would be very useful - but would require clear logging and an override function too. I have no idea if this is possible or worth the investment to code up though :)
Feel free to assign yourself to this issue - I'm not looking at it this week.

**Comment by kslong** [comment]
@mandyhewitt   Specifying by delta lambda would mean that you would give a number say, 0.25 to indicate that you wanted the spectrum  0.25 A bins.  nwave would then equal (lambda_max-lambda_min)/delta_lambda.  Most observers think of their spectra in units of delta lambda rather than the total number of bins they have between two wavelength intervals.

Figuring out what a user wants to produce optimal binning for her purposes is not something I am smart enough to do, but once the infrastructure is there, others could in principle incorporate a suggestion as to the binning assuming this becomes a variable that is queried.

**Comment by kslong** [comment]
@saultyevil  has fixed Python so the user can specify the number of bins in the detailed spectra, so I am closing this issue.
