### ISSUE TITLE
kappa_ff

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#750]
kappa_ff seems to explicitly assume that ion 1 is ionized H, and ion 4 is double ionized He.  Also free emission is only possible for these two ions.  

Consider 

- Checking that the ions are the ones that are expected

- Consider adding more highly ionized species into the FF calculation

**Comment by Higginbottom** [comment]
If the free free gaunt factor data file is not present, then it is true that 

a) the ions are hard wired and
b) only H and He are used.

I think that the second point is because the error in not knowing the gaunt factor is probably greater than including minority ions. It was written this way to preserve the old behaviour when the gaunt factor file was included.

However, I believe that if the gaunt factor data is read in - then al ions contribute and there is no assumption.

We may need to fix the fallback position, or do away with it entirely and error if the gaunt factor file is not present.

Nick

**Comment by kslong** [comment]
This really was a misreading of the code. Some documentation has been added to try to avoid this question in future.

The basic story is as follows.  

* In the original version of the code, it is true that the ff opacity was estimated based only on H and He, and that estimate of the ff opacity included no gaunt factor
*At some point, he code was modified to include all ions and to include a gaunt factor based on a table provided by Sutherland, R.~S. 1998, MNRAS, 300, 321. What happens in this case, is that a prefactor to the ff opacity is calculated at the for each ionization cycle and stored in  plasmamain[].kappa_ff_factor
* Today, unless one fails to read in the Sutherland table in the atomic data, the gaunt factors are calculated on this basis.  However if one leaves the Sutherland data out of the atomic data, the code will go back to the original approach.

In inspecting the code, it seems likely this code could be made a bit more transparent.  Most of the routines are in radiation.c, but the calculation of gaunt_ff based on Sutherland is in emission.c

Having done this, I am closing his issue.
