### ISSUE TITLE
Negative div v for inwind cells with cmf changes

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#782]
When using the new CMF mode, I get the following error:

```
wind_div_v: div v %e negative in cell %d Domain %d. Major problem if inwind (%d) == 0
```

In classic mode, this error occurs only three times and only one cell is inwind and it hasn't been a big deal before. Now, though, with the new CMF changes I am seeing this error happen for 838 cells (of which only 3 aren't inwind) when there are a total of 2155 cells which are inwind - roughly 38% of inwind cells.

This previously didn't happen with *just* the SR frequency changes. So I think it must be related to new CMF changes. I've added a pf below which shows the error.

[tde_opt.pf.txt](https://github.com/agnwinds/python/files/5408544/tde_opt.pf.txt)

**Comment by saultyevil** [comment]
I've plotted where the divergence is negative. They're pretty much in the part of the wind where the rotational velocity is highest, but could just be a coincidence.

![div_v](https://user-images.githubusercontent.com/19627279/96597123-5eaae180-12e5-11eb-8d7a-4f23ecb84f70.png)

![image](https://user-images.githubusercontent.com/19627279/96598769-1f7d9000-12e7-11eb-957a-c69ab244d3fa.png)

**Comment by kslong** [comment]
Interesting.    This certainly looks like a bug. The old approach to calculating div V is different from the current one (independent of the question of co-moving frames).  In the old approach we calculated div V at the center of the cell explicitly,  but James noted that we could use velocity gradient tensor to do this, and this seemed a good idea on the basis of code simplification.  But on slack you will see we noted that this change did cause the spectra to change slightly which we had not expected.    No one followed this up.

**Comment by kslong** [comment]
The code here looks fairly straight forward.  The divergence is calculated as the trace of the velocity gradient tensor. The velocity gradient tensor is calculated from model velocity in both the classic and the cmf case. The main difference is that the is a conversion of velocity from the observer to the local frame for the cmf case.  It may be that we should carefully check that obsever_to_local_frame velocity is giving us what we expect.  This is some kind of sign error problem is my guess

**Comment by saultyevil** [comment]
Yeah, I think that's true. I can't see a problem with tacking the trace of the matrix. Where I left it off last night was looking at the velocity transformation, which I think is where the issue is. I found that for the two velocity vectors, which had all positive components, given to observer_to_local_frame_velocity resulted in negative velocity components. So I think there is possibly an error somewhere. 

I've double checked what is implemented in the function and I think it agrees with the comment stating the transformation,

```
/*  The transformation formula is
   v_cmf=c1*(v_obs/xgamma-v+c2*v);
*/
```

Hmm...

**Comment by kslong** [comment]
Looking at the calculation of grad_v, it appears that in these models the rotational velocity dominates, both in the classic case and the ful rel case.  This is calculated to be negative, I guess because when you go in the +y direction for ds, you are also moving outward in radius. At least for the elements I have inspected the other numbers that go into the divergence are positive, but by a much smaller amount.  This does not explain though why cmf is different from classic, which it definitely is.

**Comment by kslong** [comment]
OK, I understand the error here.  The problem (or at least one major problem) is that we are not computing the derivatives accurately.  Currently this is just a simple forward derivative where we set the step size to 0.001 of the distance from the central object.  Reducing the step to 0.00001 fixes the negativity problem.  

I don't think that is what we should do however.  I expect we should be calculating a robust derivative, using a [gsl function](https://www.gnu.org/software/gsl/doc/html/diff.html)

This is going to involve creating a function that can accept parameters.  It looks like the way to do this is to pass a structure as described [here](http://www.math.utah.edu/software/gsl/gsl-ref_402.html)

**Comment by saultyevil** [comment]
I found the same thing yesterday too. I tried fixed ds values of 1e3, 1e4, 1e5 and then used the cell specific dfudge as well. I found that ds = wmain.dfudge and ds = 1e5 got rid of the negative problem. Anything smaller *reduced* the number of errors, but some cells still had negative divergence. So if ds is too small or too big, then it seems bad. I think for now, I will compare the differences between new CMF with smaller ds and the classic method. If they're the same or similar, then I propose using a smaller ds as a temporary hotfix to the problem.

But I've gotten myself into a muddle and I'm a bit conceptually confused about the velocity transformation now. We provide two observer velocities at two points, x and x+ds, and get the velocity difference in the CMF out.  Can we use it to calculate the velocity difference between the points x and x+ds? Currently, we are saying V_obs is the velocity at x+ds and V (the velocity of the CMF measured by obs) is the velocity at x. Then the transformation gives V_cmf = V_x+ds - V_x. I feel confused... is this correct?

I agree on using gsl instead to calculate an more reliable derivative. Right now, I can see how to use gsl to calculate observer frame gradients, since that is the frame they are in. But it's muddier in my head how we would transform the derivatives into the CMF.

**Comment by saultyevil** [comment]
I've tested the difference between the calculated divergences for the TDE model and our standard CV model.

**tde_opt_cmf**

At least in the model I posted in the original post, by using `ds = 0.00001 * length(x)` the difference between the new and "classic" method is small. In the plot below, column one and two are the divergence for CMF and classic respectively. The third column is the difference abs(div V_cmf - div V_classic). So the biggest difference is on the order ~10^-7. I presume the difference comes from the fact that the ds used in the old and new methods are slightly different, but I haven't proved this to myself definitively.

![div_difference](https://user-images.githubusercontent.com/19627279/97010066-d7f04180-153c-11eb-8e90-d4ad15693926.png)

And now the same thing, but with the original `ds = 0.001 * length(x)`.

![div_difference](https://user-images.githubusercontent.com/19627279/97010727-b6dc2080-153d-11eb-8a29-43f75c2e3c33.png)

Interesting, the difference in positive divergence cells is still not massive - the missing chunk in the lower left of column 1 is due to taking the log of negative divergences. I'm interested in what this slither of cells at the bottom of the old method is though..

**cv_standard**

 `ds = 0.00001 * length(x)`

![div_difference](https://user-images.githubusercontent.com/19627279/97011956-3ae2d800-153f-11eb-95a0-e60768e80c96.png)

`ds = 0.001 * length(x)`

![div_difference](https://user-images.githubusercontent.com/19627279/97012156-79789280-153f-11eb-9024-7f800c751e4c.png)

There seems to be a bigger difference between the two methods for the cv model, but appear to perform identically for both values of ds. Hmm..

**Comment by kslong** [comment]
I think we are probably agreed that for a standard SV (or KWD model), there should be no negative divergences, but this is a necessary but not sufficient condition for knowing the answer is correct.  However we do not expect the calculated values int the CMF frame to be identical to the old calculation, except in the limit of low velocity, where relativity does not matter.  

I do think there is an issue about whether we are calculating the gradients properly in the cmf frame, but it does not have to do with the velocity addition part of the routine.    That part is critical.  My issue has to do with ds in that we divide by with.  Here is what we do now:

1. We take a center position and get the observer frame velocity there,
2. We take a step ds in the observer frame
3. We find the observer frame velocity at that point
4. We use the relativistic velocity addition law to fine the relative velocity in the comoving frame.  This is generally greater than the relative velocity in without accounting for special relativity.  (This is easy to see.  If you have two particles moving in the same direction,  one moving at 0.999 the speed of light and one moving at 0.9999 the speed of light in the observer frame, and calculate how fast they will be moving apart from the perspective either particle, you will find that in this co-moving frame, they are moving apart at greater than 0.0001 C)
5. We divide by ds

The last step is I think an error. We should be dividing by ds in the co-moving frame.  This will be (if the particales are moving in the same direction) larger than ds_obs. and will tend to reduce the gradient.

I will work on implementing this, probably using gsl, which I also think is necessary, because we also need to careful of round off erros (As is emphasized in the Numerical Recipes in C discussion of derivatives).

**Comment by kslong** [comment]
OK, here are a few more comments

1.  If we do not use the gsl routines, we would be better off using a symmetric version of the derivative, that is taking values at +ds and -ds and dividing by 2ds.
2. My first attempt to implement this ended in failure because we calculated the gradient tensor everywhere, including non-physical regions of the wind, and with our parameterization in the regions had velocities that exceed the speed of light.  It is not possible to do the observer to lab frame corrections in this case

**Comment by kslong** [comment]
@saultyevil   The changes to correct his problem have been incorporated into dev. The only thing possible outstanding would be to rewrite the routines to find the best ds, probably by using a gsl routine.  The concern involves not just the trace terms in calculating the velocity gradient but also the off-diagonal terms.   Unless we want to work on this issue, and maybe we should, I think the issue can be closed.

**Comment by saultyevil** [comment]
I can confirm I am no longer seeing negative divergences. I think we can close this issue and create a new issue for using GSL or an adaptive step size if we want to work on that.
