### ISSUE TITLE
balmer decrement test is failing in travis

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#832]
Our travis tests are failing. The problem appears to be in the balmer decrement test.  

An example is in 

https://travis-ci.org/github/agnwinds/python/builds/762647125

We need to understand if this is a problem @jhmatthews

**Comment by saultyevil** [comment]
James fixed this error a couple of weeks ago, so I'm going to close this.

Here are the comments he made about the fix:

I've modified the. balmer_test param file the travis tests now pass. The changes to velocity gradients clearly altered the escape probabilities and took us away from the case B limit I think - the parameter file itself is rather arbitrary and was arrived at in an ad hoc way, I think. I just modified the velocity law a little (which now goes from 1 to 1.2 cm/s!) such that the velocity gradient was a little shallower, and this  now gives quite good agreement. I'm keeping this test in because it does actually show up things that change in code operation, so seems useful if not perfect.
