### ISSUE TITLE
PY aborted due to "serious population inversion"

### ISSUE THREAD

**Issue by keithini** [sirocco-rt/sirocco#836]
When running the attached parameter file PY aborted - apparently due to a serious population inversion. 

Note that the parameter file calls a bespoke disk temperature file (Temps01cm.csv - attached) and also the He abundance has been changed from the default by editing line 10 of  /data/atomic_macro/h10_hetop_standard80_elem_ions.dat to read "Element    2   He   11.70     4.002602"

This was run using mpi -n 16 py keith07.pf

Zip file of diagnostics attached.

[diag_keith07.zip](https://github.com/agnwinds/python/files/6280725/diag_keith07.zip)

[h10_hetop_standard80_elem_ions.dat.txt](https://github.com/agnwinds/python/files/6280695/h10_hetop_standard80_elem_ions.dat.txt)
[keith07pf.txt](https://github.com/agnwinds/python/files/6280700/keith07pf.txt)

[temps01cm.csv.txt](https://github.com/agnwinds/python/files/6280704/temps01cm.csv.txt)

Reported to Knox Long (7 April 2021) who requested that this be raised on github.

**Comment by keithini** [comment]
[keith07_errors.txt](https://github.com/agnwinds/python/files/6288606/keith07_errors.txt)

When the exit command was suppressed the program ran to completion. The error summary is attached.

**Comment by saultyevil** [comment]
This is a purely documentation update, I haven't actually solved anything yet... but to update on this issue, here's what I think I understand about it.

It's unrelated to the macro atom part of the model. Specifically, the program is crashing when calculating the Sobolev optical depth for the line (line 410) associated  to `nion = 5`, which is C I and not a macro atom. Also, if there is a population inversion for the macro atoms, we deal with that following Lucy (2003, section 6.3). For the simple atoms (i.e. metals), however, I believe we do not deal with population inversions at all. 

For the error posted, the program doesn't exit due to updated populations having a population inversion, anyway. The program exits whilst trying to calculate a new temperature, before updating the populations/densities/etc. The error is coming back to one we've worried about before, and have already implemented some safety catches.

This specific result below, xden_ion, is negative (resontace.c, line 836) when calculating the Sobolev optical depth for the C I line,

```
xden_ion = d1 - lptr->gl / lptr->gu * d2;
```

There's already a couple of if statements to try and avoid situations where this is negative, but these don't apply to the current problem (clearly). 

d1 and d2 (the lower and upper level population number density), to me, seem to both be "on-the-fly" calculations, gotten using a dilute blackbody approximation. At this stage in the program, we have an updated radiation temperature and a "trial" electron temperature to try and balance the heating/cooling rates in a cell. 

Annoyingly, during photon transport, there are no population inversions when calculating the optical depth for the *exact same line*, using the exact *same code*. Something about the "semi-updated" configuration (of t_e and t_r) is probably causing the problem here.

For extra credit, here is the backtrace before reaching a population inversion error.

![image](https://user-images.githubusercontent.com/19627279/115551188-a0bbdc80-a2a2-11eb-8154-2a8cd5774c47.png)

**Comment by kslong** [comment]
With the latest update to dev, this problem seems to have gone away.  @saultyevil   Do you agree we should close this, at least until we have an example that produces the error again?

The errors are now

```
Collated errors for 16 processors
Recurrences --  number of threads with error -- Description
	 6366 --    16 -- extract: Should not have hit secondary
	 1424 --    16 -- The net flow out of simple ion pool (%8.4e) > than the net flow in (%8.4e) in cell %d
	 1275 --    16 -- rand_wind_thermal_trapping: photon had more than  %d internal scatters in cell %d at %e %e %e with p_norm %e zmin %e tau_min %e
	  112 --    16 -- getatomic_data: line input f odd (may be OK if Macro): %s
	   48 --    16 -- Ignored %d simple lines for macro-ion %d
	   16 --    16 -- Ignored %d collision strengths with no matching line transition
	   16 --    16 -- check_grid: some cells have large changes. Consider modifying zlog_scale or grid dims
	   16 --    16 -- wind2d: Cell %3d (%2d,%2d) in domain %d has %d corners in wind, but zero volume
	   16 --    16 -- Ignored %d inner shell cross sections because no matching yields
	   16 --    16 -- get_wind_params: zdom[ndom].rmax = 0 for wind type %d
	   16 --    16 -- read_non_standard_disk_file: could not convert a line in %s, OK if comment
	   16 --    16 -- check_grid: velocity changes by >1,000 km/s in %i cells
	   16 --    16 -- error_count: This error will no longer be logged: %s
	    7 --     4 -- normalise_simple_estimators: Huge w %8.2e in cell %d trad %10.2e j %8.2e
	    6 --     5 -- trans_phot: %ld photons were lost due to DFUDGE (%8.4e) pushing them outside of the wind after scatter
	    6 --     2 -- translate_in_wind: nres %5d repeat after motion of %10.3e of phot %6d in ion cycle %2d spec cycle %2d stat(%d -> %d)
	    1 --     1 -- pillbox %d interfaces to pillbox is impossible
```

None of these seem to have to do with population inversions.

**Comment by saultyevil** [comment]
I'm not sure which changes could have changed this as recent code changes have mostly focused on the macro atom parts, when this issue is related to simple atom elements. 

I think we can close this for now, but keep our eyes open for a similar issues.
