### ISSUE TITLE
finite() is deprecated

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#84]
We use finite() to check whether a number is "valid" in several routines log.c and spectral_estimators.c, but using this routine is producing warnings because newer compilers deprecate finite.   fineite needs to replaced with the appropriate calls to a routine like isfinite.

Some details about the two routines:

finite -- returns 1 for finite x, 0 for infinite x and NaNs

The isfinite() macro returns a non-zero value if and only if its argument has a finite (zero, subnormal, or normal) value.  The isinf(), isnan(),
     and isnormal() macros return non-zero if and only if x is an infinity, NaN, or a non-zero normalized number, respectively.

Note that subnormal number appears to be a number which is near the end of the range of numbers that can be stored in a computer, and hence has fewer signiicant bits than a normal number.  

This looks like a straightforward substitution, but given that the main routine that uses this involves macro-atoms, I think James should make the changes.

**Comment by kslong** [comment]
Actually, I see that spectral_estimators is the routine which we use to determine whether the photon distribution in a band is better estimated as a power law or exponential function, so Nick is the one who has worked on this the most.  Still the action remains assigned to James.

**Comment by jhmatthews** [comment]
subnormal numbers:

''In the IEEE754 standard, floating point numbers are represented as binary scientific notation, x = M × 2^e. Here M is the mantissa and e is the exponent. Mathematically, you can always choose the exponent so that 1 ≤ M < 2.\* However, since in the computer representation the exponent can only have a finite range, there are some numbers which are bigger than zero, but smaller than 1.0 × 2^emin. Those numbers are the subnormals or denormals.''

These numbers have reduced precision, so not sure if we want to flag them with sane_check?

in the spectral_estimators case we should just replace all finite calls with isfinite().

**Comment by jhmatthews** [comment]
I'm closing this. I tried adding an error condition for subnormal numbers but it seems to throw the error when something is zero and thus throws a lot of errors. I'm therefore closing this issue.
