### ISSUE TITLE
long run times and kpkt emis is -nan in agn_macro and agn_macro_gamma

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#849]
I've been running the agn_macro and agn_macro_gamma models from the regression examples directory. I've run them with with the current version of dev (29 Apr 2021, 119d91b), but also have been finding the same issue with the commit version 47cccd7 (26 Apr 2021 was when I ran it).

agn_macro_gamma completes in a reasonable amount of time. agn_macro does not. MPI process 1 and 2 hang in the final cycle, whilst MPI process 3 is struggling on doing something. I think this is really odd. What's happening with the SR treatment which is changing the run time?

The first thing I've noticed is that I'm getting really odd numbers for the kpkt emissivity and in the photon generation diagnostic output. Here's what I'm taking about, with comments:

```
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  0 matom_abs 0.0000e+00 matom_emiss 0.0000e+00
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  1 matom_abs 3.7383e+43 matom_emiss 4.3755e+43
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  2 matom_abs 4.8801e+42 matom_emiss 2.0288e+42
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  3 matom_abs 2.4716e+42 matom_emiss 6.8915e+41
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  4 matom_abs 1.5231e+42 matom_emiss 4.6729e+41
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  5 matom_abs 1.2302e+42 matom_emiss 2.7357e+41
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  6 matom_abs 1.2159e+42 matom_emiss 2.0055e+41
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  7 matom_abs 6.5342e+41 matom_emiss 1.1585e+41
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  8 matom_abs 7.8790e+41 matom_emiss 9.3020e+40
Macro Atom level emissivities (summed): z  1 i  1 macro  1 n  9 matom_abs 6.2798e+41 matom_emiss 7.3809e+40
Macro Atom level emissivities (summed): z  1 i  2 macro  1 n 10 matom_abs 1.6454e+44 matom_emiss 1.4706e+44
Kpkt emissivities (summed over cells): kpkt_abs 5.5575e+43 kpkt_emiss     -nan
Totals: f_matom 1.947573e+44 f_kpkt -nan

// Above line has f_kpkt -nan, but f_matom is finite. Something wrong with kpkt, then?

!! xdefine_phot: lum_tot 2.30e+46 lum_star 0.00e+00 lum_bl 0.00e+00 lum_bh 1.00e+43 lum_disk 2.30e+46 lum_wind 0.00e+00
!! xdefine_phot:   f_tot     -nan   f_star 0.00e+00   f_bl 0.00e+00   f_bh 9.15e+42   f_disk 1.68e+46   f_wind 0.00e+00   f_matom 1.95e+44   f_kpkt     -nan 
!! xdefine_phot: wind ff 1.96e+44       fb 8.15e+44   lines  2.50e+46  for freq 1.15e+15 1.50e+16
!! xdefine_phot: disk                               lum_disk 2.30e+46 2.30e+46  1.43e+40 
!! xdefine_phot: heating & cooling  due to adiabatic processes:         0.00e+00 3.99e+40 
photon_gen: band 1.15e+15 to 1.50e+16 weight   -nan nphotons   666666 ndisk -2147483648 nwind       0 nstar  666666 npow -2147483648

// here we have -nan weight and negative numbers for disk photons and power law photons? 
// the numbers aren't adding up, really...
```

The above odd output doesn't happen in the rest of the regression tests, which aren't using macro atoms. So it must a macro issue. 

I'm also having issues with restarting these models from the spectral cycles because the code is struggling to renormalise a vector where all 3 components are 0.  I haven't tried from the ion cycles, so maybe there is trouble there too

The above information is true when ACCELERATED_MACRO is TRUE, which I believe is now the default now. The problem does not happen when ACCELERATED_MACRO is FALSE.

I see the same problem when I run cv_stall.pf from the first post in issue #829. @kslong, can you confirm the same -nan's in your diag files? FYI, I'm keeping this issue separate from #829 for now, as I'm not sure if Knox is using the accelerated scheme or not when the issue was raised by in mid-March. If there's some overlap in the end, then I'll close this issue and merge with #829.

**Comment by kslong** [comment]
Yes,  this is all the same problem.  If you track it back a bit you will find that there are gammas (the gammas used by macro atoms) are negative, which should not happen.  The branch bug829_cv_stall has some of the diagnostics printouts that I have been looking at.

**Comment by jhmatthews** [comment]
A few comments / questions. 
* Firstly, Ed, do we get the same kind of error messages here that we see in Knox's example, i.e. lots of macro-atom population errors and bad bound-free rates and so on? 

* If it is caused by a negative gamma_old (photoionization rate estimator), it might make sense that it only fails with the accelerated scheme, because in the old scheme we've commented out errors warning about negative macro-atom jumping probabilities and set them to zero, which would mean the old method of emissivities would give a more sensible answer despite presumably a major problem see e.g. line 324 of matom.c:
```C
        if (jprbs[m] < 0.)      //test (can be deleted eventually SS)
        {
          //Error ("Negative probability (matom, 6). Abort?\n");
          jprbs_known[uplvl][m] = jprbs[m] = 0.0;
        }
```
(Aside, I don't really know why we don't want to report an Error here)

* get_gamma is used when macro_pops errors occur to give dilute BB estimators. It's possible the negative gamma estimator is coming from here, or alternatively it could be because we use Blackbody estimators at very high and low frequencies where the estimator statistics are poor. Both of these do an integral, which might be what is giving the negative number if the increment of the estimator is never negative (?). 

* the thing I'm really confused by is why these Errors have suddenly started happening? What's changed that could change this part of the code? Or have they been happening for ages, and the Error reporting has hidden them? 

these comments of course relevant to #829 too, wasn't sure where best to post.

**Comment by saultyevil** [comment]
To answer your first question, James, for agn_macro which is what I'm testing with now, there are no macro_pops or any other macro errors. This is only a short model, just 3 ion cycles, so I can't say for certain if any errors will show later. But in the first three,  none errors.

I don't really have any responses to your questions, but I have tracked down where the NaN error first appears... 

it's not showing up in matom.c or the "regular" macro atom machinery. It's happening in the accelerated scheme, [here](https://github.com/agnwinds/python/blob/119d91b94c4c1c9cf86be779b794568453740082/source/macro_accelerate.c#L937), in the function `f_kpkt_emit_accelerate` in macro_accelerate.c:937. Specifically, my first problem is with the line below when `xplasma` points to `plasmamain[6]`. `penorm_band` is nan so everything after that is nan.

```c
if (fmin > freqmin)
{
  penorm_band += total_free (one, xplasma->t_e, fmin, fmax) / total_free (one, xplasma->t_e, freqmin, freqmax) * mplasma->cooling_ff;
}
```

Both calls to `total_free` return 0. According to the my debugger, and what the code is doing, `0 / 0 = nan`. You can write a short program to demonstrate this, if you have a function return 0 i.e. func_zero() / func_zero() = nan. Here's a screenshot from my debugger showing the error,

![Screenshot 2021-04-29 at 22 40 20](https://user-images.githubusercontent.com/19627279/116608527-34d51600-a92b-11eb-914e-6bc5e91ceb66.png)

You can see `check1 = check2 = 0` and `check3 = check1 / check2 = nan`. I've tried stepping through line by line in `total_free` in my debugger but I can't figure out when 0 is returned. None of the special conditions in the function which return 0 seemed to be triggered and x never appears to evaluate as 0. It's a total mystery to me atm and maybe I'm missing something. 

Maybe it's related to the negative gamma stuff Knox found. I'll try running with the special branch to look at the debug there.

**Comment by saultyevil** [comment]
Running agn_macro with the bug829_cv_stall branch does not produce any gamma related errors.

**Comment by jhmatthews** [comment]
Good spot. I guess it's weird how total_free returns 0 given what you say, but certainly we should add a catch for the case that the denominator is zero in the ```f_kpkt_emit_accelerate``` routine, since 0 is a legitimate result.

**Comment by saultyevil** [comment]
I've found a problem. `xplasma` and `one`, used in `f_kpkt_emit_accelerate`, are both for different cells in the wind. Look below,

```
(lldb) print one->nwind
(int) $1 = 6
(lldb) print one->nplasma
(int) $2 = 147
(lldb) print xplasma->nwind
(int) $3 = 60
(lldb) print xplasma->nplasma
(int) $4 = 6
```

nwind and nplasma are both 6, but I don't think that makes sense... The first expression in `f_kpkt_emit_accelerate` is this,

```one = &wmain[xplasma->nplasma];```

I think this should be `one = &wmain[xplasma->nwind];`!!!

**Comment by saultyevil** [comment]
Using nwind instead of nplasma fixes the problem of NaN kpkt emiss, as it is finite when I use nwind to index. The change also means agn_macro doesn't hang for me in the regression tests, either.

**Comment by lazygun37** [comment]
Great work, Ed!

Sent from my iPhone

On 30 Apr 2021, at 09:22, Edward Parkinson ***@***.***> wrote:

﻿
CAUTION: This e-mail originated outside the University of Southampton.

Using nwind instead of nplasma fixes the problem of NaN kpkt emiss, as it is finite when I use nwind to index. The change also means agn_macro doesn't hang for me in the regression tests, either.

**Comment by jhmatthews** [comment]
Yeah, good spot Ed. Sorry, this is probably my mistake (aside we should probably standardise this so every routine that uses wind and plasma pointers does the same thing). Bizarre that it produced sensible results in some cases! But good that it fixes the error. My guess is that Knox's problems are separate -- since they appeared before we used accelerate macro by default? -- but we should double check.

**Comment by saultyevil** [comment]
The latest changes have stopped these models from stalling. Closing this issue.
