### ISSUE TITLE
Unable to compile Python with GCC 10

### ISSUE THREAD

**Issue by saultyevil** [sirocco-rt/sirocco#873]
Someone external to the collaboration has found that Python does not compile using GCC 10. Whilst each file individually compiles fine, there are errors at the linking stage.

```
/usr/bin/ld: bb.o:(.bss+0xefc9a0): multiple definition of `cdf_bb'; python.o:(.bss+0x37116d40): first defined here
/usr/bin/ld: bb.o:(.bss+0x1fe4): multiple definition of `strict'; python.o:(.bss+0x3621c388): first defined here
/usr/bin/ld: bb.o:(.bss+0x2000): multiple definition of `zz_spec'; python.o:(.bss+0x3621c3a0): first defined here
/usr/bin/ld: bb.o:(.bss+0x2a2c): multiple definition of `xxxbound'; python.o:(.bss+0x3621cdcc): first defined here
```

These errors show up because of changes to the default behaviour in gcc-10, as described on https://gcc.gnu.org/gcc-10/porting_to.html in the "Default to -fno-common" section. The change is fixing "a common mistake in C is omitting `extern` when declaring a global variable in a header file." 

There are two things we can do,
 
1) Use -fno-common as a compile time flag, to override the default behaviour of GCC 10. This flag also exists in GCC 4.8.5 (the oldest compiler I have easy access to), so we would not even have to detect the compiler version.

2) Go through `python.h` and tag the variables are being `extern`, i.e. `extern PlasmaPtr plasmamain`. This isn't hard, and I don't think it should take very long to fix our "common mistake". I think the issue is limited strictly to global variables, so we don't need to go through the code and label functions as being `extern` or worry about the global variables in C source files.

**Comment by saultyevil** [comment]
I have created a new branch named `gcc_warnings` where I've started tagging variables as being extern, as we decided to do in the telecon. I've already gone through atomic.h.

The other aim for this branch is to also clean up the warnings from gcc, such as removing unused variables or checking return variables for standard library functions.

GCC-10 can be installed on macOS using homebrew using `brew install gcc@10` (or `brew install gcc`, but this will install gcc-11 instead which probably has the same issue) and should be able to use it by setting `CC=gcc-10` in the Makefile.

**Comment by kslong** [comment]
@saultyevil @saultyevil   It looks like there are some real subtleties with extern.   As I understand it 

extern int my_integer

declares that my_integer is an integer, but does not actually allocate space to it.

To allocate space to my_integer, one needs to give it a value, e.g

int my_integer= 1

and that this cannot be in some one subroutine some place, but has to be done every time one has a .c file that has 

extern int my_integeer in the header.

So this begs the question of how one does all of this. 

One could put

extern int my_integer;
int my_integer=1;

in the header, but there is a good bit of stuff on the internet suggesting this is not what you are supposed to do.

Ed, I did look at the branch you mentioned above, where you had modified the atomic.h file to add externs,  this does fix some of the compile errors/warnings,  but leaves one with ld errors instead.

Is there a standard we should be following ???

**Comment by saultyevil** [comment]
Ah, I didn't know that exact quirk of extern variables in headers. That's annoying.

If this is the case, I suppose we don't want to use `extern`, because it looks like it will be a lot of work -- and potentially confusing.

It's probably better, then, to use `--fcommon` in the Makefile to go back to the old default behaviour. This is "discouraged" behaviour, but I'm not so sure it matters that much.

**Comment by kslong** [comment]
OK, I think I understand what you are supposed to do.

- In the .h files declare all of the variables and structures as extern.  This does not allocate storage for the structures, it just defines what they would be once they are initialized
- in a .c, e.g init.c  file, initialize all of the variables, for structures you just stay struct whatever;  which creates space for it

One should not initialize a variable in .h, because you are going to apply the .h file to a bunch of other files.  

Here is an example, that seems to work and illustrates what one is supposed to do.

[z.gcc11.211019.tar.gz](https://github.com/agnwinds/python/files/7376420/z.gcc11.211019.tar.gz)

**Comment by kslong** [comment]
So, the branch gcc11 now compiles under gcc-11.  However, I get lots of warnings about sprintf that somehow need to be suppressed, or fixed.  It does not seem snprintf helps.  Do either @saultyevil or @smangham have ideas about this.

**Comment by kslong** [comment]
I have dealt with most of the -Wall errors that arise in compiling python in gcc-11 on the branch gcc11.  The vast majority of the warnings were of two types:

- Problems in sprintf where the compiler recognizes that it is possible to try to put more characters in the  the target string  than the target string has space for. The fix for this was to change the formats.
- Problems where a variable was defined and set, but nothing was done with the variable.  

This has left a small number of warnings, which might potentially be serious, which are in the attached file.  @jhmatthews and others, it might be good for you to take a look at these.

[goo.txt](https://github.com/agnwinds/python/files/7400417/goo.txt)

This version of python compiles with mpicc and clang with no errors or warnings, and my regression tests so far indicate it is identical to dev.

I would like us to check all of this out, because I would like to merge this back into dev, before additional changes ae made there.

**Comment by kslong** [comment]
I have now run several sets of regression tests

- Compiled with clang, the gcc11 branch of the code produces identical results to dev.
- Compiled with gcc-11, the gcc11 branch produces results that differ somewhat, but well within the variations that one expects if the random numbers are not quite the same.

**Comment by kslong** [comment]
@Higginbottom @saultyevil @jhmatthews     I have completed making the modifications associated with warnings produced by gcc11 and merged that branch into dev, after changing the version to 85j. The regression checks look fine, but you all may want to check that the subsidiary routines work as they always have, as these have no regression  tests.  At present the old versions of the various lines are indicated by //OLD, but I would like to remove these 223 lines fairly soon.

**Comment by kslong** [comment]
@saultyevil  has made some updates associated with the routine for calculating optical depths.  The code still complies with gcc11 without any warnings, and as noted earlier the results for the regression tests show some differences that can be attributed to different random numbers, but nothing else.  It seems reasonable to close this issue at this point.
