### ISSUE TITLE
py_optical depth produces compiler error

### ISSUE THREAD

**Issue by kslong** [sirocco-rt/sirocco#880]
I got this compiler error for py_optical_depth on the linux machines at STScI
```
YOU ARE COMPILING FOR LARGE RUNS, -03 -Wall flags
MPI_FLAG= -DMPI_ON
echo "#define VERSION " \"85h\" > version.h
echo "#define GIT_COMMIT_HASH" \"7f59cc9336548cb2a98cb723f4ec80f408d046a3\" >> version.h
echo "#define GIT_DIFF_STATUS" 0\ >> version.h
mpicc -O3 -Wall  -I../include  -DMPI_ON   -c -o py_optical_depth_util.o py_optical_depth_util.c
py_optical_depth_util.c: In function âcreate_photonâ:
py_optical_depth_util.c:342: error: âforâ loop initial declarations are only allowed in C99 mode
py_optical_depth_util.c:342: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [py_optical_depth_util.o] Error 1
```

**Comment by saultyevil** [comment]
This was caused by an inline declaration in a for loop, i.e., `for (int i = 0; i < MAX; i++)`, which isn't supported by default by the compiler at STScI. We could either compile with -std=c99 or, what I've done, is remove the inline declaration in PR #881. 

I've tested this with gcc version 4.8.5, which also had the same error.

**Comment by saultyevil** [comment]
As this has been fixed (and tested, and we haven't seen any further related problems, this issue can be closed.
